!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 26 Mar 2024 17:10
!
!  Differentiation of calc_innovq in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: *(*innovq.diff)
!   with respect to varying inputs: *(bc.sum_mass_flux) *(*innovq.diff)
!   Plus diff mem management of: bc.sum_mass_flux:in innovq:in
!                *innovq.diff:in
SUBROUTINE CALC_INNOVQ_DIFF(dof, mesh)
  USE M_COMMON ! Replaced by Perl Script
  USE M_MPI ! Replaced by Perl Script
  USE M_MODEL ! Replaced by Perl Script
  USE M_OBS ! Replaced by Perl Script
  USE M_OBS_DIFF

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  TYPE(UNK), INTENT(IN) :: dof
  TYPE(MSH), INTENT(IN) :: mesh
  INTEGER(ip) :: searched_time
  REAL(rp) :: mass_flux
  INTRINSIC SIZE
!station number is also BCout number, tested for 1 BCout
  DO iobs=1,SIZE(stationq)
    searched_time = innovq(iobs)%ind_t
    IF (searched_time .LE. innovq(iobs)%nb_dt) THEN
      IF (tc .GE. stationq(iobs)%t(searched_time)) THEN
        innovq_diff(iobs)%diff(searched_time) = bc_diff%sum_mass_flux(1)
        innovq(iobs)%diff(searched_time) = bc%sum_mass_flux(1) - &
&         stationq(iobs)%q(searched_time)
        innovq(iobs)%ind_t = innovq(iobs)%ind_t + 1
      END IF
    END IF
  END DO
END SUBROUTINE CALC_INNOVQ_DIFF

