!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Apr 2025 13:39
!
!  Differentiation of calc_innovuv in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: *(*innovuv.diff)
!   with respect to varying inputs: *(*innovuv.diff) *(dof.u) *(dof.v)
!   Plus diff mem management of: innovuv:in *innovuv.diff:in dof.u:in
!                dof.v:in
SUBROUTINE CALC_INNOVUV_DIFF(dof, dof_diff, mesh)
  USE M_COMMON ! Replaced by Perl Script
  USE M_MPI ! Replaced by Perl Script
  USE M_MODEL ! Replaced by Perl Script
  USE M_OBS ! Replaced by Perl Script
  USE M_OBS_DIFF

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  TYPE(UNK), INTENT(IN) :: dof
  TYPE(UNK), INTENT(IN) :: dof_diff ! Replaced by Perl Script
  TYPE(MSH), INTENT(IN) :: mesh
  INTEGER(ip) :: cell, searched_time, pt, n_average
  REAL(rp) :: h_mean, s_total, u_mean, v_mean
  REAL(rp) :: u_mean_diff, v_mean_diff
  CHARACTER(len=50) :: filename
  INTRINSIC SIZE
  REAL(rp) :: temp
  DO iobs=1,SIZE(station)
    searched_time = innovuv(iobs)%ind_t
    IF (searched_time .LE. innovuv(iobs)%nb_dt) THEN
      IF (tc .GE. station(iobs)%t(searched_time)) THEN
        u_mean = 0._rp
        v_mean = 0._rp
        s_total = 0._rp
        v_mean_diff = 0.0_8
        u_mean_diff = 0.0_8
        DO pt=1,SIZE(station(iobs)%pt)
          cell = station(iobs)%pt(pt)%cell
          IF (cell .GE. 0) THEN
            IF (dof%h(cell) .GT. 0) THEN
!test on water presence determining if cell is used for calculating h_average
              u_mean_diff = u_mean_diff + mesh%cell(cell)%surf*dof_diff%&
&               u(cell)
              u_mean = u_mean + dof%u(cell)*mesh%cell(cell)%surf
              v_mean_diff = v_mean_diff + mesh%cell(cell)%surf*dof_diff%&
&               v(cell)
              v_mean = v_mean + dof%v(cell)*mesh%cell(cell)%surf
              s_total = s_total + mesh%cell(cell)%surf
            END IF
          END IF
        END DO
        CALL MPI_SUM_R(u_mean)
        CALL MPI_SUM_R(v_mean)
        IF (s_total .GT. 0) THEN
          u_mean_diff = u_mean_diff/s_total
          u_mean = u_mean/s_total
          v_mean_diff = v_mean_diff/s_total
          v_mean = v_mean/s_total
        END IF
        temp = u_mean**2_rp + v_mean**2_rp
        innovuv_diff(iobs)%diff(searched_time) = 0.5_rp*temp**(-0.5)*(&
&         2_rp*u_mean*u_mean_diff+2_rp*v_mean*v_mean_diff)
        innovuv(iobs)%diff(searched_time) = temp**0.5_rp - (station(iobs&
&         )%u(searched_time)**2_rp+station(iobs)%v(searched_time)**2_rp)&
&         **0.5_rp
        innovuv(iobs)%ind_t = innovuv(iobs)%ind_t + 1
      END IF
    END IF
  END DO
END SUBROUTINE CALC_INNOVUV_DIFF

