!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Apr 2025 13:39
!
!  Differentiation of calc_innovation in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: *bathy_cell *(*innovation.diff)
!                *(dof.h)
!   with respect to varying inputs: *bathy_cell *(*innovation.diff)
!                *(dof.h)
!   Plus diff mem management of: bathy_cell:in innovation:in *innovation.diff:in
!                dof.h:in
SUBROUTINE CALC_INNOVATION_BACK(dof, dof_back, mesh)
  USE M_COMMON ! Replaced by Perl Script
  USE M_MPI ! Replaced by Perl Script
  USE M_MODEL ! Replaced by Perl Script
  USE M_OBS ! Replaced by Perl Script
  USE M_OBS_BACK

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  TYPE(UNK), INTENT(IN) :: dof
  TYPE(UNK) :: dof_back ! Replaced by Perl Script
  TYPE(MSH), INTENT(IN) :: mesh
  INTEGER(ip) :: cell, searched_time, pt, n_average
  REAL(rp) :: h_mean, s_total, u_mean, v_mean
  REAL(rp) :: h_mean_back
  INTRINSIC SIZE
  REAL(rp) :: temp_back
  INTEGER*4 :: ad_to
  INTEGER*4 :: branch
  INTEGER*4 :: ad_to0
  IF (use_obs .EQ. 1) THEN
    DO iobs=1,SIZE(station)
      CALL PUSHINTEGER4(searched_time)
      searched_time = innovation(iobs)%ind_t
      IF (searched_time .GT. innovation(iobs)%nb_dt) THEN
        CALL PUSHCONTROL2B(0)
      ELSE IF (tc .GE. station(iobs)%t(searched_time)) THEN
        CALL PUSHREAL8(s_total)
        s_total = 0._rp
        DO pt=1,SIZE(station(iobs)%pt)
          cell = station(iobs)%pt(pt)%cell
          IF (cell .LT. 0) THEN
            CALL PUSHCONTROL3B(0)
          ELSE IF (use_hobs .EQ. 1) THEN
            s_total = s_total + mesh%cell(cell)%surf
            CALL PUSHCONTROL3B(4)
          ELSE IF (use_zobs .EQ. 1) THEN
            IF (dof%h(cell) .GT. 0) THEN
!test on water presence determining if cell is used for calculating h_average
              s_total = s_total + mesh%cell(cell)%surf
              CALL PUSHCONTROL3B(3)
            ELSE
              CALL PUSHCONTROL3B(2)
            END IF
          ELSE
            CALL PUSHCONTROL3B(1)
          END IF
        END DO
        CALL PUSHINTEGER4(pt - 1)
        CALL MPI_SUM_R(h_mean)
        CALL MPI_SUM_R(s_total)
        CALL MPI_SUM_I(n_average)
        IF (s_total .GT. 0) THEN
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHCONTROL1B(1)
        END IF
        innovation(iobs)%ind_t = innovation(iobs)%ind_t + 1
        CALL PUSHCONTROL2B(2)
      ELSE
        CALL PUSHCONTROL2B(1)
      END IF
    END DO
    ad_to0 = iobs - 1
    DO iobs=ad_to0,1,-1
      CALL POPCONTROL2B(branch)
      IF (branch .NE. 0) THEN
        IF (branch .NE. 1) THEN
          h_mean_back = innovation_back(iobs)%diff(searched_time)
          innovation_back(iobs)%diff(searched_time) = 0.0_8
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) h_mean_back = h_mean_back/s_total
          CALL POPINTEGER4(ad_to)
          DO pt=ad_to,1,-1
            CALL POPCONTROL3B(branch)
            IF (branch .GE. 2) THEN
              IF (branch .NE. 2) THEN
                IF (branch .EQ. 3) THEN
                  cell = station(iobs)%pt(pt)%cell
                  temp_back = mesh%cell(cell)%surf*h_mean_back
                  dof_back%h(cell) = dof_back%h(cell) + temp_back
                  bathy_cell_back(cell) = bathy_cell_back(cell) + &
&                   temp_back
                ELSE
                  cell = station(iobs)%pt(pt)%cell
                  dof_back%h(cell) = dof_back%h(cell) + mesh%cell(cell)%&
&                   surf*h_mean_back
                END IF
              END IF
            END IF
          END DO
          CALL POPREAL8(s_total)
        END IF
      END IF
      CALL POPINTEGER4(searched_time)
    END DO
  END IF
END SUBROUTINE CALC_INNOVATION_BACK

