!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 25 Jun 2025 16:38
!
!  Differentiation of euler_time_step_first_b1 in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: *(bc.rain).cumul *(bc.sum_mass_flux)
!                *bathy_cell *(sporosity.phi) *(dof.h) *(dof.u)
!                *(dof.v) *(dof.infil)
!   with respect to varying inputs: *(infil.ga).psif *(infil.ga).ks
!                *(infil.ga).deltatheta *(infil.scs).lambdacn *(infil.scs).cn
!                *manning *(bc.inflow) *(bc.outflow) *(bc.rain).qin
!                *(bc.rain).cumul *(bc.sum_mass_flux) *bathy_cell
!                *manning_beta *(sporosity.phi) *(dof.h) *(dof.u)
!                *(dof.v) *(dof.infil)
!   Plus diff mem management of: infil.ga:in infil.scs:in manning:in
!                bc.inflow:in bc.outflow:in bc.hpresc:in *(bc.hpresc).t:in
!                *(bc.hpresc).h:in bc.zspresc:in *(bc.zspresc).t:in
!                *(bc.zspresc).z:in bc.rain:in bc.sum_mass_flux:in
!                bathy_cell:in manning_beta:in sporosity.phi:in
!                dof.h:in dof.u:in dof.v:in dof.infil:in
SUBROUTINE EULER_TIME_STEP_FIRST_B1_DIFF(dof, dof_diff, mesh, poro_unit&
& , it)
  USE M_COMMON ! Replaced by Perl Script
  USE M_MESH ! Replaced by Perl Script
  USE M_MPI ! Replaced by Perl Script
  USE M_MODEL ! Replaced by Perl Script

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  TYPE(MSH), INTENT(INOUT) :: mesh
  TYPE(UNK), INTENT(INOUT) :: dof
  TYPE(UNK), INTENT(INOUT) :: dof_diff ! Replaced by Perl Script
  INTEGER, INTENT(IN) :: poro_unit
  INTEGER, INTENT(IN) :: it
  INTEGER, PARAMETER :: write_frequency=1000
! Left and Right cells indexes to edge
  INTEGER(ip) :: il, ir
! Left State in edge cell normal coordinates
  REAL(rp) :: hl(2), ul(2), vl(2), zl
  REAL(rp) :: hl_diff(2), ul_diff(2), vl_diff(2), zl_diff
! Right State in edge cell normal coordinates
  REAL(rp) :: hr(2), ur(2), vr(2), zr
  REAL(rp) :: hr_diff(2), ur_diff(2), vr_diff(2), zr_diff
! Finite Volume normal edge flux
  REAL(rp), DIMENSION(sw_nb) :: nflux
  REAL(rp), DIMENSION(sw_nb) :: nflux_diff
! Finite Volume edge flux in (x,y) coordinates
  REAL(rp), DIMENSION(sw_nb) :: lflux
  REAL(rp), DIMENSION(sw_nb) :: lflux_diff
! Finite Volume total flux for each cell
  REAL(rp), DIMENSION(sw_nb, mesh%nc) :: tflux
  REAL(rp), DIMENSION(sw_nb, mesh%nc) :: tflux_diff
! Temporal primitive variables
  REAL(rp) :: h, u, v
  REAL(rp) :: h_diff, u_diff, v_diff
! potential maximal retention
  REAL(rp) :: s
  REAL(rp) :: s_diff
! Temporal Fn+1
  REAL(rp) :: fn1
  REAL(rp) :: fn1_diff
  REAL(rp) :: afn1, bfn1
  REAL(rp) :: afn1_diff, bfn1_diff
!local variable of infil calculated depth
  REAL(rp) :: h_infil
  REAL(rp) :: h_infil_diff
! Velocity norm
  REAL(rp) :: vel
  REAL(rp) :: vel_diff
! Manning
  REAL(rp) :: sfl
  REAL(rp) :: sfl_diff
! mass rain >TGADJ
  REAL(rp) :: madd
! Left/Right porosity in cell
  REAL(rp) :: phil, phir
  REAL(rp) :: phil_diff, phir_diff
! Left/Right term source
  REAL(rp) :: s2l, s2r
  REAL(rp) :: s2l_diff, s2r_diff
  INTRINSIC MOD
  INTRINSIC MAX
  INTRINSIC ABS
  INTRINSIC SQRT
  REAL(rp) :: y1
  REAL(rp) :: y1_diff
  REAL(rp) :: y2
  REAL(rp) :: y2_diff
  REAL(rp) :: abs0
  REAL(rp) :: abs0_diff
  REAL(rp) :: abs1
  REAL(rp) :: abs2
  REAL(rp) :: abs2_diff
  REAL(rp) :: max1
  REAL(rp) :: max1_diff
  REAL(rp) :: max2
  REAL(rp) :: max2_diff
  REAL(rp) :: abs3
  REAL(rp) :: abs3_diff
  REAL(rp) :: abs4
  REAL(rp) :: abs4_diff
  REAL(rp) :: arg1
  REAL(rp) :: arg1_diff
  REAL(rp) :: result1
  REAL(rp) :: result1_diff
  REAL(rp) :: temp
  REAL(rp) :: temp0
  REAL(rp) :: temp1
  REAL(rp) :: temp2
  REAL(rp) :: temp3
  REAL(rp) :: temp_diff
  REAL(rp) :: temp_diff0
  tflux(:, :) = 0._rp
  CALL UPDATE_ALL_POROSITIES_DIFF(dof, dof_diff, mesh)
  IF (MOD(it, write_frequency) .EQ. 0 .OR. it .EQ. 1) THEN
    WRITE(poro_unit, *) it, sporosity%phi(:)
    nflux_diff = 0.0_8
    hl_diff = 0.0_8
    ul_diff = 0.0_8
    hr_diff = 0.0_8
    ur_diff = 0.0_8
    tflux_diff = 0.0_8
    vl_diff = 0.0_8
    vr_diff = 0.0_8
    s2l_diff = 0.0_8
    s2r_diff = 0.0_8
    lflux_diff = 0.0_8
    zr_diff = 0.0_8
  ELSE
    nflux_diff = 0.0_8
    hl_diff = 0.0_8
    ul_diff = 0.0_8
    hr_diff = 0.0_8
    ur_diff = 0.0_8
    tflux_diff = 0.0_8
    vl_diff = 0.0_8
    vr_diff = 0.0_8
    s2l_diff = 0.0_8
    s2r_diff = 0.0_8
    lflux_diff = 0.0_8
    zr_diff = 0.0_8
  END IF
  DO 100 ie=1,mesh%ne
    il = mesh%edge(ie)%cell(1)
!Left cell id for a normal cell
    ir = mesh%edge(ie)%cell(2)
    IF (mesh%edge(ie)%boundary) THEN
!Check if bounfary first so typlim exists
      IF (mesh%edgeb(mesh%edge(ie)%lim)%typlim .EQ. 'internal_1D') THEN
        GOTO 100
      ELSE IF (mesh%edgeb(mesh%edge(ie)%lim)%typlim .EQ. 'internal_2D') &
&     THEN
!then change connectivity to connected 1D-like cell
!Get id of the single 1D-like cell with interface in the connected bc number => this should be done once!
        ir = mesh%edge(ie)%cell1d2d
      END IF
    END IF
    hl_diff(1) = dof_diff%h(il)
    hl(1) = dof%h(il)
    hr_diff(1) = dof_diff%h(ir)
    hr(1) = dof%h(ir)
    IF (hl(1) .GT. heps .OR. hr(1) .GT. heps) THEN
      ul_diff(1) = dof_diff%u(il)
      ul(1) = dof%u(il)
      vl_diff(1) = dof_diff%v(il)
      vl(1) = dof%v(il)
      ul_diff(2) = mesh%edge(ie)%normal%x*ul_diff(1) + mesh%edge(ie)%&
&       normal%y*vl_diff(1)
      ul(2) = mesh%edge(ie)%normal%x*ul(1) + mesh%edge(ie)%normal%y*vl(1&
&       )
      vl_diff(2) = mesh%edge(ie)%normal%x*vl_diff(1) - mesh%edge(ie)%&
&       normal%y*ul_diff(1)
      vl(2) = mesh%edge(ie)%normal%x*vl(1) - mesh%edge(ie)%normal%y*ul(1&
&       )
      IF (mesh%edge(ie)%boundary) THEN
        zl_diff = bathy_cell_diff(il)
        zl = bathy_cell(il)
        IF (mesh%edgeb(mesh%edge(ie)%lim)%typlim .EQ. 'zspresc') THEN
!&
          zr_diff = bathy_cell_diff(il)
          zr = bathy_cell(il)
        ELSE IF (mesh%edgeb(mesh%edge(ie)%lim)%typlim .EQ. 'discharg1') &
&       THEN
          zr_diff = bathy_cell_diff(il)
          zr = bathy_cell(il) + slope_y(1)*mesh%cell(mesh%edge(il)%cell(&
&           1))%surf/mesh%edge(il)%length + slope_x(1)*mesh%cell(mesh%&
&           edge(il)%cell(1))%surf/mesh%edge(il)%length
        ELSE IF (mesh%edgeb(mesh%edge(ie)%lim)%typlim .EQ. 'wall') THEN
          zr_diff = bathy_cell_diff(il)
          zr = bathy_cell(il)
        END IF
        IF (.NOT.mesh%edgeb(mesh%edge(ie)%lim)%typlim .EQ. 'internal_2D'&
&       ) THEN
!do not call boundary calculations for internal BCs
          CALL CALC_BOUNDARY_STATE_DIFF(mesh, hl(1), hl_diff(1), zl, &
&                                 zl_diff, ul(2), ul_diff(2), vl(2), &
&                                 vl_diff(2), hr(1), hr_diff(1), zr, &
&                                 zr_diff, ur(2), ur_diff(2), vr(2), &
&                                 vr_diff(2))
        ELSE
          ur_diff(1) = dof_diff%u(ir)
          ur(1) = dof%u(ir)
          vr_diff(1) = dof_diff%v(ir)
          vr(1) = dof%v(ir)
          ur_diff(2) = mesh%edge(ie)%normal%x*ur_diff(1) + mesh%edge(ie)&
&           %normal%y*vr_diff(1)
          ur(2) = mesh%edge(ie)%normal%x*ur(1) + mesh%edge(ie)%normal%y*&
&           vr(1)
          vr_diff(2) = mesh%edge(ie)%normal%x*vr_diff(1) - mesh%edge(ie)&
&           %normal%y*ur_diff(1)
          vr(2) = mesh%edge(ie)%normal%x*vr(1) - mesh%edge(ie)%normal%y*&
&           ur(1)
        END IF
        phil_diff = sporosity_diff%phi(sporosity%land(il))
        phil = sporosity%phi(sporosity%land(il))
        phir_diff = phil_diff
        phir = phil
      ELSE
        zl_diff = bathy_cell_diff(il)
        zl = bathy_cell(il)
        zr_diff = bathy_cell_diff(ir)
        zr = bathy_cell(ir)
        ur_diff(1) = dof_diff%u(ir)
        ur(1) = dof%u(ir)
        vr_diff(1) = dof_diff%v(ir)
        vr(1) = dof%v(ir)
        ur_diff(2) = mesh%edge(ie)%normal%x*ur_diff(1) + mesh%edge(ie)%&
&         normal%y*vr_diff(1)
        ur(2) = mesh%edge(ie)%normal%x*ur(1) + mesh%edge(ie)%normal%y*vr&
&         (1)
        vr_diff(2) = mesh%edge(ie)%normal%x*vr_diff(1) - mesh%edge(ie)%&
&         normal%y*ur_diff(1)
        vr(2) = mesh%edge(ie)%normal%x*vr(1) - mesh%edge(ie)%normal%y*ur&
&         (1)
        phil_diff = sporosity_diff%phi(sporosity%land(il))
        phil = sporosity%phi(sporosity%land(il))
        phir_diff = sporosity_diff%phi(sporosity%land(ir))
        phir = sporosity%phi(sporosity%land(ir))
      END IF
      IF (zl .LT. zr) THEN
        max1_diff = zr_diff
        max1 = zr
      ELSE
        max1_diff = zl_diff
        max1 = zl
      END IF
      y1_diff = hl_diff(1) + zl_diff - max1_diff
      y1 = hl(1) + zl - max1
      IF (0._rp .LT. y1) THEN
        hl_diff(2) = y1_diff
        hl(2) = y1
      ELSE
        hl_diff(2) = 0.0_8
        hl(2) = 0._rp
      END IF
      IF (zl .LT. zr) THEN
        max2_diff = zr_diff
        max2 = zr
      ELSE
        max2_diff = zl_diff
        max2 = zl
      END IF
      y2_diff = hr_diff(1) + zr_diff - max2_diff
      y2 = hr(1) + zr - max2
      IF (0._rp .LT. y2) THEN
        hr_diff(2) = y2_diff
        hr(2) = y2
      ELSE
        hr_diff(2) = 0.0_8
        hr(2) = 0._rp
      END IF
      IF (phil .GT. zerom .OR. phir .GT. zerom) THEN
        CALL SW_HLLC_SP_DIFF(hl(1), hl_diff(1), ul(2), ul_diff(2), vl(2)&
&                      , vl_diff(2), zl, zl_diff, phil, phil_diff, s2l, &
&                      s2l_diff, hr(1), hr_diff(1), ur(2), ur_diff(2), &
&                      vr(2), vr_diff(2), zr, zr_diff, phir, phir_diff, &
&                      s2r, s2r_diff, nflux, nflux_diff)
      ELSE
        CALL SW_HLLC_IMPERVIOUS_SP_DIFF(hl(2), hl_diff(2), ul(2), &
&                                 ul_diff(2), vl(2), zl, phil, phil_diff&
&                                 , s2l, s2l_diff, hr(2), hr_diff(2), ur&
&                                 (2), ur_diff(2), vr(2), zr, phir, &
&                                 phir_diff, s2r, s2r_diff, nflux)
        nflux_diff = 0.0_8
      END IF
      IF (mesh%edge(ie)%boundary) CALL BOUNDARY_POST_DIFF(nflux(1), &
&                                                   nflux_diff(1), ir, &
&                                                   mesh)
      lflux_diff(1) = nflux_diff(1)
      lflux(1) = nflux(1)
      lflux_diff(2) = mesh%edge(ie)%normal%x*nflux_diff(2) - mesh%edge(&
&       ie)%normal%y*nflux_diff(3)
      lflux(2) = mesh%edge(ie)%normal%x*nflux(2) - mesh%edge(ie)%normal%&
&       y*nflux(3)
      lflux_diff(3) = mesh%edge(ie)%normal%y*nflux_diff(2) + mesh%edge(&
&       ie)%normal%x*nflux_diff(3)
      lflux(3) = mesh%edge(ie)%normal%y*nflux(2) + mesh%edge(ie)%normal%&
&       x*nflux(3)
      lflux_diff(1:3) = mesh%edge(ie)%length*lflux_diff(1:3)
      lflux(1:3) = lflux(1:3)*mesh%edge(ie)%length
      tflux_diff(1, il) = tflux_diff(1, il) + lflux_diff(1)
      tflux(1, il) = tflux(1, il) + lflux(1)
      tflux_diff(2, il) = tflux_diff(2, il) + lflux_diff(2) - mesh%edge(&
&       ie)%length*mesh%edge(ie)%normal%x*s2l_diff
      tflux(2, il) = tflux(2, il) + lflux(2) - mesh%edge(ie)%normal%x*&
&       s2l*mesh%edge(ie)%length
      tflux_diff(3, il) = tflux_diff(3, il) + lflux_diff(3) - mesh%edge(&
&       ie)%length*mesh%edge(ie)%normal%y*s2l_diff
      tflux(3, il) = tflux(3, il) + lflux(3) - mesh%edge(ie)%normal%y*&
&       s2l*mesh%edge(ie)%length
      IF (.NOT.mesh%edge(ie)%boundary .AND. (.NOT.mesh%edge(ie)%&
&         subdomain)) THEN
        tflux_diff(1, ir) = tflux_diff(1, ir) - lflux_diff(1)
        tflux(1, ir) = tflux(1, ir) - lflux(1)
        tflux_diff(2, ir) = tflux_diff(2, ir) - lflux_diff(2) - mesh%&
&         edge(ie)%length*mesh%edge(ie)%normal%x*s2r_diff
        tflux(2, ir) = tflux(2, ir) - lflux(2) - mesh%edge(ie)%normal%x*&
&         s2r*mesh%edge(ie)%length
        tflux_diff(3, ir) = tflux_diff(3, ir) - lflux_diff(3) - mesh%&
&         edge(ie)%length*mesh%edge(ie)%normal%y*s2r_diff
        tflux(3, ir) = tflux(3, ir) - lflux(3) - mesh%edge(ie)%normal%y*&
&         s2r*mesh%edge(ie)%length
      END IF
      IF (mesh%edge(ie)%boundary) THEN
        IF (mesh%edgeb(mesh%edge(ie)%lim)%typlim .EQ. 'internal_2D') &
&       THEN
          tflux_diff(1, ir) = tflux_diff(1, ir) - lflux_diff(1)
          tflux(1, ir) = tflux(1, ir) - lflux(1)
          tflux_diff(2, ir) = tflux_diff(2, ir) - lflux_diff(2) - mesh%&
&           edge(ie)%length*mesh%edge(ie)%normal%x*s2r_diff
          tflux(2, ir) = tflux(2, ir) - lflux(2) - mesh%edge(ie)%normal%&
&           x*s2r*mesh%edge(ie)%length
          tflux_diff(3, ir) = tflux_diff(3, ir) - lflux_diff(3) - mesh%&
&           edge(ie)%length*mesh%edge(ie)%normal%y*s2r_diff
          tflux(3, ir) = tflux(3, ir) - lflux(3) - mesh%edge(ie)%normal%&
&           y*s2r*mesh%edge(ie)%length
        END IF
      END IF
    END IF
 100 CONTINUE
  DO k=1,bc%nb_rn
    bc_diff%rain(k)%cumul = bc_diff%rain(k)%cumul + dt*bc_diff%rain(k)%&
&     qin
    bc%rain(k)%cumul = bc%rain(k)%cumul + dt*bc%rain(k)%qin
  END DO
  DO i=1,mesh%nc
    h_diff = dof_diff%h(i)
    h = dof%h(i)
    u_diff = dof_diff%u(i)
    u = dof%u(i)
    v_diff = dof_diff%v(i)
    v = dof%v(i)
    IF (0._rp .LT. h - dt/sporosity%phi(sporosity%land(i))*tflux(1, i)*&
&       mesh%cell(i)%invsurf) THEN
      temp = dt*mesh%cell(i)%invsurf
      temp0 = tflux(1, i)/sporosity%phi(sporosity%land(i))
      dof_diff%h(i) = h_diff - temp*(tflux_diff(1, i)-temp0*&
&       sporosity_diff%phi(sporosity%land(i)))/sporosity%phi(sporosity%&
&       land(i))
      dof%h(i) = h - temp*temp0
    ELSE
      dof_diff%h(i) = 0.0_8
      dof%h(i) = 0._rp
    END IF
    IF (bc_rain .EQ. 1) THEN
! If rain is accounted for
!Get rain group for current cell
      k = bc%rain_land(i)
      IF (k .GT. 0) THEN
!If the cell does have a rain value attributed
        IF (bc_infil .EQ. 2) THEN
          IF (infil%scs(infil%land(i))%cn .GE. 0.) THEN
            abs0_diff = infil_diff%scs(infil%land(i))%cn
            abs0 = infil%scs(infil%land(i))%cn
          ELSE
            abs0_diff = -infil_diff%scs(infil%land(i))%cn
            abs0 = -infil%scs(infil%land(i))%cn
          END IF
! If SCS-type infiltration is selected and this cell does have an infiltration value attributed
          s_diff = -(25.4_rp*abs0_diff/abs0**2)
          s = 25.4_rp*(1000._rp/abs0-10._rp)/1000._rp
          IF (infil%scs(infil%land(i))%lambdacn .GE. 0.) THEN
            abs1 = infil%scs(infil%land(i))%lambdacn
          ELSE
            abs1 = -infil%scs(infil%land(i))%lambdacn
          END IF
          IF (bc%rain(k)%cumul .GT. abs1*s) THEN
            IF (infil%scs(infil%land(i))%lambdacn .GE. 0.) THEN
              abs2_diff = infil_diff%scs(infil%land(i))%lambdacn
              abs2 = infil%scs(infil%land(i))%lambdacn
            ELSE
              abs2_diff = -infil_diff%scs(infil%land(i))%lambdacn
              abs2 = -infil%scs(infil%land(i))%lambdacn
            END IF
            IF (infil%scs(infil%land(i))%lambdacn .GE. 0.) THEN
              abs3_diff = infil_diff%scs(infil%land(i))%lambdacn
              abs3 = infil%scs(infil%land(i))%lambdacn
            ELSE
              abs3_diff = -infil_diff%scs(infil%land(i))%lambdacn
              abs3 = -infil%scs(infil%land(i))%lambdacn
            END IF
            IF (infil%scs(infil%land(i))%lambdacn .GE. 0.) THEN
              abs4_diff = infil_diff%scs(infil%land(i))%lambdacn
              abs4 = infil%scs(infil%land(i))%lambdacn
            ELSE
              abs4_diff = -infil_diff%scs(infil%land(i))%lambdacn
              abs4 = -infil%scs(infil%land(i))%lambdacn
            END IF
            temp0 = bc%rain(k)%cumul + (-abs4+1)*s
            temp = bc%rain(k)%cumul - abs3*s
            temp1 = s*temp/temp0
            fn1_diff = abs2*s_diff + s*abs2_diff + (temp*s_diff+s*(&
&             bc_diff%rain(k)%cumul-s*abs3_diff-abs3*s_diff)-temp1*(&
&             bc_diff%rain(k)%cumul-s*abs4_diff+(1-abs4)*s_diff))/temp0
            fn1 = s*abs2 + temp1
          ELSE
            fn1_diff = dof_diff%infil(i) + dt*bc_diff%rain(k)%qin
            fn1 = dof%infil(i) + dt*bc%rain(k)%qin
          END IF
! Output SCS-modified rain
          dof_diff%h(i) = dof_diff%h(i) + dt*bc_diff%rain(k)%qin + &
&           dof_diff%infil(i) - fn1_diff
          dof%h(i) = dof%h(i) + dt*bc%rain(k)%qin - fn1 + dof%infil(i)
          dof_diff%infil(i) = fn1_diff
          dof%infil(i) = fn1
        ELSE
! Raw rain data injected
          dof_diff%h(i) = dof_diff%h(i) + dt*bc_diff%rain(k)%qin
          dof%h(i) = dof%h(i) + dt*bc%rain(k)%qin
        END IF
      END IF
    END IF
    IF (bc_infil .EQ. 1) THEN
!If Green-Ampt infiltration is selected
      IF (infil%land(i) .NE. 0) THEN
!If the current cell does have an infiltration value attributed
        IF (dof%infil(i) .LT. infil%h_infil_max(infil%land(i))) THEN
! If current infiltrated depth is lower than the max soil depth, then apply computed infiltration (else do not infiltrate)
          afn1_diff = dof_diff%infil(i) + dt*((1._rp-infil%ga(infil%land&
&           (i))%deltatheta)*infil_diff%ga(infil%land(i))%ks-infil%ga(&
&           infil%land(i))%ks*infil_diff%ga(infil%land(i))%deltatheta)
          afn1 = dof%infil(i) + dt*infil%ga(infil%land(i))%ks*(1._rp-&
&           infil%ga(infil%land(i))%deltatheta)
          temp1 = dof%infil(i) + dof%h(i) + infil%ga(infil%land(i))%psif
          temp0 = infil%ga(infil%land(i))%ks*infil%ga(infil%land(i))%&
&           deltatheta
          bfn1_diff = dt*(temp1*(infil%ga(infil%land(i))%deltatheta*&
&           infil_diff%ga(infil%land(i))%ks+infil%ga(infil%land(i))%ks*&
&           infil_diff%ga(infil%land(i))%deltatheta)+temp0*(dof_diff%&
&           infil(i)+dof_diff%h(i)+infil_diff%ga(infil%land(i))%psif))
          bfn1 = dt*(temp0*temp1)
! Infiltrated depth over current time step (F^(n+1))
          arg1_diff = 2._rp*afn1*afn1_diff + 4._rp*bfn1_diff
          arg1 = afn1**2._rp + 4._rp*bfn1
          temp1 = SQRT(arg1)
          IF (arg1 .EQ. 0.0) THEN
            result1_diff = 0.0_8
          ELSE
            result1_diff = arg1_diff/(2.0*temp1)
          END IF
          result1 = temp1
          fn1_diff = (afn1_diff+result1_diff)/2._rp
          fn1 = (afn1+result1)/2._rp
          h_infil_diff = dof_diff%h(i) + dof_diff%infil(i) - fn1_diff
          h_infil = dof%h(i) + dof%infil(i) - fn1
          IF (h_infil .LT. 0._rp) THEN
! If more than the available water depth should be infiltrated, infiltrate only the total depth (h^n + r * Dt)
            fn1_diff = dof_diff%h(i) + dof_diff%infil(i)
            fn1 = dof%h(i) + dof%infil(i)
            h_infil = 0._rp
            h_infil_diff = 0.0_8
          END IF
! Pass h^(n+1) to dof%h (h^n)
          dof_diff%h(i) = h_infil_diff
          dof%h(i) = h_infil
! Pass F^(n+1) to dof%infil (F^n)
          dof_diff%infil(i) = fn1_diff
          dof%infil(i) = fn1
        END IF
      END IF
    END IF
    IF (dof%h(i) .LE. heps) THEN
      dof_diff%u(i) = 0.0_8
      dof%u(i) = 0._rp
      dof_diff%v(i) = 0.0_8
      dof%v(i) = 0._rp
    ELSE
      temp1 = dt*mesh%cell(i)%invsurf
      temp0 = tflux(2, i)/sporosity%phi(sporosity%land(i))
      temp = (h*u-temp1*temp0)/dof%h(i)
      dof_diff%u(i) = (u*h_diff+h*u_diff-temp1*(tflux_diff(2, i)-temp0*&
&       sporosity_diff%phi(sporosity%land(i)))/sporosity%phi(sporosity%&
&       land(i))-temp*dof_diff%h(i))/dof%h(i)
      dof%u(i) = temp
      temp1 = dt*mesh%cell(i)%invsurf
      temp0 = tflux(3, i)/sporosity%phi(sporosity%land(i))
      temp = (h*v-temp1*temp0)/dof%h(i)
      dof_diff%v(i) = (v*h_diff+h*v_diff-temp1*(tflux_diff(3, i)-temp0*&
&       sporosity_diff%phi(sporosity%land(i)))/sporosity%phi(sporosity%&
&       land(i))-temp*dof_diff%h(i))/dof%h(i)
      dof%v(i) = temp
      IF (friction .EQ. 1) THEN
        arg1_diff = 2*dof%u(i)*dof_diff%u(i) + 2*dof%v(i)*dof_diff%v(i)
        arg1 = dof%u(i)**2 + dof%v(i)**2
        temp1 = SQRT(arg1)
        IF (arg1 .EQ. 0.0) THEN
          vel_diff = 0.0_8
        ELSE
          vel_diff = arg1_diff/(2.0*temp1)
        END IF
        vel = temp1
        temp1 = 4._rp*dt*g
        temp0 = manning_beta(land(i))
        temp = dof%h(i)
        temp2 = temp**temp0
        temp3 = manning(land(i))*manning(land(i))
        IF (temp .LE. 0.0 .AND. (temp0 .EQ. 0.0 .OR. temp0 .NE. INT(&
&           temp0))) THEN
          temp_diff = 0.0_8
        ELSE IF (temp .LE. 0.0) THEN
          temp_diff = temp0*temp**(temp0-1)*dof_diff%h(i)
        ELSE
          temp_diff = temp0*temp**(temp0-1)*dof_diff%h(i) + temp2*LOG(&
&           temp)*manning_beta_diff(land(i))
        END IF
        IF (dof%h(i) .LE. 0.0 .AND. (d4p3 .EQ. 0.0 .OR. d4p3 .NE. INT(&
&           d4p3))) THEN
          arg1_diff = temp1*(temp2**2*(vel*2*manning(land(i))*&
&           manning_diff(land(i))+temp3*vel_diff)+temp3*vel*2*temp2*&
&           temp_diff)
        ELSE
          arg1_diff = d4p3*dof%h(i)**(d4p3-1)*dof_diff%h(i) + temp1*(&
&           temp2**2*(vel*2*manning(land(i))*manning_diff(land(i))+temp3&
&           *vel_diff)+temp3*vel*2*temp2*temp_diff)
        END IF
        arg1 = dof%h(i)**d4p3 + temp1*(temp3*vel*(temp2*temp2))
        temp3 = SQRT(arg1)
        IF (arg1 .EQ. 0.0) THEN
          result1_diff = 0.0_8
        ELSE
          result1_diff = arg1_diff/(2.0*temp3)
        END IF
        result1 = temp3
        IF (dof%h(i) .LE. 0.0 .AND. (d2p3 .EQ. 0.0 .OR. d2p3 .NE. INT(&
&           d2p3))) THEN
          sfl_diff = result1_diff
        ELSE
          sfl_diff = d2p3*dof%h(i)**(d2p3-1)*dof_diff%h(i) + &
&           result1_diff
        END IF
        sfl = dof%h(i)**d2p3 + result1
        temp2 = dof%h(i)**d2p3/sfl
        IF (dof%h(i) .LE. 0.0 .AND. (d2p3 .EQ. 0.0 .OR. d2p3 .NE. INT(&
&           d2p3))) THEN
          temp_diff0 = 0.0_8
        ELSE
          temp_diff0 = d2p3*dof%h(i)**(d2p3-1)*dof_diff%h(i)
        END IF
        sfl_diff = 2._rp*(temp_diff0-temp2*sfl_diff)/sfl
        sfl = 2._rp*temp2
      ELSE IF (friction .EQ. 2) THEN
        sfl_diff = -(dt*manning_diff(land(i)))
        sfl = one - dt*manning(land(i))
      ELSE
        sfl = 1._rp
        sfl_diff = 0.0_8
      END IF
      dof_diff%u(i) = sfl*dof_diff%u(i) + dof%u(i)*sfl_diff
      dof%u(i) = dof%u(i)*sfl
      dof_diff%v(i) = sfl*dof_diff%v(i) + dof%v(i)*sfl_diff
      dof%v(i) = dof%v(i)*sfl
    END IF
  END DO
  CALL COM_DOF(dof, mesh)
! Required MPI Communication due to inverse variable dependency
  CALL COM_VAR_R(bathy_cell, mesh)

CONTAINS
!  Differentiation of update_all_porosities in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: *(sporosity.phi)[from module m_model]
!   with respect to varying inputs: *bathy_cell[from module m_model]
!                *(sporosity.phi)[from module m_model] *(dof.h)
!   Plus diff mem management of: bathy_cell[from module m_model]:in
!                sporosity.phi[from module m_model]:in dof.h:in
  SUBROUTINE UPDATE_ALL_POROSITIES_DIFF(dof, dof_diff, mesh)

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    TYPE(UNK), INTENT(IN) :: dof
    TYPE(UNK), INTENT(IN) :: dof_diff ! Replaced by Perl Script
    TYPE(MSH), INTENT(IN) :: mesh
    INTEGER :: icell
    REAL(rp) :: h_k, wetted_area, phi_k_new, macro_area
    REAL(rp) :: h_k_diff, wetted_area_diff, phi_k_new_diff, &
&   macro_area_diff
    REAL(rp) :: w
    DO icell=1,mesh%nc
      w = CALCULATE_WIDTH(icell, mesh)
      h_k_diff = dof_diff%h(icell) + bathy_cell_diff(icell)
      h_k = dof%h(icell) + bathy_cell(icell)
      wetted_area_diff = CALCULATE_WETTED_AREA_DIFF(icell, h_k, h_k_diff&
&       , wetted_area)
      macro_area_diff = w*dof_diff%h(icell)
      macro_area = w*dof%h(icell)
      IF (macro_area .GT. 1.0e-9_rp) THEN
        phi_k_new_diff = (wetted_area_diff-wetted_area*macro_area_diff/&
&         macro_area)/macro_area
        phi_k_new = wetted_area/macro_area
      ELSE
        phi_k_new = 1.0_rp
        phi_k_new_diff = 0.0_8
      END IF
      sporosity_diff%phi(icell) = phi_k_new_diff
      sporosity%phi(icell) = phi_k_new
    END DO
  END SUBROUTINE UPDATE_ALL_POROSITIES_DIFF

  SUBROUTINE UPDATE_ALL_POROSITIES(dof, mesh)

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    TYPE(UNK), INTENT(IN) :: dof
    TYPE(MSH), INTENT(IN) :: mesh
    INTEGER :: icell
    REAL(rp) :: h_k, wetted_area, phi_k_new, macro_area
    REAL(rp) :: w
    DO icell=1,mesh%nc
      w = CALCULATE_WIDTH(icell, mesh)
      h_k = dof%h(icell) + bathy_cell(icell)
      wetted_area = CALCULATE_WETTED_AREA(icell, h_k)
      macro_area = w*dof%h(icell)
      IF (macro_area .GT. 1.0e-9_rp) THEN
        phi_k_new = wetted_area/macro_area
      ELSE
        phi_k_new = 1.0_rp
      END IF
      sporosity%phi(icell) = phi_k_new
    END DO
  END SUBROUTINE UPDATE_ALL_POROSITIES

  FUNCTION CALCULATE_WIDTH(icell, mesh) RESULT (w)

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    INTEGER, INTENT(IN) :: icell
    TYPE(MSH), INTENT(IN) :: mesh
    REAL(rp) :: w
    INTEGER :: k_loop, ie_local, count_found
    REAL(rp) :: length1, length2
    count_found = 0
    length1 = 0.0_rp
    length2 = 0.0_rp
    DO k_loop=1,mesh%cell(icell)%nbed
      ie_local = mesh%cell(icell)%edge(k_loop)
      IF (.NOT.mesh%edge(ie_local)%boundary) THEN
        count_found = count_found + 1
        IF (count_found .EQ. 1) THEN
          length1 = mesh%edge(ie_local)%length
        ELSE IF (count_found .EQ. 2) THEN
          length2 = mesh%edge(ie_local)%length
          GOTO 100
        END IF
      END IF
    END DO
 100 w = (length1+length2)/2.0_rp
  END FUNCTION CALCULATE_WIDTH

!  Differentiation of calculate_yn in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: yn
!   with respect to varying inputs: h_k c
  REAL(rp) FUNCTION CALCULATE_YN_DIFF(h_k, h_k_diff, a, beta, c, c_diff&
&   , yn) RESULT (yn_diff)

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    REAL(rp), INTENT(IN) :: h_k
    REAL(rp), INTENT(IN) :: h_k_diff
!parabola parameter
    REAL(rp), INTENT(IN) :: a
!parabola parameter
    REAL(rp), INTENT(IN) :: beta
!parabola parameter
    REAL(rp), INTENT(IN) :: c
    REAL(rp), INTENT(IN) :: c_diff
    REAL(rp), INTENT(OUT) :: yn
    REAL(rp) :: temp
    REAL(rp) :: temp0
    IF (h_k - c .LT. 0.0_rp .OR. a .LE. 0.0_rp) THEN
      yn = 0.0_rp
      yn_diff = 0.0_8
      RETURN
    ELSE
      temp = (h_k-c)/a
      temp0 = 1.0/beta
      IF (temp .LE. 0.0 .AND. (temp0 .EQ. 0.0 .OR. temp0 .NE. INT(temp0)&
&         )) THEN
        yn_diff = 0.0_8
      ELSE
        yn_diff = temp0*temp**(temp0-1)*(h_k_diff-c_diff)/a
      END IF
      yn = temp**temp0
    END IF
  END FUNCTION CALCULATE_YN_DIFF

  FUNCTION CALCULATE_YN(h_k, a, beta, c) RESULT (yn)

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    REAL(rp), INTENT(IN) :: h_k
!parabola parameter
    REAL(rp), INTENT(IN) :: a
!parabola parameter
    REAL(rp), INTENT(IN) :: beta
!parabola parameter
    REAL(rp), INTENT(IN) :: c
    REAL(rp) :: yn
    IF (h_k - c .LT. 0.0_rp .OR. a .LE. 0.0_rp) THEN
      yn = 0.0_rp
      RETURN
    ELSE
      yn = ((h_k-c)/a)**(1.0_rp/beta)
    END IF
  END FUNCTION CALCULATE_YN

!  Differentiation of calculate_wetted_area in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: area
!   with respect to varying inputs: *bathy_cell[from module m_model]
!                h_k
!   Plus diff mem management of: bathy_cell[from module m_model]:in
  REAL(rp) FUNCTION CALCULATE_WETTED_AREA_DIFF(icell, h_k, h_k_diff, &
&   area) RESULT (area_diff)

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    INTEGER, INTENT(IN) :: icell
    REAL(rp), INTENT(IN) :: h_k
    REAL(rp), INTENT(IN) :: h_k_diff
    REAL(rp), INTENT(OUT) :: area
!parabola parameters + half the width occupied by water
    REAL(rp) :: a, c, beta, yn
    REAL(rp) :: c_diff, yn_diff
    INTRINSIC MAX
    REAL(rp) :: temp_diff
    a = sporosity%a(icell)
    beta = sporosity%beta(icell)
    c_diff = bathy_cell_diff(icell)
    c = bathy_cell(icell)
    IF (h_k - c .LT. 0.0_rp .OR. a .LE. 0.0_rp) THEN
      area = 0.0_rp
      area_diff = 0.0_8
      RETURN
    ELSE
      yn_diff = CALCULATE_YN_DIFF(h_k, h_k_diff, a, beta, c, c_diff, yn)
      IF (yn .LE. 0.0 .AND. (beta + 1.0_rp .EQ. 0.0 .OR. beta + 1.0_rp &
&         .NE. INT(beta + 1.0_rp))) THEN
        temp_diff = 0.0_8
      ELSE
        temp_diff = (beta+1.0_rp)*yn**beta*yn_diff
      END IF
      area_diff = yn*(h_k_diff-c_diff) + (h_k-c)*yn_diff - a*temp_diff/(&
&       beta+1.0_rp)
      area = (h_k-c)*yn - a/(beta+1.0_rp)*yn**(beta+1.0_rp)
      area_diff = 2.0_rp*area_diff
      area = 2.0_rp*area
      IF (0.0_rp .LT. area) THEN
        area = area
      ELSE
        area = 0.0_rp
        area_diff = 0.0_8
      END IF
    END IF
  END FUNCTION CALCULATE_WETTED_AREA_DIFF

  FUNCTION CALCULATE_WETTED_AREA(icell, h_k) RESULT (area)

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    INTEGER, INTENT(IN) :: icell
    REAL(rp), INTENT(IN) :: h_k
    REAL(rp) :: area
!parabola parameters + half the width occupied by water
    REAL(rp) :: a, c, beta, yn
    INTRINSIC MAX
    a = sporosity%a(icell)
    beta = sporosity%beta(icell)
    c = bathy_cell(icell)
    IF (h_k - c .LT. 0.0_rp .OR. a .LE. 0.0_rp) THEN
      area = 0.0_rp
      RETURN
    ELSE
      yn = CALCULATE_YN(h_k, a, beta, c)
      area = (h_k-c)*yn - a/(beta+1.0_rp)*yn**(beta+1.0_rp)
      area = 2.0_rp*area
      IF (0.0_rp .LT. area) THEN
        area = area
      ELSE
        area = 0.0_rp
      END IF
    END IF
  END FUNCTION CALCULATE_WETTED_AREA

END SUBROUTINE EULER_TIME_STEP_FIRST_B1_DIFF

