1 run_model: (AD12) User help requested: unknown dimension 1 of array *dof%infil
2 run_model: (AD12) User help requested: unknown dimension 1 of array *dof%v
3 run_model: (AD12) User help requested: unknown dimension 1 of array *dof%u
4 run_model: (AD12) User help requested: unknown dimension 1 of array *dof%h
5 run_model: (AD12) User help requested: unknown dimension 1 of array *innovuv
6 run_model: (AD12) User help requested: unknown dimension 1 of array *innovq
7 run_model: (AD12) User help requested: unknown dimension 1 of array *innovation
8 run_model: (AD12) User help requested: unknown dimension 1 of array *bathy_cell
9 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%sum_mass_flux
10 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
11 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
12 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rat
13 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%outflow
14 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%inflow
15 run_model: (AD12) User help requested: unknown dimension 1 of array *ptf
16 run_model: (AD12) User help requested: unknown dimension 1 of array *ptf
17 run_model: (AD12) User help requested: unknown dimension 1 of array *ptf
18 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
19 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
20 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rat
21 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rat
22 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%hyd
23 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
24 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rat
25 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%outflow
26 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%inflow
27 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%h
28 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%h
29 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%sum_mass_flux
30 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bathy_cell
31 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%sum_mass_flux
32 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
33 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%h
34 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%h
35 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%u
36 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%u
37 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%v
38 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%v
39 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%infil
40 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%infil
41 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bathy_cell
42 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%sum_mass_flux
43 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
44 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%h
45 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%h
46 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%u
47 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%u
48 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%v
49 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%v
50 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%infil
51 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%infil
52 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%sum_mass_flux
53 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *innovation
54 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *innovuv
55 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *innovq
56 set_bc: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:sum_pow_h])
57 set_bc: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:qout])
58 set_bc: (AD07) Data-Flow recovery (TBR) needs to restore allocatable pointer *(bc.inflow), not implemented yet
59 set_bc: (AD12) User help requested: unknown dimension 1 of array *bc%inflow
60 set_bc: (AD07) Data-Flow recovery (TBR) needs to restore allocatable pointer *(bc.outflow), not implemented yet
61 set_bc: (AD12) User help requested: unknown dimension 1 of array *bc%outflow
62 newton_qin: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:zs])
63 newton_qin: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_i in call(none(), ident:mpi_sum_i, expressions[ident:av])
64 newton_qin: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:s1])
65 newton_qin: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:s2])
66 euler_time_step_first_b1: (AD12) User help requested: unknown dimension 1 of array *bathy_cell
67 euler_time_step_first_b1: (AD12) User help requested: unknown dimension 1 of array *bc%sum_mass_flux
68 euler_time_step_first_b1_porosity: (AD12) User help requested: unknown dimension 1 of array *bathy_cell
69 euler_time_step_first_b1_porosity: (AD12) User help requested: unknown dimension 1 of array *bc%sum_mass_flux
70 calc_innovation: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:h_mean])
71 calc_innovation: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:s_total])
72 calc_innovation: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_i in call(none(), ident:mpi_sum_i, expressions[ident:n_average])
73 calc_innovuv: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:u_mean])
74 calc_innovuv: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:v_mean])
75 calc_innovw: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:w_total])
76 calc_cost_function: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[arrayAccess(ident:cost_part, expressions[intCst:2])])
77 calc_cost_function: (AD12) User help requested: unknown dimension 1 of array *bc%hyd
78 calc_cost_function: (AD12) User help requested: unknown dimension 1 of array *bc%hyd
79 update_cost_function: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:h_mean])
80 sw_post_treatment: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[arrayAccess(fieldAccess(ident:bc, ident:sum_mass_flux), expressions[ident:num_bc])])
81 sw_post_treatment: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[arrayAccess(pointerAccess(fieldAccess(ident:bc, ident:sum_mass_flux), none()), expressions[ident:num_bc])])
82 default_values: (TC16) Type mismatch in assignment: INTEGER*4 receives REAL*4
83 alloc_or_realloc_station: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE STATION_OBS(*) POINTER
84 alloc_or_realloc_station: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE STATION_OBS(*) POINTER
85 alloc_or_realloc_stationq: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE STATION_OBSQ(*) POINTER
86 alloc_or_realloc_stationq: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE STATION_OBSQ(*) POINTER
87 end_mpi: (TC32) Conflicting numbers of arguments for procedure exit, expected 1, is here 0
88 reallocate_cell: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPE(*) POINTER
89 reallocate_cell: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPE(*) POINTER
90 reallocate_cell: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPE(*) POINTER
91 reallocate_cell: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPE(*) POINTER
92 reallocate_edge: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPE(*) POINTER
93 reallocate_edge: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPE(*) POINTER
94 reallocate_edge: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPE(*) POINTER
95 reallocate_edge: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPE(*) POINTER
96 reallocate_node: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPE(*) POINTER
97 reallocate_node: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPE(*) POINTER
98 reallocate_node: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPE(*) POINTER
99 reallocate_node: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPE(*) POINTER
100 reallocate_cellb: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPELIM(*) POINTER
101 reallocate_cellb: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPELIM(*) POINTER
102 reallocate_cellb: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPELIM(*) POINTER
103 reallocate_cellb: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPELIM(*) POINTER
104 reallocate_edgeb: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPELIM(*) POINTER
105 reallocate_edgeb: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPELIM(*) POINTER
106 reallocate_edgeb: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPELIM(*) POINTER
107 reallocate_edgeb: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPELIM(*) POINTER
108 reallocate_nodeb: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPELIM(*) POINTER
109 reallocate_nodeb: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPELIM(*) POINTER
110 reallocate_nodeb: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPELIM(*) POINTER
111 reallocate_nodeb: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPELIM(*) POINTER
112 reading_args: (TC33) External procedure command_argument_count is not declared
113 reading_args: (TC33) External procedure get_command_argument is not declared
114 msh_initialise: (TC33) External procedure mesh_input is not declared
115 mpi_sum_r: Tool: (Build MP call info) Unexpected MPI primitive mpi_wait_all in call(none(), ident:mpi_wait_all, expressions[])
