1 run_model: (AD12) User help requested: unknown dimension 1 of array *dof%infil
2 run_model: (AD12) User help requested: unknown dimension 1 of array *dof%v
3 run_model: (AD12) User help requested: unknown dimension 1 of array *dof%u
4 run_model: (AD12) User help requested: unknown dimension 1 of array *dof%h
5 run_model: (AD12) User help requested: unknown dimension 1 of array *innovuv
6 run_model: (AD12) User help requested: unknown dimension 1 of array *innovq
7 run_model: (AD12) User help requested: unknown dimension 1 of array *innovation
8 run_model: (AD12) User help requested: unknown dimension 1 of array *sporosity%phi
9 run_model: (AD12) User help requested: unknown dimension 1 of array *bathy_cell
10 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%sum_mass_flux
11 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
12 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
13 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rat
14 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%outflow
15 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%inflow
16 run_model: (AD12) User help requested: unknown dimension 1 of array *ptf
17 run_model: (AD12) User help requested: unknown dimension 1 of array *ptf
18 run_model: (AD12) User help requested: unknown dimension 1 of array *ptf
19 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
20 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
21 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rat
22 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rat
23 run_model: (AD12) User help requested: unknown dimension 1 of array *bc%hyd
24 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
25 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rat
26 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%outflow
27 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%inflow
28 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%h
29 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%h
30 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%sum_mass_flux
31 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *sporosity%phi
32 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bathy_cell
33 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%sum_mass_flux
34 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%rain
35 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%h
36 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%h
37 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%u
38 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%u
39 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%v
40 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%v
41 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%infil
42 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *dof%infil
43 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *bc%sum_mass_flux
44 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *innovation
45 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *innovuv
46 sub_run_model: (AD12) User help requested: unknown dimension 1 of array *innovq
47 set_bc: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:sum_pow_h])
48 set_bc: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:qout])
49 set_bc: (AD07) Data-Flow recovery (TBR) needs to restore allocatable pointer *(bc.inflow), not implemented yet
50 set_bc: (AD12) User help requested: unknown dimension 1 of array *bc%inflow
51 set_bc: (AD07) Data-Flow recovery (TBR) needs to restore allocatable pointer *(bc.outflow), not implemented yet
52 set_bc: (AD12) User help requested: unknown dimension 1 of array *bc%outflow
53 newton_qin: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:zs])
54 newton_qin: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_i in call(none(), ident:mpi_sum_i, expressions[ident:av])
55 newton_qin: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:s1])
56 newton_qin: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:s2])
57 euler_time_step_first_b1: (AD12) User help requested: unknown dimension 1 of array *bathy_cell
58 euler_time_step_first_b1: (AD12) User help requested: unknown dimension 1 of array *bc%sum_mass_flux
59 calc_innovation: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:h_mean])
60 calc_innovation: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:s_total])
61 calc_innovation: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_i in call(none(), ident:mpi_sum_i, expressions[ident:n_average])
62 calc_innovuv: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:u_mean])
63 calc_innovuv: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:v_mean])
64 calc_innovw: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:w_total])
65 calc_cost_function: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[arrayAccess(ident:cost_part, expressions[intCst:1])])
66 calc_cost_function: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[arrayAccess(ident:cost_part, expressions[intCst:2])])
67 calc_cost_function: (AD12) User help requested: unknown dimension 1 of array *bc%hyd
68 calc_cost_function: (AD12) User help requested: unknown dimension 1 of array *bc%hyd
69 update_cost_function: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[ident:h_mean])
70 sw_post_treatment: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[arrayAccess(fieldAccess(ident:bc, ident:sum_mass_flux), expressions[ident:num_bc])])
71 sw_post_treatment: Tool: (Build MP call info) Unexpected MPI primitive mpi_sum_r in call(none(), ident:mpi_sum_r, expressions[arrayAccess(pointerAccess(fieldAccess(ident:bc, ident:sum_mass_flux), none()), expressions[ident:num_bc])])
72 default_values: (TC16) Type mismatch in assignment: INTEGER*4 receives REAL*4
73 alloc_or_realloc_station: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE STATION_OBS(*) POINTER
74 alloc_or_realloc_station: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE STATION_OBS(*) POINTER
75 alloc_or_realloc_stationq: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE STATION_OBSQ(*) POINTER
76 alloc_or_realloc_stationq: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE STATION_OBSQ(*) POINTER
77 end_mpi: (TC32) Conflicting numbers of arguments for procedure exit, expected 1, is here 0
78 reallocate_cell: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPE(*) POINTER
79 reallocate_cell: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPE(*) POINTER
80 reallocate_cell: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPE(*) POINTER
81 reallocate_cell: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPE(*) POINTER
82 reallocate_edge: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPE(*) POINTER
83 reallocate_edge: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPE(*) POINTER
84 reallocate_edge: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPE(*) POINTER
85 reallocate_edge: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPE(*) POINTER
86 reallocate_node: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPE(*) POINTER
87 reallocate_node: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPE(*) POINTER
88 reallocate_node: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPE(*) POINTER
89 reallocate_node: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPE(*) POINTER
90 reallocate_cellb: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPELIM(*) POINTER
91 reallocate_cellb: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPELIM(*) POINTER
92 reallocate_cellb: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPELIM(*) POINTER
93 reallocate_cellb: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE CELLTYPELIM(*) POINTER
94 reallocate_edgeb: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPELIM(*) POINTER
95 reallocate_edgeb: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPELIM(*) POINTER
96 reallocate_edgeb: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPELIM(*) POINTER
97 reallocate_edgeb: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE EDGETYPELIM(*) POINTER
98 reallocate_nodeb: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPELIM(*) POINTER
99 reallocate_nodeb: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPELIM(*) POINTER
100 reallocate_nodeb: (TC30) Type mismatch in argument 1 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPELIM(*) POINTER
101 reallocate_nodeb: (TC30) Type mismatch in argument 2 of procedure move_alloc, expected REAL*8(*) POINTER, is here derived TYPE NODETYPELIM(*) POINTER
102 reading_args: (TC33) External procedure command_argument_count is not declared
103 reading_args: (TC33) External procedure get_command_argument is not declared
104 msh_initialise: (TC33) External procedure mesh_input is not declared
105 mpi_sum_r: Tool: (Build MP call info) Unexpected MPI primitive mpi_wait_all in call(none(), ident:mpi_wait_all, expressions[])
