!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 25 Jun 2025 16:38
!
MODULE M_NUMERIC_BACK

  USE M_NUMERIC
  USE M_MPI_BACK
  USE M_TAP_VARS

CONTAINS


!  Differentiation of fv_cell_grad in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: grad_var.x grad_var.y var
!   with respect to varying inputs: var *(mesh.cell).invsurf *(mesh.edge).length
!                *(mesh.edge).normal.x *(mesh.edge).normal.y
!   Plus diff mem management of: mesh.cell:in mesh.edge:in
  SUBROUTINE FV_CELL_GRAD_BACK(grad_var, grad_var_back, var, var_back, &
&   mesh, mesh_back)
    IMPLICIT NONE
    TYPE(MSH), INTENT(IN) :: mesh
    TYPE(MSH) :: mesh_back ! Replaced by Perl Script
    REAL(rp), DIMENSION(mesh%nc+mesh%ncb), INTENT(IN) :: var
    REAL(rp), DIMENSION(mesh%nc+mesh%ncb) :: var_back
    TYPE(VEC2D), DIMENSION(mesh%nc+mesh%ncb) :: grad_var
    TYPE(VEC2D), DIMENSION(mesh%nc+mesh%ncb) :: grad_var_back
! Left and Right cells indexes to edge
    INTEGER(ip) :: il, ir
    REAL(rp) :: temp_back
    REAL(rp) :: temp_back0
    INTEGER*4 :: branch
    grad_var(:)%x = 0._rp
    grad_var(:)%y = 0._rp
    DO ie=1,mesh%ne
      CALL PUSHINTEGER4(il)
      il = mesh%edge(ie)%cell(1)
      CALL PUSHINTEGER4(ir)
      ir = mesh%edge(ie)%cell(2)
      grad_var(il)%x = grad_var(il)%x + mesh%edge(ie)%length*mesh%edge(&
&       ie)%normal%x*demi*(var(il)+var(ir))
      grad_var(il)%y = grad_var(il)%y + mesh%edge(ie)%length*mesh%edge(&
&       ie)%normal%y*demi*(var(il)+var(ir))
      IF (.NOT.mesh%edge(ie)%boundary .AND. (.NOT.mesh%edge(ie)%&
&         subdomain)) THEN
        grad_var(ir)%x = grad_var(ir)%x - mesh%edge(ie)%length*mesh%edge&
&         (ie)%normal%x*demi*(var(il)+var(ir))
        grad_var(ir)%y = grad_var(ir)%y - mesh%edge(ie)%length*mesh%edge&
&         (ie)%normal%y*demi*(var(il)+var(ir))
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
    i = mesh%nc + 1
    mesh_back%cell%invsurf = 0.0_8
    DO i=mesh%nc,1,-1
      mesh_back%cell(i)%invsurf = mesh_back%cell(i)%invsurf + grad_var(i&
&       )%y*grad_var_back(i)%y + grad_var(i)%x*grad_var_back(i)%x
      grad_var_back(i)%y = mesh%cell(i)%invsurf*grad_var_back(i)%y
      grad_var_back(i)%x = mesh%cell(i)%invsurf*grad_var_back(i)%x
    END DO
    mesh_back%edge%length = 0.0_8
    mesh_back%edge%normal%x = 0.0_8
    mesh_back%edge%normal%y = 0.0_8
    DO ie=mesh%ne,1,-1
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) THEN
        il = mesh%edge(ie)%cell(1)
        ir = mesh%edge(ie)%cell(2)
        temp_back0 = -((var(il)+var(ir))*demi*grad_var_back(ir)%y)
        temp_back = -(mesh%edge(ie)%length*mesh%edge(ie)%normal%y*demi*&
&         grad_var_back(ir)%y)
        var_back(il) = var_back(il) + temp_back
        var_back(ir) = var_back(ir) + temp_back
        mesh_back%edge(ie)%length = mesh_back%edge(ie)%length + mesh%&
&         edge(ie)%normal%y*temp_back0
        mesh_back%edge(ie)%normal%y = mesh_back%edge(ie)%normal%y + mesh&
&         %edge(ie)%length*temp_back0
        temp_back0 = -((var(il)+var(ir))*demi*grad_var_back(ir)%x)
        temp_back = -(mesh%edge(ie)%length*mesh%edge(ie)%normal%x*demi*&
&         grad_var_back(ir)%x)
        var_back(il) = var_back(il) + temp_back
        var_back(ir) = var_back(ir) + temp_back
        mesh_back%edge(ie)%length = mesh_back%edge(ie)%length + mesh%&
&         edge(ie)%normal%x*temp_back0
        mesh_back%edge(ie)%normal%x = mesh_back%edge(ie)%normal%x + mesh&
&         %edge(ie)%length*temp_back0
      END IF
      temp_back0 = (var(il)+var(ir))*demi*grad_var_back(il)%y
      temp_back = mesh%edge(ie)%length*mesh%edge(ie)%normal%y*demi*&
&       grad_var_back(il)%y
      var_back(il) = var_back(il) + temp_back
      var_back(ir) = var_back(ir) + temp_back
      mesh_back%edge(ie)%normal%y = mesh_back%edge(ie)%normal%y + mesh%&
&       edge(ie)%length*temp_back0
      temp_back = (var(il)+var(ir))*demi*grad_var_back(il)%x
      mesh_back%edge(ie)%length = mesh_back%edge(ie)%length + mesh%edge(&
&       ie)%normal%y*temp_back0 + mesh%edge(ie)%normal%x*temp_back
      temp_back0 = mesh%edge(ie)%length*mesh%edge(ie)%normal%x*demi*&
&       grad_var_back(il)%x
      var_back(il) = var_back(il) + temp_back0
      var_back(ir) = var_back(ir) + temp_back0
      mesh_back%edge(ie)%normal%x = mesh_back%edge(ie)%normal%x + mesh%&
&       edge(ie)%length*temp_back
      CALL POPINTEGER4(ir)
      CALL POPINTEGER4(il)
    END DO
  END SUBROUTINE FV_CELL_GRAD_BACK


END MODULE M_NUMERIC_BACK

