!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 26 Mar 2024 17:10
!
MODULE M_NUMERIC_BACK

  USE M_NUMERIC
  USE M_MPI_BACK
  USE M_TAP_VARS

CONTAINS

!  Differentiation of linear_interp in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: tx ty x linear_interp
!   with respect to varying inputs: tx ty x
  SUBROUTINE LINEAR_INTERP_BACK0(tx, tx_back, ty, ty_back, x, x_back, &
&   linear_interp_back)
    IMPLICIT NONE
    REAL(rp), DIMENSION(:), INTENT(IN) :: tx, ty
    REAL(rp), DIMENSION(:) :: tx_back, ty_back
    REAL(rp), INTENT(IN) :: x
    REAL(rp) :: x_back
    REAL(rp) :: alpha
    REAL(rp) :: alpha_back
    INTEGER(ip) :: ind, imin, imax
    INTRINSIC LBOUND
    INTRINSIC UBOUND
    REAL(rp) :: temp_back
    REAL(rp) :: temp_back0
    REAL(rp) :: linear_interp
    REAL(rp) :: linear_interp_back
    imin = LBOUND(tx(:), dim=1)
    imax = UBOUND(tx(:), dim=1)
    IF (x + zerom .LT. tx(imin)) THEN
      alpha = (x-tx(imin))/(tx(imin+1)-tx(imin))
      alpha_back = (ty(imin+1)-ty(imin))*linear_interp_back
      ty_back(imin) = ty_back(imin) + (one-alpha)*linear_interp_back
      ty_back(imin+1) = ty_back(imin+1) + alpha*linear_interp_back
      temp_back = alpha_back/(tx(imin+1)-tx(imin))
      x_back = x_back + temp_back
      temp_back0 = -((x-tx(imin))*temp_back/(tx(imin+1)-tx(imin)))
      tx_back(imin) = tx_back(imin) - temp_back - temp_back0
      tx_back(imin+1) = tx_back(imin+1) + temp_back0
    ELSE IF (x + zerom .LT. tx(imax)) THEN
      ind = imin + 1
      DO WHILE (tx(ind) .LT. x + zerom)
        ind = ind + 1
      END DO
      alpha = (x-tx(ind-1))/(tx(ind)-tx(ind-1))
      alpha_back = (ty(ind)-ty(ind-1))*linear_interp_back
      ty_back(ind-1) = ty_back(ind-1) + (one-alpha)*linear_interp_back
      ty_back(ind) = ty_back(ind) + alpha*linear_interp_back
      temp_back0 = alpha_back/(tx(ind)-tx(ind-1))
      x_back = x_back + temp_back0
      temp_back = -((x-tx(ind-1))*temp_back0/(tx(ind)-tx(ind-1)))
      tx_back(ind-1) = tx_back(ind-1) - temp_back0 - temp_back
      tx_back(ind) = tx_back(ind) + temp_back
    ELSE
      alpha = (x-tx(imax-1))/(tx(imax)-tx(imax-1))
      alpha_back = (ty(imax)-ty(imax-1))*linear_interp_back
      ty_back(imax-1) = ty_back(imax-1) + (one-alpha)*linear_interp_back
      ty_back(imax) = ty_back(imax) + alpha*linear_interp_back
      temp_back0 = alpha_back/(tx(imax)-tx(imax-1))
      x_back = x_back + temp_back0
      temp_back = -((x-tx(imax-1))*temp_back0/(tx(imax)-tx(imax-1)))
      tx_back(imax-1) = tx_back(imax-1) - temp_back0 - temp_back
      tx_back(imax) = tx_back(imax) + temp_back
    END IF
  END SUBROUTINE LINEAR_INTERP_BACK0


!  Differentiation of fv_cell_grad in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: grad_var.x grad_var.y var
!   with respect to varying inputs: var
  SUBROUTINE FV_CELL_GRAD_BACK(grad_var, grad_var_back, var, var_back, &
&   mesh)
    IMPLICIT NONE
    TYPE(MSH), INTENT(IN) :: mesh
    REAL(rp), DIMENSION(mesh%nc+mesh%ncb), INTENT(IN) :: var
    REAL(rp), DIMENSION(mesh%nc+mesh%ncb) :: var_back
    TYPE(VEC2D), DIMENSION(mesh%nc+mesh%ncb) :: grad_var
    TYPE(VEC2D), DIMENSION(mesh%nc+mesh%ncb) :: grad_var_back
! Left and Right cells indexes to edge
    INTEGER(ip) :: il, ir
    REAL(rp) :: temp_back
    INTEGER*4 :: branch
    DO ie=1,mesh%ne
      CALL PUSHINTEGER4(il)
      il = mesh%edge(ie)%cell(1)
      CALL PUSHINTEGER4(ir)
      ir = mesh%edge(ie)%cell(2)
      IF (.NOT.mesh%edge(ie)%boundary .AND. (.NOT.mesh%edge(ie)%&
&         subdomain)) THEN
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
    i = mesh%nc + 1
    DO i=mesh%nc,1,-1
      grad_var_back(i)%y = mesh%cell(i)%invsurf*grad_var_back(i)%y
      grad_var_back(i)%x = mesh%cell(i)%invsurf*grad_var_back(i)%x
    END DO
    DO ie=mesh%ne,1,-1
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) THEN
        il = mesh%edge(ie)%cell(1)
        ir = mesh%edge(ie)%cell(2)
        temp_back = -(mesh%edge(ie)%normal%y*mesh%edge(ie)%length*demi*&
&         grad_var_back(ir)%y)
        var_back(il) = var_back(il) + temp_back
        var_back(ir) = var_back(ir) + temp_back
        temp_back = -(mesh%edge(ie)%normal%x*mesh%edge(ie)%length*demi*&
&         grad_var_back(ir)%x)
        var_back(il) = var_back(il) + temp_back
        var_back(ir) = var_back(ir) + temp_back
      END IF
      temp_back = mesh%edge(ie)%normal%y*mesh%edge(ie)%length*demi*&
&       grad_var_back(il)%y
      var_back(il) = var_back(il) + temp_back
      var_back(ir) = var_back(ir) + temp_back
      temp_back = mesh%edge(ie)%normal%x*mesh%edge(ie)%length*demi*&
&       grad_var_back(il)%x
      var_back(il) = var_back(il) + temp_back
      var_back(ir) = var_back(ir) + temp_back
      CALL POPINTEGER4(ir)
      CALL POPINTEGER4(il)
    END DO
  END SUBROUTINE FV_CELL_GRAD_BACK


END MODULE M_NUMERIC_BACK

