!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Apr 2025 13:39
!
MODULE M_NUMERIC_DIFF

  USE M_NUMERIC
  USE M_MPI_DIFF
  USE M_TAP_VARS

CONTAINS

!  Differentiation of linear_interp in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: linear_interp
!   with respect to varying inputs: tx ty x
  REAL(rp) FUNCTION LINEAR_INTERP_DIFF(tx, tx_diff, ty, ty_diff, x, &
&   x_diff, linear_interp)
    IMPLICIT NONE
    REAL(rp), DIMENSION(:), INTENT(IN) :: tx, ty
    REAL(rp), DIMENSION(:), INTENT(IN) :: tx_diff, ty_diff
    REAL(rp), INTENT(IN) :: x
    REAL(rp), INTENT(IN) :: x_diff
    REAL(rp) :: alpha
    REAL(rp) :: alpha_diff
    INTEGER(ip) :: ind, imin, imax
    INTRINSIC LBOUND
    INTRINSIC UBOUND
    REAL(rp) :: temp
    REAL(rp) :: linear_interp
    imin = LBOUND(tx(:), dim=1)
    imax = UBOUND(tx(:), dim=1)
    IF (x + zerom .LT. tx(imin)) THEN
      temp = (x-tx(imin))/(tx(imin+1)-tx(imin))
      alpha_diff = (x_diff-tx_diff(imin)-temp*(tx_diff(imin+1)-tx_diff(&
&       imin)))/(tx(imin+1)-tx(imin))
      alpha = temp
      linear_interp_diff = (one-alpha)*ty_diff(imin) - (ty(imin)-ty(imin&
&       +1))*alpha_diff + alpha*ty_diff(imin+1)
      linear_interp = (one-alpha)*ty(imin) + alpha*ty(imin+1)
    ELSE IF (x + zerom .LT. tx(imax)) THEN
      ind = imin + 1
      DO WHILE (tx(ind) .LT. x + zerom)
        ind = ind + 1
      END DO
      temp = (x-tx(ind-1))/(tx(ind)-tx(ind-1))
      alpha_diff = (x_diff-tx_diff(ind-1)-temp*(tx_diff(ind)-tx_diff(ind&
&       -1)))/(tx(ind)-tx(ind-1))
      alpha = temp
      linear_interp_diff = (one-alpha)*ty_diff(ind-1) - (ty(ind-1)-ty(&
&       ind))*alpha_diff + alpha*ty_diff(ind)
      linear_interp = (one-alpha)*ty(ind-1) + alpha*ty(ind)
    ELSE
      temp = (x-tx(imax-1))/(tx(imax)-tx(imax-1))
      alpha_diff = (x_diff-tx_diff(imax-1)-temp*(tx_diff(imax)-tx_diff(&
&       imax-1)))/(tx(imax)-tx(imax-1))
      alpha = temp
      linear_interp_diff = (one-alpha)*ty_diff(imax-1) - (ty(imax-1)-ty(&
&       imax))*alpha_diff + alpha*ty_diff(imax)
      linear_interp = (one-alpha)*ty(imax-1) + alpha*ty(imax)
    END IF
  END FUNCTION LINEAR_INTERP_DIFF


!  Differentiation of fv_cell_grad in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: grad_var.x grad_var.y
!   with respect to varying inputs: var
  SUBROUTINE FV_CELL_GRAD_DIFF(grad_var, grad_var_diff, var, var_diff, &
&   mesh)
    IMPLICIT NONE
    TYPE(MSH), INTENT(IN) :: mesh
    REAL(rp), DIMENSION(mesh%nc+mesh%ncb), INTENT(IN) :: var
    REAL(rp), DIMENSION(mesh%nc+mesh%ncb), INTENT(IN) :: var_diff
    TYPE(VEC2D), DIMENSION(mesh%nc+mesh%ncb), INTENT(OUT) :: grad_var
    TYPE(VEC2D), DIMENSION(mesh%nc+mesh%ncb), INTENT(OUT) :: &
&   grad_var_diff
! Left and Right cells indexes to edge
    INTEGER(ip) :: il, ir
    REAL(rp) :: temp
    grad_var(:)%x = 0._rp
    grad_var(:)%y = 0._rp
    grad_var_diff%x = 0.0_8
    grad_var_diff%y = 0.0_8
    DO ie=1,mesh%ne
      il = mesh%edge(ie)%cell(1)
      ir = mesh%edge(ie)%cell(2)
      temp = mesh%edge(ie)%length*demi
      grad_var_diff(il)%x = grad_var_diff(il)%x + temp*mesh%edge(ie)%&
&       normal%x*(var_diff(il)+var_diff(ir))
      grad_var(il)%x = grad_var(il)%x + temp*(mesh%edge(ie)%normal%x*(&
&       var(il)+var(ir)))
      temp = mesh%edge(ie)%length*demi
      grad_var_diff(il)%y = grad_var_diff(il)%y + temp*mesh%edge(ie)%&
&       normal%y*(var_diff(il)+var_diff(ir))
      grad_var(il)%y = grad_var(il)%y + temp*(mesh%edge(ie)%normal%y*(&
&       var(il)+var(ir)))
      IF (.NOT.mesh%edge(ie)%boundary .AND. (.NOT.mesh%edge(ie)%&
&         subdomain)) THEN
        temp = mesh%edge(ie)%length*demi
        grad_var_diff(ir)%x = grad_var_diff(ir)%x - temp*mesh%edge(ie)%&
&         normal%x*(var_diff(il)+var_diff(ir))
        grad_var(ir)%x = grad_var(ir)%x - temp*(mesh%edge(ie)%normal%x*(&
&         var(il)+var(ir)))
        temp = mesh%edge(ie)%length*demi
        grad_var_diff(ir)%y = grad_var_diff(ir)%y - temp*mesh%edge(ie)%&
&         normal%y*(var_diff(il)+var_diff(ir))
        grad_var(ir)%y = grad_var(ir)%y - temp*(mesh%edge(ie)%normal%y*(&
&         var(il)+var(ir)))
      END IF
    END DO
    DO i=1,mesh%nc
      grad_var_diff(i)%x = mesh%cell(i)%invsurf*grad_var_diff(i)%x
      grad_var(i)%x = grad_var(i)%x*mesh%cell(i)%invsurf
      grad_var_diff(i)%y = mesh%cell(i)%invsurf*grad_var_diff(i)%y
      grad_var(i)%y = grad_var(i)%y*mesh%cell(i)%invsurf
    END DO
    CALL COM_VAR_R(grad_var(:)%x, mesh)
    CALL COM_VAR_R(grad_var(:)%y, mesh)
  END SUBROUTINE FV_CELL_GRAD_DIFF


END MODULE M_NUMERIC_DIFF

