!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
MODULE M_NUMERIC_DIFF

  USE M_TAP_VARS

CONTAINS

!  Differentiation of linear_interp in forward (tangent) mode (with options fixinterface noISIZE):
!   variations   of useful results: linear_interp
!   with respect to varying inputs: tx ty x
  REAL(rp) FUNCTION LINEAR_INTERP_DIFF(tx, tx_diff, ty, ty_diff, x, &
&   x_diff, linear_interp)
    IMPLICIT NONE
    REAL(rp), DIMENSION(:), INTENT(IN) :: tx, ty
    REAL(rp), DIMENSION(:), INTENT(IN) :: tx_diff, ty_diff
    REAL(rp), INTENT(IN) :: x
    REAL(rp), INTENT(IN) :: x_diff
    REAL(rp) :: alpha
    REAL(rp) :: alpha_diff
    INTEGER(ip) :: ind, imin, imax
    INTRINSIC LBOUND
    INTRINSIC UBOUND
    REAL(rp) :: temp
    REAL(rp) :: linear_interp
    imin = LBOUND(tx(:), dim=1)
    imax = UBOUND(tx(:), dim=1)
    IF (x + zerom .LT. tx(imin)) THEN
      temp = (x-tx(imin))/(tx(imin+1)-tx(imin))
      alpha_diff = (x_diff-tx_diff(imin)-temp*(tx_diff(imin+1)-tx_diff(&
&       imin)))/(tx(imin+1)-tx(imin))
      alpha = temp
      linear_interp_diff = (one-alpha)*ty_diff(imin) - (ty(imin)-ty(imin&
&       +1))*alpha_diff + alpha*ty_diff(imin+1)
      linear_interp = (one-alpha)*ty(imin) + alpha*ty(imin+1)
    ELSE IF (x + zerom .LT. tx(imax)) THEN
      ind = imin + 1
      DO WHILE (tx(ind) .LT. x + zerom)
        ind = ind + 1
      END DO
      temp = (x-tx(ind-1))/(tx(ind)-tx(ind-1))
      alpha_diff = (x_diff-tx_diff(ind-1)-temp*(tx_diff(ind)-tx_diff(ind&
&       -1)))/(tx(ind)-tx(ind-1))
      alpha = temp
      linear_interp_diff = (one-alpha)*ty_diff(ind-1) - (ty(ind-1)-ty(&
&       ind))*alpha_diff + alpha*ty_diff(ind)
      linear_interp = (one-alpha)*ty(ind-1) + alpha*ty(ind)
    ELSE
      temp = (x-tx(imax-1))/(tx(imax)-tx(imax-1))
      alpha_diff = (x_diff-tx_diff(imax-1)-temp*(tx_diff(imax)-tx_diff(&
&       imax-1)))/(tx(imax)-tx(imax-1))
      alpha = temp
      linear_interp_diff = (one-alpha)*ty_diff(imax-1) - (ty(imax-1)-ty(&
&       imax))*alpha_diff + alpha*ty_diff(imax)
      linear_interp = (one-alpha)*ty(imax-1) + alpha*ty(imax)
    END IF
  END FUNCTION LINEAR_INTERP_DIFF



END MODULE M_NUMERIC_DIFF

