!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 25 Jun 2025 16:38
!
MODULE M_OBS_BACK

  USE M_OBS
  USE M_MPI_BACK
  USE M_TAP_VARS

CONTAINS
!  Differentiation of calc_cost_function in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: *(*innovation.diff) *(*innovq.diff)
!                *(*innovuv.diff) cost
!   with respect to varying inputs: *(*(bc.hyd).q) *xsshape.xcenter
!                *xsshape.s *xsshape.hmax *bathy_cell *(*innovation.diff)
!                *(*innovq.diff) *(*innovuv.diff) *(mesh.cell).invsurf
!                *(mesh.cell).grav.x *(mesh.cell).grav.y *(mesh.edge).length
!                *(mesh.edge).normal.x *(mesh.edge).normal.y cost
!   Plus diff mem management of: bc.hyd:in *(bc.hyd).q:in xsshape:in
!                bathy_cell:in innovation:in *innovation.diff:in
!                innovq:in *innovq.diff:in innovuv:in *innovuv.diff:in
!                mesh.cell:in mesh.edge:in
  SUBROUTINE CALC_COST_FUNCTION_BACK(cost, cost_back, mesh, mesh_back)
    USE M_NUMERIC_BACK
    IMPLICIT NONE
    TYPE(MSH), INTENT(IN) :: mesh
    TYPE(MSH) :: mesh_back ! Replaced by Perl Script
    REAL(rp), INTENT(INOUT) :: cost
    REAL(rp), INTENT(INOUT) :: cost_back
    REAL(rp) :: cost_part(3), filtered(4)
    REAL(rp) :: cost_part_back(3), filtered_back(4)
    INTEGER(ip) :: idiff, temp, sizeq
    TYPE(VEC2D), DIMENSION(mesh%nc+mesh%ncb) :: grad_var
    TYPE(VEC2D), DIMENSION(mesh%nc+mesh%ncb) :: grad_var_back
    REAL(rp), DIMENSION(mesh%nc+mesh%ncb) :: bathy_temp
    REAL(rp), DIMENSION(mesh%nc+mesh%ncb) :: bathy_temp_back
    INTRINSIC SIZE
    INTRINSIC ABS
    INTRINSIC MIN
    INTRINSIC SUM
    INTRINSIC SQRT
    REAL(rp) :: y1
    REAL(rp) :: y1_back
    REAL(rp) :: y2
    REAL(rp) :: y2_back
    REAL(rp) :: y3
    REAL(rp) :: y3_back
    REAL(rp) :: y4
    REAL(rp) :: y4_back
    REAL(rp) :: y5
    REAL(rp) :: y5_back
    REAL(rp) :: y6
    REAL(rp) :: y6_back
    REAL(rp) :: y7
    REAL(rp) :: y7_back
    REAL(rp) :: y8
    REAL(rp) :: y8_back
    REAL(rp) :: min1
    REAL(rp) :: min1_back
    REAL(rp) :: min2
    REAL(rp) :: min2_back
    REAL(rp) :: min3
    REAL(rp) :: min3_back
    REAL(rp) :: min4
    REAL(rp) :: min4_back
    REAL(rp) :: min5
    REAL(rp) :: min5_back
    REAL(rp) :: min6
    REAL(rp) :: min6_back
    REAL(rp) :: min7
    REAL(rp) :: min7_back
    REAL(rp) :: min8
    REAL(rp) :: min8_back
    REAL(rp) :: abs0
    REAL(rp) :: abs0_back
    REAL(rp) :: abs1
    REAL(rp) :: abs1_back
    REAL(rp) :: abs2
    REAL(rp) :: abs2_back
    REAL(rp) :: abs3
    REAL(rp) :: abs3_back
    REAL(rp) :: abs4
    REAL(rp) :: abs4_back
    REAL(rp) :: abs5
    REAL(rp) :: abs5_back
    REAL(rp) :: abs6
    REAL(rp) :: abs6_back
    REAL(rp) :: abs7
    REAL(rp) :: abs7_back
    REAL(rp) :: abs8
    REAL(rp) :: abs8_back
    REAL(rp) :: abs9
    REAL(rp) :: abs9_back
    REAL(rp) :: abs10
    REAL(rp) :: abs10_back
    REAL(rp) :: abs11
    REAL(rp) :: abs11_back
    REAL(rp) :: abs12
    REAL(rp) :: abs12_back
    REAL(rp) :: abs13
    REAL(rp) :: abs13_back
    REAL(rp) :: abs14
    REAL(rp) :: abs14_back
    REAL(rp) :: abs15
    REAL(rp) :: abs15_back
    REAL(rp) :: abs16
    REAL(rp) :: abs16_back
    REAL(rp) :: abs17
    REAL(rp) :: abs17_back
    REAL(rp) :: abs18
    REAL(rp) :: abs18_back
    REAL(rp) :: abs19
    REAL(rp) :: abs19_back
    REAL(rp) :: abs20
    REAL(rp) :: abs20_back
    REAL(rp) :: abs21
    REAL(rp) :: abs21_back
    REAL(rp) :: abs22
    REAL(rp) :: abs22_back
    REAL(rp) :: abs23
    REAL(rp) :: abs23_back
    REAL(rp) :: temp0
    REAL(rp) :: temp_back
    REAL(rp) :: temp1
    REAL(rp) :: temp_back0
    INTEGER*4 :: ad_to
    INTEGER*4 :: ad_to0
    INTEGER*4 :: ad_to1
    INTEGER*4 :: ad_to2
    INTEGER*4 :: ad_to3
    INTEGER*4 :: ad_to4
    INTEGER*4 :: ad_to5
    INTEGER*4 :: ad_to6
    INTEGER*4 :: branch
    INTEGER*4 :: ad_to7
    INTEGER :: ii1
    IF (use_obs .EQ. 1) THEN
      cost_part(:) = 0._rp
      IF (use_zobs .EQ. 1) THEN
        DO iobs=1,SIZE(station)
          DO idiff=1,SIZE(innovation(iobs)%diff)
            cost_part(1) = cost_part(1) + station(iobs)%weight*&
&             innovation(iobs)%diff(idiff)**2
          END DO
          CALL PUSHINTEGER4(idiff - 1)
        END DO
        CALL PUSHINTEGER4(iobs - 1)
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHCONTROL1B(1)
      END IF
      IF (use_uvobs .EQ. 1) THEN
        DO iobs=1,SIZE(station)
          DO idiff=1,SIZE(innovuv(iobs)%diff)
            cost_part(1) = cost_part(1) + station(iobs)%weight*innovuv(&
&             iobs)%diff(idiff)**2
          END DO
          CALL PUSHINTEGER4(idiff - 1)
        END DO
        CALL PUSHINTEGER4(iobs - 1)
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHCONTROL1B(1)
      END IF
      IF (use_qobs .EQ. 1 .OR. use_qobs_gr4 .EQ. 1) THEN
        IF (use_nse .EQ. 0) THEN
          DO iobs=1,SIZE(stationq)
            DO idiff=1,SIZE(innovq(iobs)%diff)
              cost_part(1) = cost_part(1) + stationq(iobs)%weight*innovq&
&               (iobs)%diff(idiff)**2
            END DO
            CALL PUSHINTEGER4(idiff - 1)
          END DO
          CALL PUSHINTEGER4(iobs - 1)
          CALL PUSHCONTROL2B(0)
        ELSE
          sizeq = SIZE(stationq)
          DO iobs=1,SIZE(stationq)
            CALL PUSHREAL8(cost_part(3))
            cost_part(3) = 0._rp
            CALL PUSHREAL8(cost_part(2))
            cost_part(2) = 0._rp
            DO idiff=1,SIZE(innovq(iobs)%diff)
              CALL PUSHREAL8(cost_part(2))
              cost_part(2) = cost_part(2) + innovq(iobs)%diff(idiff)**2
              CALL PUSHREAL8(cost_part(3))
              cost_part(3) = cost_part(3) + innovq(iobs+sizeq)%diff(&
&               idiff)**2
            END DO
            CALL PUSHINTEGER4(idiff - 1)
            CALL PUSHREAL8(cost_part(1))
            cost_part(1) = cost_part(1) + cost_part(2)/cost_part(3)
          END DO
          CALL PUSHINTEGER4(iobs - 1)
          CALL PUSHCONTROL2B(1)
        END IF
      ELSE
        CALL PUSHCONTROL2B(2)
      END IF
      CALL MPI_SUM_R(cost_part(1))
      IF (regul_bathy_grad .EQ. 1) THEN
        CALL FV_CELL_GRAD(grad_var, bathy_cell, mesh)
        CALL PUSHCONTROL2B(0)
      ELSE IF (regul_bathy_grad .EQ. 2 .AND. use_xsshp .EQ. 1) THEN
        bathy_temp(:) = 0._rp
        IF (xsshp_along_y .EQ. 1) THEN
          DO ie=1,mesh%nc
            IF (mesh%cell(ie)%grav%x .LE. xsshape(1)%xcenter) THEN
              IF (xsshape(1)%hmax .GE. 0.) THEN
                CALL PUSHREAL8(abs0)
                abs0 = xsshape(1)%hmax
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs0)
                abs0 = -xsshape(1)%hmax
                CALL PUSHCONTROL1B(0)
              END IF
              IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                CALL PUSHREAL8(abs8)
                abs8 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs8)
                abs8 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape(&
&                 1)%xcenter-xsshape(1)%xleft))
                CALL PUSHCONTROL1B(0)
              END IF
              IF (xsshape(1)%s .GE. 0.) THEN
                CALL PUSHREAL8(abs16)
                abs16 = xsshape(1)%s
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHREAL8(abs16)
                abs16 = -xsshape(1)%s
                CALL PUSHCONTROL1B(1)
              END IF
              y1 = -(abs0*(1-(abs8/(xsshape(1)%xcenter-xsshape(1)%xleft)&
&               )**abs16))
              IF (0._rp .GT. y1) THEN
                min1 = y1
                CALL PUSHCONTROL1B(0)
              ELSE
                min1 = 0._rp
                CALL PUSHCONTROL1B(1)
              END IF
              bathy_temp(ie) = bathy_cell(ie) - (xsshape(1)%topz+min1+&
&               slope_y(1)*mesh%cell(ie)%grav%y+slope_x(1)*mesh%cell(ie)&
&               %grav%x)
              CALL PUSHCONTROL1B(1)
            ELSE
              IF (xsshape(1)%hmax .GE. 0.) THEN
                CALL PUSHREAL8(abs1)
                abs1 = xsshape(1)%hmax
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs1)
                abs1 = -xsshape(1)%hmax
                CALL PUSHCONTROL1B(0)
              END IF
              IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                CALL PUSHREAL8(abs9)
                abs9 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs9)
                abs9 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape(&
&                 1)%xcenter-xsshape(1)%xleft))
                CALL PUSHCONTROL1B(0)
              END IF
              IF (xsshape(1)%s .GE. 0.) THEN
                CALL PUSHREAL8(abs17)
                abs17 = xsshape(1)%s
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHREAL8(abs17)
                abs17 = -xsshape(1)%s
                CALL PUSHCONTROL1B(1)
              END IF
              y2 = -(abs1*(1-(abs9/(xsshape(1)%xright-xsshape(1)%xcenter&
&               ))**abs17))
              IF (0._rp .GT. y2) THEN
                min2 = y2
                CALL PUSHCONTROL1B(0)
              ELSE
                min2 = 0._rp
                CALL PUSHCONTROL1B(1)
              END IF
              bathy_temp(ie) = bathy_cell(ie) - (xsshape(1)%topz+min2+&
&               slope_y(1)*mesh%cell(ie)%grav%y+slope_x(1)*mesh%cell(ie)&
&               %grav%x)
              CALL PUSHCONTROL1B(0)
            END IF
          END DO
          CALL PUSHCONTROL2B(0)
        ELSE IF (xsshp_along_x .EQ. 1) THEN
          DO ie=1,mesh%nc
            IF (mesh%cell(ie)%grav%y .LE. xsshape(1)%xcenter) THEN
              IF (xsshape(1)%hmax .GE. 0.) THEN
                CALL PUSHREAL8(abs2)
                abs2 = xsshape(1)%hmax
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs2)
                abs2 = -xsshape(1)%hmax
                CALL PUSHCONTROL1B(0)
              END IF
              IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                CALL PUSHREAL8(abs10)
                abs10 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs10)
                abs10 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft))
                CALL PUSHCONTROL1B(0)
              END IF
              IF (xsshape(1)%s .GE. 0.) THEN
                CALL PUSHREAL8(abs18)
                abs18 = xsshape(1)%s
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHREAL8(abs18)
                abs18 = -xsshape(1)%s
                CALL PUSHCONTROL1B(1)
              END IF
              y3 = -(abs2*(1-(abs10/(xsshape(1)%xcenter-xsshape(1)%xleft&
&               ))**abs18))
              IF (0._rp .GT. y3) THEN
                min3 = y3
                CALL PUSHCONTROL1B(0)
              ELSE
                min3 = 0._rp
                CALL PUSHCONTROL1B(1)
              END IF
              bathy_temp(ie) = bathy_cell(ie) - (xsshape(1)%topz+min3+&
&               slope_y(1)*mesh%cell(ie)%grav%y+slope_x(1)*mesh%cell(ie)&
&               %grav%x)
              CALL PUSHCONTROL1B(1)
            ELSE
              IF (xsshape(1)%hmax .GE. 0.) THEN
                CALL PUSHREAL8(abs3)
                abs3 = xsshape(1)%hmax
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs3)
                abs3 = -xsshape(1)%hmax
                CALL PUSHCONTROL1B(0)
              END IF
              IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                CALL PUSHREAL8(abs11)
                abs11 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs11)
                abs11 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft))
                CALL PUSHCONTROL1B(0)
              END IF
              IF (xsshape(1)%s .GE. 0.) THEN
                CALL PUSHREAL8(abs19)
                abs19 = xsshape(1)%s
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHREAL8(abs19)
                abs19 = -xsshape(1)%s
                CALL PUSHCONTROL1B(1)
              END IF
              y4 = -(abs3*(1-(abs11/(xsshape(1)%xright-xsshape(1)%&
&               xcenter))**abs19))
              IF (0._rp .GT. y4) THEN
                min4 = y4
                CALL PUSHCONTROL1B(0)
              ELSE
                min4 = 0._rp
                CALL PUSHCONTROL1B(1)
              END IF
              bathy_temp(ie) = bathy_cell(ie) - (xsshape(1)%topz+min4+&
&               slope_y(1)*mesh%cell(ie)%grav%y+slope_x(1)*mesh%cell(ie)&
&               %grav%x)
              CALL PUSHCONTROL1B(0)
            END IF
          END DO
          CALL PUSHCONTROL2B(1)
        ELSE
          CALL PUSHCONTROL2B(2)
        END IF
        CALL FV_CELL_GRAD(grad_var, bathy_temp, mesh)
        CALL PUSHCONTROL2B(1)
      ELSE
        CALL PUSHCONTROL2B(2)
      END IF
      IF (regul_bathy_grad .NE. 0) THEN
        DO i=1,mesh%nc
          CALL PUSHREAL8(cost_part(2))
          cost_part(2) = cost_part(2) + (grad_var(i)%x**2+grad_var(i)%y&
&           **2)
        END DO
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHCONTROL1B(1)
      END IF
      IF (regul_bathy_shape .EQ. 1 .AND. use_xsshp .EQ. 1) THEN
        IF (xsshp_along_x .EQ. 1) THEN
          DO ie=1,mesh%nc
            IF (mesh%cell(ie)%grav%x .LE. xsshape(1)%xcenter) THEN
              IF (xsshape(1)%hmax .GE. 0.) THEN
                CALL PUSHREAL8(abs4)
                abs4 = xsshape(1)%hmax
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs4)
                abs4 = -xsshape(1)%hmax
                CALL PUSHCONTROL1B(0)
              END IF
              IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                CALL PUSHREAL8(abs12)
                abs12 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs12)
                abs12 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft))
                CALL PUSHCONTROL1B(0)
              END IF
              IF (xsshape(1)%s .GE. 0.) THEN
                CALL PUSHREAL8(abs20)
                abs20 = xsshape(1)%s
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHREAL8(abs20)
                abs20 = -xsshape(1)%s
                CALL PUSHCONTROL1B(1)
              END IF
              y5 = -(abs4*(1-(abs12/(xsshape(1)%xcenter-xsshape(1)%xleft&
&               ))**abs20))
              IF (0._rp .GT. y5) THEN
                CALL PUSHREAL8(min5)
                min5 = y5
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHREAL8(min5)
                min5 = 0._rp
                CALL PUSHCONTROL1B(1)
              END IF
              CALL PUSHREAL8(cost_part(2))
              cost_part(2) = cost_part(2) + (bathy_cell(ie)-(xsshape(1)%&
&               topz+min5+slope_y(1)*mesh%cell(ie)%grav%y+slope_x(1)*&
&               mesh%cell(ie)%grav%x))**2
              CALL PUSHCONTROL1B(1)
            ELSE
              IF (xsshape(1)%hmax .GE. 0.) THEN
                CALL PUSHREAL8(abs5)
                abs5 = xsshape(1)%hmax
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs5)
                abs5 = -xsshape(1)%hmax
                CALL PUSHCONTROL1B(0)
              END IF
              IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                CALL PUSHREAL8(abs13)
                abs13 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs13)
                abs13 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft))
                CALL PUSHCONTROL1B(0)
              END IF
              IF (xsshape(1)%s .GE. 0.) THEN
                CALL PUSHREAL8(abs21)
                abs21 = xsshape(1)%s
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHREAL8(abs21)
                abs21 = -xsshape(1)%s
                CALL PUSHCONTROL1B(1)
              END IF
              y6 = -(abs5*(1-(abs13/(xsshape(1)%xright-xsshape(1)%&
&               xcenter))**abs21))
              IF (0._rp .GT. y6) THEN
                CALL PUSHREAL8(min6)
                min6 = y6
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHREAL8(min6)
                min6 = 0._rp
                CALL PUSHCONTROL1B(1)
              END IF
              CALL PUSHREAL8(cost_part(2))
              cost_part(2) = cost_part(2) + (bathy_cell(ie)-(xsshape(1)%&
&               topz+min6+slope_y(1)*mesh%cell(ie)%grav%y+slope_x(1)*&
&               mesh%cell(ie)%grav%x))**2
              CALL PUSHCONTROL1B(0)
            END IF
          END DO
          CALL MPI_SUM_R(cost_part(2))
          CALL PUSHCONTROL2B(0)
        ELSE IF (xsshp_along_y .EQ. 1) THEN
          DO ie=1,mesh%nc
            IF (mesh%cell(ie)%grav%y .LE. xsshape(1)%xcenter) THEN
              IF (xsshape(1)%hmax .GE. 0.) THEN
                CALL PUSHREAL8(abs6)
                abs6 = xsshape(1)%hmax
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs6)
                abs6 = -xsshape(1)%hmax
                CALL PUSHCONTROL1B(0)
              END IF
              IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                CALL PUSHREAL8(abs14)
                abs14 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs14)
                abs14 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft))
                CALL PUSHCONTROL1B(0)
              END IF
              IF (xsshape(1)%s .GE. 0.) THEN
                CALL PUSHREAL8(abs22)
                abs22 = xsshape(1)%s
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHREAL8(abs22)
                abs22 = -xsshape(1)%s
                CALL PUSHCONTROL1B(1)
              END IF
              y7 = -(abs6*(1-(abs14/(xsshape(1)%xcenter-xsshape(1)%xleft&
&               ))**abs22))
              IF (0._rp .GT. y7) THEN
                CALL PUSHREAL8(min7)
                min7 = y7
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHREAL8(min7)
                min7 = 0._rp
                CALL PUSHCONTROL1B(1)
              END IF
              CALL PUSHREAL8(cost_part(2))
              cost_part(2) = cost_part(2) + (bathy_cell(ie)-(xsshape(1)%&
&               topz+min7+slope_y(1)*mesh%cell(ie)%grav%y+slope_x(1)*&
&               mesh%cell(ie)%grav%x))**2
              CALL PUSHCONTROL1B(1)
            ELSE
              IF (xsshape(1)%hmax .GE. 0.) THEN
                CALL PUSHREAL8(abs7)
                abs7 = xsshape(1)%hmax
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs7)
                abs7 = -xsshape(1)%hmax
                CALL PUSHCONTROL1B(0)
              END IF
              IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                CALL PUSHREAL8(abs15)
                abs15 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
                CALL PUSHCONTROL1B(1)
              ELSE
                CALL PUSHREAL8(abs15)
                abs15 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft))
                CALL PUSHCONTROL1B(0)
              END IF
              IF (xsshape(1)%s .GE. 0.) THEN
                CALL PUSHREAL8(abs23)
                abs23 = xsshape(1)%s
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHREAL8(abs23)
                abs23 = -xsshape(1)%s
                CALL PUSHCONTROL1B(1)
              END IF
              y8 = -(abs7*(1-(abs15/(xsshape(1)%xright-xsshape(1)%&
&               xcenter))**abs23))
              IF (0._rp .GT. y8) THEN
                CALL PUSHREAL8(min8)
                min8 = y8
                CALL PUSHCONTROL1B(0)
              ELSE
                CALL PUSHREAL8(min8)
                min8 = 0._rp
                CALL PUSHCONTROL1B(1)
              END IF
              CALL PUSHREAL8(cost_part(2))
              cost_part(2) = cost_part(2) + (bathy_cell(ie)-(xsshape(1)%&
&               topz+min8+slope_y(1)*mesh%cell(ie)%grav%y+slope_x(1)*&
&               mesh%cell(ie)%grav%x))**2
              CALL PUSHCONTROL1B(0)
            END IF
          END DO
          CALL MPI_SUM_R(cost_part(2))
          CALL PUSHCONTROL2B(1)
        ELSE
          CALL PUSHCONTROL2B(2)
        END IF
      ELSE
        CALL PUSHCONTROL2B(3)
      END IF
      CALL PUSHREAL8(cost_part(2))
      cost_part(2) = cost_part(2)*regul_bathy
      DO k=1,bc%nb_in
        CALL PUSHREAL8(filtered(1))
        filtered(1) = bc%hyd(k)%q(1)
        DO i=2,SIZE(bc%hyd(k)%q(:))-3
          CALL PUSHREAL8(filtered(2))
          filtered(2) = filtered(1) + 0.2_rp*(bc%hyd(k)%q(i)-filtered(1)&
&           )
          CALL PUSHREAL8(filtered(3))
          filtered(3) = filtered(2) + 0.2_rp*(bc%hyd(k)%q(i+1)-filtered(&
&           2))
          CALL PUSHREAL8(filtered(4))
          filtered(4) = filtered(3) + 0.2_rp*(bc%hyd(k)%q(i+2)-filtered(&
&           3))
          CALL PUSHREAL8(cost_part(3))
          cost_part(3) = cost_part(3) + (bc%hyd(k)%q(i)-filtered(4))**2
          CALL PUSHREAL8(filtered(1))
          filtered(1) = filtered(4)
        END DO
        CALL PUSHINTEGER4(i - 1)
      END DO
      CALL PUSHREAL8(cost_part(3))
      cost_part(3) = cost_part(3)*regul_hydrograph
      cost = SUM(cost_part)
      CALL PUSHCONTROL1B(0)
    ELSE
      CALL PUSHCONTROL1B(1)
    END IF
    IF (cost**2 .EQ. 0.0) THEN
      cost_back = 0.0_8
    ELSE
      cost_back = 2*cost*cost_back/(2.0*SQRT(cost**2))
    END IF
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      cost_part_back = 0.0_8
      cost_part_back = cost_back
      CALL POPREAL8(cost_part(3))
      cost_part_back(3) = regul_hydrograph*cost_part_back(3)
      DO ii1=1,size(bc%hyd,1)
        bc_back%hyd(ii1)%q = 0.0_8
      END DO
      filtered_back = 0.0_8
      DO k=bc%nb_in,1,-1
        CALL POPINTEGER4(ad_to7)
        DO i=ad_to7,2,-1
          temp_back0 = 2*(bc%hyd(k)%q(i)-filtered(4))*cost_part_back(3)
          CALL POPREAL8(filtered(1))
          filtered_back(4) = filtered_back(4) + filtered_back(1) - &
&           temp_back0
          CALL POPREAL8(cost_part(3))
          bc_back%hyd(k)%q(i) = bc_back%hyd(k)%q(i) + temp_back0
          CALL POPREAL8(filtered(4))
          filtered_back(3) = filtered_back(3) + 0.8*filtered_back(4)
          bc_back%hyd(k)%q(i+2) = bc_back%hyd(k)%q(i+2) + 0.2_rp*&
&           filtered_back(4)
          filtered_back(4) = 0.0_8
          CALL POPREAL8(filtered(3))
          filtered_back(2) = filtered_back(2) + 0.8*filtered_back(3)
          filtered_back(1) = 0.8*filtered_back(2)
          bc_back%hyd(k)%q(i+1) = bc_back%hyd(k)%q(i+1) + 0.2_rp*&
&           filtered_back(3)
          filtered_back(3) = 0.0_8
          CALL POPREAL8(filtered(2))
          bc_back%hyd(k)%q(i) = bc_back%hyd(k)%q(i) + 0.2_rp*&
&           filtered_back(2)
          filtered_back(2) = 0.0_8
        END DO
        CALL POPREAL8(filtered(1))
        bc_back%hyd(k)%q(1) = bc_back%hyd(k)%q(1) + filtered_back(1)
        filtered_back(1) = 0.0_8
      END DO
      CALL POPREAL8(cost_part(2))
      cost_part_back(2) = regul_bathy*cost_part_back(2)
      CALL POPCONTROL2B(branch)
      IF (branch .LT. 2) THEN
        IF (branch .EQ. 0) THEN
          IF (ALLOCATED(xsshape_back)) xsshape_back%xcenter = 0.0_8
          IF (ALLOCATED(xsshape_back)) xsshape_back%s = 0.0_8
          IF (ALLOCATED(xsshape_back)) xsshape_back%hmax = 0.0_8
          IF (ALLOCATED(bathy_cell_back)) bathy_cell_back = 0.0_8
          mesh_back%cell%grav%x = 0.0_8
          mesh_back%cell%grav%y = 0.0_8
          DO ie=mesh%nc,1,-1
            CALL POPCONTROL1B(branch)
            IF (branch .EQ. 0) THEN
              CALL POPREAL8(cost_part(2))
              temp_back0 = 2*(bathy_cell(ie)-xsshape(1)%topz-min6-&
&               slope_y(1)*mesh%cell(ie)%grav%y-slope_x(1)*mesh%cell(ie)&
&               %grav%x)*cost_part_back(2)
              bathy_cell_back(ie) = bathy_cell_back(ie) + temp_back0
              min6_back = -temp_back0
              mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y - &
&               slope_y(1)*temp_back0
              mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x - &
&               slope_x(1)*temp_back0
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(min6)
                y6_back = min6_back
              ELSE
                CALL POPREAL8(min6)
                y6_back = 0.0_8
              END IF
              temp1 = abs13/(xsshape(1)%xright-xsshape(1)%xcenter)
              temp0 = temp1**abs21
              abs5_back = -((1-temp0)*y6_back)
              IF (temp1 .LE. 0.0 .AND. (abs21 .EQ. 0.0 .OR. abs21 .NE. &
&                 INT(abs21))) THEN
                temp_back0 = 0.0_8
              ELSE
                temp_back0 = abs21*temp1**(abs21-1)*abs5*y6_back/(&
&                 xsshape(1)%xright-xsshape(1)%xcenter)
              END IF
              IF (temp1 .LE. 0.0) THEN
                abs21_back = 0.0_8
              ELSE
                abs21_back = temp0*LOG(temp1)*abs5*y6_back
              END IF
              abs13_back = temp_back0
              xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + temp1*&
&               temp_back0
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs21)
                xsshape_back(1)%s = xsshape_back(1)%s + abs21_back
              ELSE
                CALL POPREAL8(abs21)
                xsshape_back(1)%s = xsshape_back(1)%s - abs21_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs13)
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + &
&                 abs13_back
                mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x - &
&                 abs13_back
              ELSE
                CALL POPREAL8(abs13)
                mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x + &
&                 abs13_back
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - &
&                 abs13_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs5)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax - abs5_back
              ELSE
                CALL POPREAL8(abs5)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax + abs5_back
              END IF
            ELSE
              CALL POPREAL8(cost_part(2))
              temp_back0 = 2*(bathy_cell(ie)-xsshape(1)%topz-min5-&
&               slope_y(1)*mesh%cell(ie)%grav%y-slope_x(1)*mesh%cell(ie)&
&               %grav%x)*cost_part_back(2)
              bathy_cell_back(ie) = bathy_cell_back(ie) + temp_back0
              min5_back = -temp_back0
              mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y - &
&               slope_y(1)*temp_back0
              mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x - &
&               slope_x(1)*temp_back0
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(min5)
                y5_back = min5_back
              ELSE
                CALL POPREAL8(min5)
                y5_back = 0.0_8
              END IF
              temp1 = abs12/(xsshape(1)%xcenter-xsshape(1)%xleft)
              temp0 = temp1**abs20
              abs4_back = -((1-temp0)*y5_back)
              IF (temp1 .LE. 0.0 .AND. (abs20 .EQ. 0.0 .OR. abs20 .NE. &
&                 INT(abs20))) THEN
                temp_back0 = 0.0_8
              ELSE
                temp_back0 = abs20*temp1**(abs20-1)*abs4*y5_back/(&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
              END IF
              IF (temp1 .LE. 0.0) THEN
                abs20_back = 0.0_8
              ELSE
                abs20_back = temp0*LOG(temp1)*abs4*y5_back
              END IF
              abs12_back = temp_back0
              xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - temp1*&
&               temp_back0
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs20)
                xsshape_back(1)%s = xsshape_back(1)%s + abs20_back
              ELSE
                CALL POPREAL8(abs20)
                xsshape_back(1)%s = xsshape_back(1)%s - abs20_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs12)
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + &
&                 abs12_back
                mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x - &
&                 abs12_back
              ELSE
                CALL POPREAL8(abs12)
                mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x + &
&                 abs12_back
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - &
&                 abs12_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs4)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax - abs4_back
              ELSE
                CALL POPREAL8(abs4)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax + abs4_back
              END IF
            END IF
          END DO
        ELSE
          IF (ALLOCATED(xsshape_back)) xsshape_back%xcenter = 0.0_8
          IF (ALLOCATED(xsshape_back)) xsshape_back%s = 0.0_8
          IF (ALLOCATED(xsshape_back)) xsshape_back%hmax = 0.0_8
          IF (ALLOCATED(bathy_cell_back)) bathy_cell_back = 0.0_8
          mesh_back%cell%grav%x = 0.0_8
          mesh_back%cell%grav%y = 0.0_8
          DO ie=mesh%nc,1,-1
            CALL POPCONTROL1B(branch)
            IF (branch .EQ. 0) THEN
              CALL POPREAL8(cost_part(2))
              temp_back0 = 2*(bathy_cell(ie)-xsshape(1)%topz-min8-&
&               slope_y(1)*mesh%cell(ie)%grav%y-slope_x(1)*mesh%cell(ie)&
&               %grav%x)*cost_part_back(2)
              bathy_cell_back(ie) = bathy_cell_back(ie) + temp_back0
              min8_back = -temp_back0
              mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y - &
&               slope_y(1)*temp_back0
              mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x - &
&               slope_x(1)*temp_back0
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(min8)
                y8_back = min8_back
              ELSE
                CALL POPREAL8(min8)
                y8_back = 0.0_8
              END IF
              temp1 = abs15/(xsshape(1)%xright-xsshape(1)%xcenter)
              temp0 = temp1**abs23
              abs7_back = -((1-temp0)*y8_back)
              IF (temp1 .LE. 0.0 .AND. (abs23 .EQ. 0.0 .OR. abs23 .NE. &
&                 INT(abs23))) THEN
                temp_back0 = 0.0_8
              ELSE
                temp_back0 = abs23*temp1**(abs23-1)*abs7*y8_back/(&
&                 xsshape(1)%xright-xsshape(1)%xcenter)
              END IF
              IF (temp1 .LE. 0.0) THEN
                abs23_back = 0.0_8
              ELSE
                abs23_back = temp0*LOG(temp1)*abs7*y8_back
              END IF
              abs15_back = temp_back0
              xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + temp1*&
&               temp_back0
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs23)
                xsshape_back(1)%s = xsshape_back(1)%s + abs23_back
              ELSE
                CALL POPREAL8(abs23)
                xsshape_back(1)%s = xsshape_back(1)%s - abs23_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs15)
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + &
&                 abs15_back
                mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y - &
&                 abs15_back
              ELSE
                CALL POPREAL8(abs15)
                mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y + &
&                 abs15_back
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - &
&                 abs15_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs7)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax - abs7_back
              ELSE
                CALL POPREAL8(abs7)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax + abs7_back
              END IF
            ELSE
              CALL POPREAL8(cost_part(2))
              temp_back0 = 2*(bathy_cell(ie)-xsshape(1)%topz-min7-&
&               slope_y(1)*mesh%cell(ie)%grav%y-slope_x(1)*mesh%cell(ie)&
&               %grav%x)*cost_part_back(2)
              bathy_cell_back(ie) = bathy_cell_back(ie) + temp_back0
              min7_back = -temp_back0
              mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y - &
&               slope_y(1)*temp_back0
              mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x - &
&               slope_x(1)*temp_back0
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(min7)
                y7_back = min7_back
              ELSE
                CALL POPREAL8(min7)
                y7_back = 0.0_8
              END IF
              temp1 = abs14/(xsshape(1)%xcenter-xsshape(1)%xleft)
              temp0 = temp1**abs22
              abs6_back = -((1-temp0)*y7_back)
              IF (temp1 .LE. 0.0 .AND. (abs22 .EQ. 0.0 .OR. abs22 .NE. &
&                 INT(abs22))) THEN
                temp_back0 = 0.0_8
              ELSE
                temp_back0 = abs22*temp1**(abs22-1)*abs6*y7_back/(&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
              END IF
              IF (temp1 .LE. 0.0) THEN
                abs22_back = 0.0_8
              ELSE
                abs22_back = temp0*LOG(temp1)*abs6*y7_back
              END IF
              abs14_back = temp_back0
              xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - temp1*&
&               temp_back0
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs22)
                xsshape_back(1)%s = xsshape_back(1)%s + abs22_back
              ELSE
                CALL POPREAL8(abs22)
                xsshape_back(1)%s = xsshape_back(1)%s - abs22_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs14)
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + &
&                 abs14_back
                mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y - &
&                 abs14_back
              ELSE
                CALL POPREAL8(abs14)
                mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y + &
&                 abs14_back
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - &
&                 abs14_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs6)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax - abs6_back
              ELSE
                CALL POPREAL8(abs6)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax + abs6_back
              END IF
            END IF
          END DO
        END IF
      ELSE IF (branch .EQ. 2) THEN
        IF (ALLOCATED(xsshape_back)) xsshape_back%xcenter = 0.0_8
        IF (ALLOCATED(xsshape_back)) xsshape_back%s = 0.0_8
        IF (ALLOCATED(xsshape_back)) xsshape_back%hmax = 0.0_8
        IF (ALLOCATED(bathy_cell_back)) bathy_cell_back = 0.0_8
        mesh_back%cell%grav%x = 0.0_8
        mesh_back%cell%grav%y = 0.0_8
      ELSE
        IF (ALLOCATED(xsshape_back)) xsshape_back%xcenter = 0.0_8
        IF (ALLOCATED(xsshape_back)) xsshape_back%s = 0.0_8
        IF (ALLOCATED(xsshape_back)) xsshape_back%hmax = 0.0_8
        IF (ALLOCATED(bathy_cell_back)) bathy_cell_back = 0.0_8
        mesh_back%cell%grav%x = 0.0_8
        mesh_back%cell%grav%y = 0.0_8
      END IF
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        grad_var_back%x = 0.0_8
        grad_var_back%y = 0.0_8
        DO i=mesh%nc,1,-1
          CALL POPREAL8(cost_part(2))
          grad_var_back(i)%x = grad_var_back(i)%x + 2*grad_var(i)%x*&
&           cost_part_back(2)
          grad_var_back(i)%y = grad_var_back(i)%y + 2*grad_var(i)%y*&
&           cost_part_back(2)
        END DO
      ELSE
        grad_var_back%x = 0.0_8
        grad_var_back%y = 0.0_8
      END IF
      CALL POPCONTROL2B(branch)
      IF (branch .EQ. 0) THEN
        CALL FV_CELL_GRAD_BACK(grad_var, grad_var_back, bathy_cell, &
&                        bathy_cell_back, mesh, mesh_back)
      ELSE IF (branch .EQ. 1) THEN
        bathy_temp_back = 0.0_8
        CALL FV_CELL_GRAD_BACK(grad_var, grad_var_back, bathy_temp, &
&                        bathy_temp_back, mesh, mesh_back)
        CALL POPCONTROL2B(branch)
        IF (branch .EQ. 0) THEN
          DO ie=mesh%nc,1,-1
            CALL POPCONTROL1B(branch)
            IF (branch .EQ. 0) THEN
              bathy_cell_back(ie) = bathy_cell_back(ie) + &
&               bathy_temp_back(ie)
              min2_back = -bathy_temp_back(ie)
              mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y - &
&               slope_y(1)*bathy_temp_back(ie)
              mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x - &
&               slope_x(1)*bathy_temp_back(ie)
              bathy_temp_back(ie) = 0.0_8
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                y2_back = min2_back
              ELSE
                y2_back = 0.0_8
              END IF
              temp1 = abs9/(xsshape(1)%xright-xsshape(1)%xcenter)
              temp0 = temp1**abs17
              abs1_back = -((1-temp0)*y2_back)
              IF (temp1 .LE. 0.0 .AND. (abs17 .EQ. 0.0 .OR. abs17 .NE. &
&                 INT(abs17))) THEN
                temp_back0 = 0.0_8
              ELSE
                temp_back0 = abs17*temp1**(abs17-1)*abs1*y2_back/(&
&                 xsshape(1)%xright-xsshape(1)%xcenter)
              END IF
              IF (temp1 .LE. 0.0) THEN
                abs17_back = 0.0_8
              ELSE
                abs17_back = temp0*LOG(temp1)*abs1*y2_back
              END IF
              abs9_back = temp_back0
              xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + temp1*&
&               temp_back0
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs17)
                xsshape_back(1)%s = xsshape_back(1)%s + abs17_back
              ELSE
                CALL POPREAL8(abs17)
                xsshape_back(1)%s = xsshape_back(1)%s - abs17_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs9)
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + &
&                 abs9_back
                mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x - &
&                 abs9_back
              ELSE
                CALL POPREAL8(abs9)
                mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x + &
&                 abs9_back
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - &
&                 abs9_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs1)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax - abs1_back
              ELSE
                CALL POPREAL8(abs1)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax + abs1_back
              END IF
            ELSE
              bathy_cell_back(ie) = bathy_cell_back(ie) + &
&               bathy_temp_back(ie)
              min1_back = -bathy_temp_back(ie)
              mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y - &
&               slope_y(1)*bathy_temp_back(ie)
              mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x - &
&               slope_x(1)*bathy_temp_back(ie)
              bathy_temp_back(ie) = 0.0_8
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                y1_back = min1_back
              ELSE
                y1_back = 0.0_8
              END IF
              temp0 = abs8/(xsshape(1)%xcenter-xsshape(1)%xleft)
              temp1 = temp0**abs16
              abs0_back = -((1-temp1)*y1_back)
              IF (temp0 .LE. 0.0 .AND. (abs16 .EQ. 0.0 .OR. abs16 .NE. &
&                 INT(abs16))) THEN
                temp_back = 0.0_8
              ELSE
                temp_back = abs16*temp0**(abs16-1)*abs0*y1_back/(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft)
              END IF
              IF (temp0 .LE. 0.0) THEN
                abs16_back = 0.0_8
              ELSE
                abs16_back = temp1*LOG(temp0)*abs0*y1_back
              END IF
              abs8_back = temp_back
              xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - temp0*&
&               temp_back
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs16)
                xsshape_back(1)%s = xsshape_back(1)%s + abs16_back
              ELSE
                CALL POPREAL8(abs16)
                xsshape_back(1)%s = xsshape_back(1)%s - abs16_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs8)
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + &
&                 abs8_back
                mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x - &
&                 abs8_back
              ELSE
                CALL POPREAL8(abs8)
                mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x + &
&                 abs8_back
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - &
&                 abs8_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs0)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax - abs0_back
              ELSE
                CALL POPREAL8(abs0)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax + abs0_back
              END IF
            END IF
          END DO
        ELSE IF (branch .EQ. 1) THEN
          DO ie=mesh%nc,1,-1
            CALL POPCONTROL1B(branch)
            IF (branch .EQ. 0) THEN
              bathy_cell_back(ie) = bathy_cell_back(ie) + &
&               bathy_temp_back(ie)
              min4_back = -bathy_temp_back(ie)
              mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y - &
&               slope_y(1)*bathy_temp_back(ie)
              mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x - &
&               slope_x(1)*bathy_temp_back(ie)
              bathy_temp_back(ie) = 0.0_8
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                y4_back = min4_back
              ELSE
                y4_back = 0.0_8
              END IF
              temp1 = abs11/(xsshape(1)%xright-xsshape(1)%xcenter)
              temp0 = temp1**abs19
              abs3_back = -((1-temp0)*y4_back)
              IF (temp1 .LE. 0.0 .AND. (abs19 .EQ. 0.0 .OR. abs19 .NE. &
&                 INT(abs19))) THEN
                temp_back0 = 0.0_8
              ELSE
                temp_back0 = abs19*temp1**(abs19-1)*abs3*y4_back/(&
&                 xsshape(1)%xright-xsshape(1)%xcenter)
              END IF
              IF (temp1 .LE. 0.0) THEN
                abs19_back = 0.0_8
              ELSE
                abs19_back = temp0*LOG(temp1)*abs3*y4_back
              END IF
              abs11_back = temp_back0
              xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + temp1*&
&               temp_back0
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs19)
                xsshape_back(1)%s = xsshape_back(1)%s + abs19_back
              ELSE
                CALL POPREAL8(abs19)
                xsshape_back(1)%s = xsshape_back(1)%s - abs19_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs11)
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + &
&                 abs11_back
                mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y - &
&                 abs11_back
              ELSE
                CALL POPREAL8(abs11)
                mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y + &
&                 abs11_back
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - &
&                 abs11_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs3)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax - abs3_back
              ELSE
                CALL POPREAL8(abs3)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax + abs3_back
              END IF
            ELSE
              bathy_cell_back(ie) = bathy_cell_back(ie) + &
&               bathy_temp_back(ie)
              min3_back = -bathy_temp_back(ie)
              mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y - &
&               slope_y(1)*bathy_temp_back(ie)
              mesh_back%cell(ie)%grav%x = mesh_back%cell(ie)%grav%x - &
&               slope_x(1)*bathy_temp_back(ie)
              bathy_temp_back(ie) = 0.0_8
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                y3_back = min3_back
              ELSE
                y3_back = 0.0_8
              END IF
              temp1 = abs10/(xsshape(1)%xcenter-xsshape(1)%xleft)
              temp0 = temp1**abs18
              abs2_back = -((1-temp0)*y3_back)
              IF (temp1 .LE. 0.0 .AND. (abs18 .EQ. 0.0 .OR. abs18 .NE. &
&                 INT(abs18))) THEN
                temp_back0 = 0.0_8
              ELSE
                temp_back0 = abs18*temp1**(abs18-1)*abs2*y3_back/(&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
              END IF
              IF (temp1 .LE. 0.0) THEN
                abs18_back = 0.0_8
              ELSE
                abs18_back = temp0*LOG(temp1)*abs2*y3_back
              END IF
              abs10_back = temp_back0
              xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - temp1*&
&               temp_back0
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs18)
                xsshape_back(1)%s = xsshape_back(1)%s + abs18_back
              ELSE
                CALL POPREAL8(abs18)
                xsshape_back(1)%s = xsshape_back(1)%s - abs18_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs10)
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + &
&                 abs10_back
                mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y - &
&                 abs10_back
              ELSE
                CALL POPREAL8(abs10)
                mesh_back%cell(ie)%grav%y = mesh_back%cell(ie)%grav%y + &
&                 abs10_back
                xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - &
&                 abs10_back
              END IF
              CALL POPCONTROL1B(branch)
              IF (branch .EQ. 0) THEN
                CALL POPREAL8(abs2)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax - abs2_back
              ELSE
                CALL POPREAL8(abs2)
                xsshape_back(1)%hmax = xsshape_back(1)%hmax + abs2_back
              END IF
            END IF
          END DO
        END IF
      ELSE
        mesh_back%cell%invsurf = 0.0_8
        mesh_back%edge%length = 0.0_8
        mesh_back%edge%normal%x = 0.0_8
        mesh_back%edge%normal%y = 0.0_8
      END IF
      CALL POPCONTROL2B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPINTEGER4(ad_to4)
        DO iobs=ad_to4,1,-1
          CALL POPINTEGER4(ad_to3)
          DO idiff=ad_to3,1,-1
            innovq_back(iobs)%diff(idiff) = innovq_back(iobs)%diff(idiff&
&             ) + 2*innovq(iobs)%diff(idiff)*stationq(iobs)%weight*&
&             cost_part_back(1)
          END DO
        END DO
      ELSE IF (branch .EQ. 1) THEN
        CALL POPINTEGER4(ad_to6)
        DO iobs=ad_to6,1,-1
          CALL POPREAL8(cost_part(1))
          temp_back = cost_part_back(1)/cost_part(3)
          cost_part_back(2) = cost_part_back(2) + temp_back
          cost_part_back(3) = cost_part_back(3) - cost_part(2)*temp_back&
&           /cost_part(3)
          CALL POPINTEGER4(ad_to5)
          DO idiff=ad_to5,1,-1
            CALL POPREAL8(cost_part(3))
            innovq_back(iobs+sizeq)%diff(idiff) = innovq_back(iobs+sizeq&
&             )%diff(idiff) + 2*innovq(iobs+sizeq)%diff(idiff)*&
&             cost_part_back(3)
            CALL POPREAL8(cost_part(2))
            innovq_back(iobs)%diff(idiff) = innovq_back(iobs)%diff(idiff&
&             ) + 2*innovq(iobs)%diff(idiff)*cost_part_back(2)
          END DO
          CALL POPREAL8(cost_part(2))
          cost_part_back(2) = 0.0_8
          CALL POPREAL8(cost_part(3))
          cost_part_back(3) = 0.0_8
        END DO
      END IF
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPINTEGER4(ad_to2)
        DO iobs=ad_to2,1,-1
          CALL POPINTEGER4(ad_to1)
          DO idiff=ad_to1,1,-1
            innovuv_back(iobs)%diff(idiff) = innovuv_back(iobs)%diff(&
&             idiff) + 2*innovuv(iobs)%diff(idiff)*station(iobs)%weight*&
&             cost_part_back(1)
          END DO
        END DO
      END IF
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPINTEGER4(ad_to0)
        DO iobs=ad_to0,1,-1
          CALL POPINTEGER4(ad_to)
          DO idiff=ad_to,1,-1
            innovation_back(iobs)%diff(idiff) = innovation_back(iobs)%&
&             diff(idiff) + 2*innovation(iobs)%diff(idiff)*station(iobs)&
&             %weight*cost_part_back(1)
          END DO
        END DO
      END IF
      cost_back = 0.0_8
    ELSE
      DO ii1=1,size(bc%hyd,1)
        bc_back%hyd(ii1)%q = 0.0_8
      END DO
      IF (ALLOCATED(xsshape_back)) xsshape_back%xcenter = 0.0_8
      IF (ALLOCATED(xsshape_back)) xsshape_back%s = 0.0_8
      IF (ALLOCATED(xsshape_back)) xsshape_back%hmax = 0.0_8
      IF (ALLOCATED(bathy_cell_back)) bathy_cell_back = 0.0_8
      mesh_back%cell%invsurf = 0.0_8
      mesh_back%cell%grav%x = 0.0_8
      mesh_back%cell%grav%y = 0.0_8
      mesh_back%edge%length = 0.0_8
      mesh_back%edge%normal%x = 0.0_8
      mesh_back%edge%normal%y = 0.0_8
    END IF
  END SUBROUTINE CALC_COST_FUNCTION_BACK


!  Differentiation of update_cost_function in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: *(dof.h) cost
!   with respect to varying inputs: *(dof.h) cost
!   Plus diff mem management of: dof.h:in
  SUBROUTINE UPDATE_COST_FUNCTION_BACK(dof, dof_back, cost, cost_back)
    IMPLICIT NONE
    TYPE(UNK), INTENT(IN) :: dof
    TYPE(UNK) :: dof_back
    REAL(rp), INTENT(INOUT) :: cost
    REAL(rp), INTENT(INOUT) :: cost_back
    INTEGER(ip) :: cell, pt
    REAL(rp) :: h_mean
    REAL(rp) :: h_mean_back
    INTRINSIC ALLOCATED
    INTRINSIC SIZE
    INTRINSIC REAL
    LOGICAL :: result1
    INTEGER*4 :: ad_to
    INTEGER*4 :: branch
    INTEGER*4 :: ad_to0
    IF (ALLOCATED(station)) THEN
      DO iobs=1,SIZE(station)
        result1 = TEST_DT_JUST_AFTER(station(iobs)%dt)
        IF (.NOT.result1) THEN
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHREAL8(h_mean)
          h_mean = 0._rp
          DO pt=1,SIZE(station(iobs)%pt)
            cell = station(iobs)%pt(pt)%cell
            IF (cell .LT. 0) THEN
              CALL PUSHCONTROL1B(0)
            ELSE
              h_mean = h_mean + dof%h(cell)
              CALL PUSHCONTROL1B(1)
            END IF
          END DO
          CALL PUSHINTEGER4(pt - 1)
          CALL MPI_SUM_R(h_mean)
          h_mean = h_mean/REAL(SIZE(station(iobs)%pt), 8)
          CALL PUSHCONTROL1B(1)
        END IF
      END DO
      ad_to0 = iobs - 1
      DO iobs=ad_to0,1,-1
        CALL POPCONTROL1B(branch)
        IF (branch .NE. 0) THEN
          h_mean_back = 2*h_mean*station(iobs)%weight*cost_back
          h_mean_back = h_mean_back/REAL(SIZE(station(iobs)%pt), 8)
          CALL POPINTEGER4(ad_to)
          DO pt=ad_to,1,-1
            CALL POPCONTROL1B(branch)
            IF (branch .NE. 0) THEN
              cell = station(iobs)%pt(pt)%cell
              dof_back%h(cell) = dof_back%h(cell) + h_mean_back
            END IF
          END DO
          CALL POPREAL8(h_mean)
        END IF
      END DO
    END IF
  END SUBROUTINE UPDATE_COST_FUNCTION_BACK


END MODULE M_OBS_BACK

