!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 26 Mar 2024 17:10
!
MODULE M_OBS_DIFF

  USE M_OBS
  USE M_MPI_DIFF
  USE M_TAP_VARS

CONTAINS
!  Differentiation of calc_cost_function in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: cost
!   with respect to varying inputs: *(*(bc.hyd).q) *xsshape.xcenter
!                *xsshape.s *xsshape.hmax *bathy_cell *(*innovation.diff)
!                *(*innovq.diff) *(*innovuv.diff) cost
!   Plus diff mem management of: bc.hyd:in *(bc.hyd).q:in xsshape:in
!                bathy_cell:in innovation:in *innovation.diff:in
!                innovq:in *innovq.diff:in innovuv:in *innovuv.diff:in
  SUBROUTINE CALC_COST_FUNCTION_DIFF(cost, cost_diff, mesh)
    USE M_NUMERIC_DIFF
    IMPLICIT NONE
    TYPE(MSH), INTENT(IN) :: mesh
    REAL(rp), INTENT(INOUT) :: cost
    REAL(rp), INTENT(INOUT) :: cost_diff
    REAL(rp) :: cost_part(3), filtered(4)
    REAL(rp) :: cost_part_diff(3), filtered_diff(4)
    INTEGER(ip) :: idiff, temp, sizeq
    TYPE(VEC2D), DIMENSION(mesh%nc+mesh%ncb) :: grad_var
    TYPE(VEC2D), DIMENSION(mesh%nc+mesh%ncb) :: grad_var_diff
    REAL(rp), DIMENSION(mesh%nc+mesh%ncb) :: bathy_temp
    REAL(rp), DIMENSION(mesh%nc+mesh%ncb) :: bathy_temp_diff
    INTRINSIC SIZE
    INTRINSIC ABS
    INTRINSIC MIN
    INTRINSIC SUM
    INTRINSIC SQRT
    REAL(rp) :: y1
    REAL(rp) :: y1_diff
    REAL(rp) :: y2
    REAL(rp) :: y2_diff
    REAL(rp) :: y3
    REAL(rp) :: y3_diff
    REAL(rp) :: y4
    REAL(rp) :: y4_diff
    REAL(rp) :: y5
    REAL(rp) :: y5_diff
    REAL(rp) :: y6
    REAL(rp) :: y6_diff
    REAL(rp) :: y7
    REAL(rp) :: y7_diff
    REAL(rp) :: y8
    REAL(rp) :: y8_diff
    REAL(rp) :: min1
    REAL(rp) :: min1_diff
    REAL(rp) :: min2
    REAL(rp) :: min2_diff
    REAL(rp) :: min3
    REAL(rp) :: min3_diff
    REAL(rp) :: min4
    REAL(rp) :: min4_diff
    REAL(rp) :: min5
    REAL(rp) :: min5_diff
    REAL(rp) :: min6
    REAL(rp) :: min6_diff
    REAL(rp) :: min7
    REAL(rp) :: min7_diff
    REAL(rp) :: min8
    REAL(rp) :: min8_diff
    REAL(rp) :: abs0
    REAL(rp) :: abs0_diff
    REAL(rp) :: abs1
    REAL(rp) :: abs1_diff
    REAL(rp) :: abs2
    REAL(rp) :: abs2_diff
    REAL(rp) :: abs3
    REAL(rp) :: abs3_diff
    REAL(rp) :: abs4
    REAL(rp) :: abs4_diff
    REAL(rp) :: abs5
    REAL(rp) :: abs5_diff
    REAL(rp) :: abs6
    REAL(rp) :: abs6_diff
    REAL(rp) :: abs7
    REAL(rp) :: abs7_diff
    REAL(rp) :: abs8
    REAL(rp) :: abs8_diff
    REAL(rp) :: abs9
    REAL(rp) :: abs9_diff
    REAL(rp) :: abs10
    REAL(rp) :: abs10_diff
    REAL(rp) :: abs11
    REAL(rp) :: abs11_diff
    REAL(rp) :: abs12
    REAL(rp) :: abs12_diff
    REAL(rp) :: abs13
    REAL(rp) :: abs13_diff
    REAL(rp) :: abs14
    REAL(rp) :: abs14_diff
    REAL(rp) :: abs15
    REAL(rp) :: abs15_diff
    REAL(rp) :: arg1
    REAL(rp) :: arg1_diff
    REAL(rp) :: temp0
    REAL(rp) :: temp1
    REAL(rp) :: temp_diff
    REAL(rp) :: temp_diff0
    IF (use_obs .EQ. 1) THEN
      cost_part(:) = 0._rp
      IF (use_zobs .EQ. 1) THEN
        cost_part_diff = 0.0_8
        DO iobs=1,SIZE(station)
          DO idiff=1,SIZE(innovation(iobs)%diff)
            cost_part_diff(1) = cost_part_diff(1) + station(iobs)%weight&
&             *2*innovation(iobs)%diff(idiff)*innovation_diff(iobs)%diff&
&             (idiff)
            cost_part(1) = cost_part(1) + station(iobs)%weight*&
&             innovation(iobs)%diff(idiff)**2
          END DO
        END DO
      ELSE
        cost_part_diff = 0.0_8
      END IF
      IF (use_uvobs .EQ. 1) THEN
        DO iobs=1,SIZE(station)
          DO idiff=1,SIZE(innovuv(iobs)%diff)
            cost_part_diff(1) = cost_part_diff(1) + station(iobs)%weight&
&             *2*innovuv(iobs)%diff(idiff)*innovuv_diff(iobs)%diff(idiff&
&             )
            cost_part(1) = cost_part(1) + station(iobs)%weight*innovuv(&
&             iobs)%diff(idiff)**2
          END DO
        END DO
      END IF
      IF (use_qobs .EQ. 1 .OR. use_qobs_gr4 .EQ. 1) THEN
        IF (use_nse .EQ. 0) THEN
          DO iobs=1,SIZE(stationq)
            DO idiff=1,SIZE(innovq(iobs)%diff)
              cost_part_diff(1) = cost_part_diff(1) + stationq(iobs)%&
&               weight*2*innovq(iobs)%diff(idiff)*innovq_diff(iobs)%diff&
&               (idiff)
              cost_part(1) = cost_part(1) + stationq(iobs)%weight*innovq&
&               (iobs)%diff(idiff)**2
            END DO
          END DO
        ELSE
          sizeq = SIZE(stationq)
          DO iobs=1,SIZE(stationq)
            cost_part_diff(3) = 0.0_8
            cost_part(3) = 0._rp
            cost_part_diff(2) = 0.0_8
            cost_part(2) = 0._rp
            DO idiff=1,SIZE(innovq(iobs)%diff)
              cost_part_diff(2) = cost_part_diff(2) + 2*innovq(iobs)%&
&               diff(idiff)*innovq_diff(iobs)%diff(idiff)
              cost_part(2) = cost_part(2) + innovq(iobs)%diff(idiff)**2
              temp0 = innovq(iobs+sizeq)%diff(idiff)
              cost_part_diff(3) = cost_part_diff(3) + 2*temp0*&
&               innovq_diff(iobs+sizeq)%diff(idiff)
              cost_part(3) = cost_part(3) + temp0*temp0
            END DO
            temp0 = cost_part(2)/cost_part(3)
            cost_part_diff(1) = cost_part_diff(1) + (cost_part_diff(2)-&
&             temp0*cost_part_diff(3))/cost_part(3)
            cost_part(1) = cost_part(1) + temp0
          END DO
        END IF
      END IF
      IF (regul_bathy_grad .EQ. 1) THEN
        grad_var_diff%y = 0.0_8
        grad_var_diff%x = 0.0_8
        CALL FV_CELL_GRAD_DIFF(grad_var, grad_var_diff, bathy_cell, &
&                        bathy_cell_diff, mesh)
      ELSE IF (regul_bathy_grad .EQ. 2 .AND. use_xsshp .EQ. 1) THEN
        bathy_temp(:) = 0._rp
        IF (xsshp_along_y .EQ. 1) THEN
          bathy_temp_diff = 0.0_8
          DO ie=1,mesh%nc
            IF (mesh%cell(ie)%grav%x .LE. xsshape(1)%xcenter) THEN
              IF (xsshape(1)%hmax .GE. 0.) THEN
                abs0_diff = xsshape_diff(1)%hmax
                abs0 = xsshape(1)%hmax
              ELSE
                abs0_diff = -xsshape_diff(1)%hmax
                abs0 = -xsshape(1)%hmax
              END IF
              IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                abs8_diff = -xsshape_diff(1)%xcenter
                abs8 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
              ELSE
                abs8_diff = xsshape_diff(1)%xcenter
                abs8 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape(&
&                 1)%xcenter-xsshape(1)%xleft))
              END IF
              temp0 = abs8/(xsshape(1)%xcenter-xsshape(1)%xleft)
              temp1 = temp0**xsshape(1)%s
              IF (temp0 .LE. 0.0 .AND. (xsshape(1)%s .EQ. 0.0 .OR. &
&                 xsshape(1)%s .NE. INT(xsshape(1)%s))) THEN
                temp_diff = 0.0_8
              ELSE IF (temp0 .LE. 0.0) THEN
                temp_diff = xsshape(1)%s*temp0**(xsshape(1)%s-1)*(&
&                 abs8_diff-temp0*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xcenter-xsshape(1)%xleft)
              ELSE
                temp_diff = xsshape(1)%s*temp0**(xsshape(1)%s-1)*(&
&                 abs8_diff-temp0*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) + temp1*LOG(temp0)*&
&                 xsshape_diff(1)%s
              END IF
              y1_diff = -((1-temp1)*abs0_diff-abs0*temp_diff)
              y1 = -(abs0*(1-temp1))
              IF (0._rp .GT. y1) THEN
                min1_diff = y1_diff
                min1 = y1
              ELSE
                min1 = 0._rp
                min1_diff = 0.0_8
              END IF
              bathy_temp_diff(ie) = bathy_cell_diff(ie) - min1_diff
              bathy_temp(ie) = bathy_cell(ie) - (xsshape(1)%topz+min1+&
&               slope_y(1)*mesh%cell(ie)%grav%y+slope_x(1)*mesh%cell(ie)&
&               %grav%x)
            ELSE
              IF (xsshape(1)%hmax .GE. 0.) THEN
                abs1_diff = xsshape_diff(1)%hmax
                abs1 = xsshape(1)%hmax
              ELSE
                abs1_diff = -xsshape_diff(1)%hmax
                abs1 = -xsshape(1)%hmax
              END IF
              IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                abs9_diff = -xsshape_diff(1)%xcenter
                abs9 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
              ELSE
                abs9_diff = xsshape_diff(1)%xcenter
                abs9 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape(&
&                 1)%xcenter-xsshape(1)%xleft))
              END IF
              temp1 = abs9/(xsshape(1)%xright-xsshape(1)%xcenter)
              temp0 = temp1**xsshape(1)%s
              IF (temp1 .LE. 0.0 .AND. (xsshape(1)%s .EQ. 0.0 .OR. &
&                 xsshape(1)%s .NE. INT(xsshape(1)%s))) THEN
                temp_diff0 = 0.0_8
              ELSE IF (temp1 .LE. 0.0) THEN
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs9_diff+temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xright-xsshape(1)%xcenter)
              ELSE
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs9_diff+temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xright-xsshape(1)%xcenter) + temp0*LOG(temp1)*&
&                 xsshape_diff(1)%s
              END IF
              y2_diff = -((1-temp0)*abs1_diff-abs1*temp_diff0)
              y2 = -(abs1*(1-temp0))
              IF (0._rp .GT. y2) THEN
                min2_diff = y2_diff
                min2 = y2
              ELSE
                min2 = 0._rp
                min2_diff = 0.0_8
              END IF
              bathy_temp_diff(ie) = bathy_cell_diff(ie) - min2_diff
              bathy_temp(ie) = bathy_cell(ie) - (xsshape(1)%topz+min2+&
&               slope_y(1)*mesh%cell(ie)%grav%y+slope_x(1)*mesh%cell(ie)&
&               %grav%x)
            END IF
          END DO
        ELSE IF (xsshp_along_x .EQ. 1) THEN
          bathy_temp_diff = 0.0_8
          DO ie=1,mesh%nc
            IF (mesh%cell(ie)%grav%y .LE. xsshape(1)%xcenter) THEN
              IF (xsshape(1)%hmax .GE. 0.) THEN
                abs2_diff = xsshape_diff(1)%hmax
                abs2 = xsshape(1)%hmax
              ELSE
                abs2_diff = -xsshape_diff(1)%hmax
                abs2 = -xsshape(1)%hmax
              END IF
              IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                abs10_diff = -xsshape_diff(1)%xcenter
                abs10 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
              ELSE
                abs10_diff = xsshape_diff(1)%xcenter
                abs10 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft))
              END IF
              temp1 = abs10/(xsshape(1)%xcenter-xsshape(1)%xleft)
              temp0 = temp1**xsshape(1)%s
              IF (temp1 .LE. 0.0 .AND. (xsshape(1)%s .EQ. 0.0 .OR. &
&                 xsshape(1)%s .NE. INT(xsshape(1)%s))) THEN
                temp_diff0 = 0.0_8
              ELSE IF (temp1 .LE. 0.0) THEN
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs10_diff-temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xcenter-xsshape(1)%xleft)
              ELSE
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs10_diff-temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) + temp0*LOG(temp1)*&
&                 xsshape_diff(1)%s
              END IF
              y3_diff = -((1-temp0)*abs2_diff-abs2*temp_diff0)
              y3 = -(abs2*(1-temp0))
              IF (0._rp .GT. y3) THEN
                min3_diff = y3_diff
                min3 = y3
              ELSE
                min3 = 0._rp
                min3_diff = 0.0_8
              END IF
              bathy_temp_diff(ie) = bathy_cell_diff(ie) - min3_diff
              bathy_temp(ie) = bathy_cell(ie) - (xsshape(1)%topz+min3+&
&               slope_y(1)*mesh%cell(ie)%grav%y+slope_x(1)*mesh%cell(ie)&
&               %grav%x)
            ELSE
              IF (xsshape(1)%hmax .GE. 0.) THEN
                abs3_diff = xsshape_diff(1)%hmax
                abs3 = xsshape(1)%hmax
              ELSE
                abs3_diff = -xsshape_diff(1)%hmax
                abs3 = -xsshape(1)%hmax
              END IF
              IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                abs11_diff = -xsshape_diff(1)%xcenter
                abs11 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
              ELSE
                abs11_diff = xsshape_diff(1)%xcenter
                abs11 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft))
              END IF
              temp1 = abs11/(xsshape(1)%xright-xsshape(1)%xcenter)
              temp0 = temp1**xsshape(1)%s
              IF (temp1 .LE. 0.0 .AND. (xsshape(1)%s .EQ. 0.0 .OR. &
&                 xsshape(1)%s .NE. INT(xsshape(1)%s))) THEN
                temp_diff0 = 0.0_8
              ELSE IF (temp1 .LE. 0.0) THEN
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs11_diff+temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xright-xsshape(1)%xcenter)
              ELSE
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs11_diff+temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xright-xsshape(1)%xcenter) + temp0*LOG(temp1)*&
&                 xsshape_diff(1)%s
              END IF
              y4_diff = -((1-temp0)*abs3_diff-abs3*temp_diff0)
              y4 = -(abs3*(1-temp0))
              IF (0._rp .GT. y4) THEN
                min4_diff = y4_diff
                min4 = y4
              ELSE
                min4 = 0._rp
                min4_diff = 0.0_8
              END IF
              bathy_temp_diff(ie) = bathy_cell_diff(ie) - min4_diff
              bathy_temp(ie) = bathy_cell(ie) - (xsshape(1)%topz+min4+&
&               slope_y(1)*mesh%cell(ie)%grav%y+slope_x(1)*mesh%cell(ie)&
&               %grav%x)
            END IF
          END DO
        ELSE
          bathy_temp_diff = 0.0_8
        END IF
        grad_var_diff%y = 0.0_8
        grad_var_diff%x = 0.0_8
        CALL FV_CELL_GRAD_DIFF(grad_var, grad_var_diff, bathy_temp, &
&                        bathy_temp_diff, mesh)
      ELSE
        grad_var_diff%x = 0.0_8
        grad_var_diff%y = 0.0_8
      END IF
      IF (regul_bathy_grad .NE. 0) THEN
        DO i=1,mesh%nc
          cost_part_diff(2) = cost_part_diff(2) + 2*grad_var(i)%x*&
&           grad_var_diff(i)%x + 2*grad_var(i)%y*grad_var_diff(i)%y
          cost_part(2) = cost_part(2) + (grad_var(i)%x**2+grad_var(i)%y&
&           **2)
        END DO
        CALL MPI_SUM_R(cost_part(2))
      END IF
      IF (regul_bathy_shape .EQ. 1 .AND. use_xsshp .EQ. 1) THEN
        IF (xsshp_along_x .EQ. 1) THEN
          DO ie=1,mesh%nc
            IF (mesh%cell(ie)%grav%x .LE. xsshape(1)%xcenter) THEN
              IF (xsshape(1)%hmax .GE. 0.) THEN
                abs4_diff = xsshape_diff(1)%hmax
                abs4 = xsshape(1)%hmax
              ELSE
                abs4_diff = -xsshape_diff(1)%hmax
                abs4 = -xsshape(1)%hmax
              END IF
              IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                abs12_diff = -xsshape_diff(1)%xcenter
                abs12 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
              ELSE
                abs12_diff = xsshape_diff(1)%xcenter
                abs12 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft))
              END IF
              temp1 = abs12/(xsshape(1)%xcenter-xsshape(1)%xleft)
              temp0 = temp1**xsshape(1)%s
              IF (temp1 .LE. 0.0 .AND. (xsshape(1)%s .EQ. 0.0 .OR. &
&                 xsshape(1)%s .NE. INT(xsshape(1)%s))) THEN
                temp_diff0 = 0.0_8
              ELSE IF (temp1 .LE. 0.0) THEN
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs12_diff-temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xcenter-xsshape(1)%xleft)
              ELSE
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs12_diff-temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) + temp0*LOG(temp1)*&
&                 xsshape_diff(1)%s
              END IF
              y5_diff = -((1-temp0)*abs4_diff-abs4*temp_diff0)
              y5 = -(abs4*(1-temp0))
              IF (0._rp .GT. y5) THEN
                min5_diff = y5_diff
                min5 = y5
              ELSE
                min5 = 0._rp
                min5_diff = 0.0_8
              END IF
              temp1 = bathy_cell(ie) - slope_y(1)*mesh%cell(ie)%grav%y -&
&               slope_x(1)*mesh%cell(ie)%grav%x - xsshape(1)%topz - min5
              cost_part_diff(2) = cost_part_diff(2) + 2*temp1*(&
&               bathy_cell_diff(ie)-min5_diff)
              cost_part(2) = cost_part(2) + temp1*temp1
            ELSE
              IF (xsshape(1)%hmax .GE. 0.) THEN
                abs5_diff = xsshape_diff(1)%hmax
                abs5 = xsshape(1)%hmax
              ELSE
                abs5_diff = -xsshape_diff(1)%hmax
                abs5 = -xsshape(1)%hmax
              END IF
              IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                abs13_diff = -xsshape_diff(1)%xcenter
                abs13 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
              ELSE
                abs13_diff = xsshape_diff(1)%xcenter
                abs13 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft))
              END IF
              temp1 = abs13/(xsshape(1)%xright-xsshape(1)%xcenter)
              temp0 = temp1**xsshape(1)%s
              IF (temp1 .LE. 0.0 .AND. (xsshape(1)%s .EQ. 0.0 .OR. &
&                 xsshape(1)%s .NE. INT(xsshape(1)%s))) THEN
                temp_diff0 = 0.0_8
              ELSE IF (temp1 .LE. 0.0) THEN
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs13_diff+temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xright-xsshape(1)%xcenter)
              ELSE
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs13_diff+temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xright-xsshape(1)%xcenter) + temp0*LOG(temp1)*&
&                 xsshape_diff(1)%s
              END IF
              y6_diff = -((1-temp0)*abs5_diff-abs5*temp_diff0)
              y6 = -(abs5*(1-temp0))
              IF (0._rp .GT. y6) THEN
                min6_diff = y6_diff
                min6 = y6
              ELSE
                min6 = 0._rp
                min6_diff = 0.0_8
              END IF
              temp1 = bathy_cell(ie) - slope_y(1)*mesh%cell(ie)%grav%y -&
&               slope_x(1)*mesh%cell(ie)%grav%x - xsshape(1)%topz - min6
              cost_part_diff(2) = cost_part_diff(2) + 2*temp1*(&
&               bathy_cell_diff(ie)-min6_diff)
              cost_part(2) = cost_part(2) + temp1*temp1
            END IF
          END DO
          CALL MPI_SUM_R(cost_part(2))
        ELSE IF (xsshp_along_y .EQ. 1) THEN
          DO ie=1,mesh%nc
            IF (mesh%cell(ie)%grav%y .LE. xsshape(1)%xcenter) THEN
              IF (xsshape(1)%hmax .GE. 0.) THEN
                abs6_diff = xsshape_diff(1)%hmax
                abs6 = xsshape(1)%hmax
              ELSE
                abs6_diff = -xsshape_diff(1)%hmax
                abs6 = -xsshape(1)%hmax
              END IF
              IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                abs14_diff = -xsshape_diff(1)%xcenter
                abs14 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
              ELSE
                abs14_diff = xsshape_diff(1)%xcenter
                abs14 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft))
              END IF
              temp1 = abs14/(xsshape(1)%xcenter-xsshape(1)%xleft)
              temp0 = temp1**xsshape(1)%s
              IF (temp1 .LE. 0.0 .AND. (xsshape(1)%s .EQ. 0.0 .OR. &
&                 xsshape(1)%s .NE. INT(xsshape(1)%s))) THEN
                temp_diff0 = 0.0_8
              ELSE IF (temp1 .LE. 0.0) THEN
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs14_diff-temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xcenter-xsshape(1)%xleft)
              ELSE
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs14_diff-temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) + temp0*LOG(temp1)*&
&                 xsshape_diff(1)%s
              END IF
              y7_diff = -((1-temp0)*abs6_diff-abs6*temp_diff0)
              y7 = -(abs6*(1-temp0))
              IF (0._rp .GT. y7) THEN
                min7_diff = y7_diff
                min7 = y7
              ELSE
                min7 = 0._rp
                min7_diff = 0.0_8
              END IF
              temp1 = bathy_cell(ie) - slope_y(1)*mesh%cell(ie)%grav%y -&
&               slope_x(1)*mesh%cell(ie)%grav%x - xsshape(1)%topz - min7
              cost_part_diff(2) = cost_part_diff(2) + 2*temp1*(&
&               bathy_cell_diff(ie)-min7_diff)
              cost_part(2) = cost_part(2) + temp1*temp1
            ELSE
              IF (xsshape(1)%hmax .GE. 0.) THEN
                abs7_diff = xsshape_diff(1)%hmax
                abs7 = xsshape(1)%hmax
              ELSE
                abs7_diff = -xsshape_diff(1)%hmax
                abs7 = -xsshape(1)%hmax
              END IF
              IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&                 xcenter-xsshape(1)%xleft) .GE. 0.) THEN
                abs15_diff = -xsshape_diff(1)%xcenter
                abs15 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (&
&                 xsshape(1)%xcenter-xsshape(1)%xleft)
              ELSE
                abs15_diff = xsshape_diff(1)%xcenter
                abs15 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape&
&                 (1)%xcenter-xsshape(1)%xleft))
              END IF
              temp1 = abs15/(xsshape(1)%xright-xsshape(1)%xcenter)
              temp0 = temp1**xsshape(1)%s
              IF (temp1 .LE. 0.0 .AND. (xsshape(1)%s .EQ. 0.0 .OR. &
&                 xsshape(1)%s .NE. INT(xsshape(1)%s))) THEN
                temp_diff0 = 0.0_8
              ELSE IF (temp1 .LE. 0.0) THEN
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs15_diff+temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xright-xsshape(1)%xcenter)
              ELSE
                temp_diff0 = xsshape(1)%s*temp1**(xsshape(1)%s-1)*(&
&                 abs15_diff+temp1*xsshape_diff(1)%xcenter)/(xsshape(1)%&
&                 xright-xsshape(1)%xcenter) + temp0*LOG(temp1)*&
&                 xsshape_diff(1)%s
              END IF
              y8_diff = -((1-temp0)*abs7_diff-abs7*temp_diff0)
              y8 = -(abs7*(1-temp0))
              IF (0._rp .GT. y8) THEN
                min8_diff = y8_diff
                min8 = y8
              ELSE
                min8 = 0._rp
                min8_diff = 0.0_8
              END IF
              temp1 = bathy_cell(ie) - slope_y(1)*mesh%cell(ie)%grav%y -&
&               slope_x(1)*mesh%cell(ie)%grav%x - xsshape(1)%topz - min8
              cost_part_diff(2) = cost_part_diff(2) + 2*temp1*(&
&               bathy_cell_diff(ie)-min8_diff)
              cost_part(2) = cost_part(2) + temp1*temp1
            END IF
          END DO
        END IF
      END IF
      cost_part_diff(2) = regul_bathy*cost_part_diff(2)
      cost_part(2) = cost_part(2)*regul_bathy
      filtered_diff = 0.0_8
      DO k=1,bc%nb_in
        filtered_diff(1) = bc_diff%hyd(k)%q(1)
        filtered(1) = bc%hyd(k)%q(1)
        DO i=2,SIZE(bc%hyd(k)%q(:))-3
          filtered_diff(2) = filtered_diff(1) + 0.2_rp*(bc_diff%hyd(k)%q&
&           (i)-filtered_diff(1))
          filtered(2) = filtered(1) + 0.2_rp*(bc%hyd(k)%q(i)-filtered(1)&
&           )
          filtered_diff(3) = filtered_diff(2) + 0.2_rp*(bc_diff%hyd(k)%q&
&           (i+1)-filtered_diff(2))
          filtered(3) = filtered(2) + 0.2_rp*(bc%hyd(k)%q(i+1)-filtered(&
&           2))
          filtered_diff(4) = filtered_diff(3) + 0.2_rp*(bc_diff%hyd(k)%q&
&           (i+2)-filtered_diff(3))
          filtered(4) = filtered(3) + 0.2_rp*(bc%hyd(k)%q(i+2)-filtered(&
&           3))
          temp1 = bc%hyd(k)%q(i) - filtered(4)
          cost_part_diff(3) = cost_part_diff(3) + 2*temp1*(bc_diff%hyd(k&
&           )%q(i)-filtered_diff(4))
          cost_part(3) = cost_part(3) + temp1*temp1
          filtered_diff(1) = filtered_diff(4)
          filtered(1) = filtered(4)
        END DO
      END DO
      cost_part_diff(3) = regul_hydrograph*cost_part_diff(3)
      cost_part(3) = cost_part(3)*regul_hydrograph
      cost_diff = SUM(cost_part_diff)
      cost = SUM(cost_part)
    END IF
    arg1_diff = 2*cost*cost_diff
    arg1 = cost**2
    temp1 = SQRT(arg1)
    IF (arg1 .EQ. 0.0) THEN
      cost_diff = 0.0_8
    ELSE
      cost_diff = arg1_diff/(2.0*temp1)
    END IF
    cost = temp1
    WRITE(*, *) 'cost', cost
  END SUBROUTINE CALC_COST_FUNCTION_DIFF


!  Differentiation of update_cost_function in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: cost
!   with respect to varying inputs: *(dof.h) cost
!   Plus diff mem management of: dof.h:in
  SUBROUTINE UPDATE_COST_FUNCTION_DIFF(dof, dof_diff, cost, cost_diff)
    IMPLICIT NONE
    TYPE(UNK), INTENT(IN) :: dof
    TYPE(UNK), INTENT(IN) :: dof_diff
    REAL(rp), INTENT(INOUT) :: cost
    REAL(rp), INTENT(INOUT) :: cost_diff
    INTEGER(ip) :: cell, pt
    REAL(rp) :: h_mean
    REAL(rp) :: h_mean_diff
    INTRINSIC ALLOCATED
    INTRINSIC SIZE
    INTRINSIC REAL
    LOGICAL :: result1
    INTEGER :: arg1
    REAL*8 :: temp
    IF (.NOT.ALLOCATED(station)) THEN
      RETURN
    ELSE
      DO iobs=1,SIZE(station)
        result1 = TEST_DT_JUST_AFTER(station(iobs)%dt)
        IF (result1) THEN
          h_mean = 0._rp
          h_mean_diff = 0.0_8
          DO pt=1,SIZE(station(iobs)%pt)
            cell = station(iobs)%pt(pt)%cell
            IF (cell .GE. 0) THEN
              h_mean_diff = h_mean_diff + dof_diff%h(cell)
              h_mean = h_mean + dof%h(cell)
            END IF
          END DO
          CALL MPI_SUM_R(h_mean)
          arg1 = SIZE(station(iobs)%pt)
          temp = REAL(arg1, 8)
          h_mean_diff = h_mean_diff/temp
          h_mean = h_mean/temp
          cost_diff = cost_diff + station(iobs)%weight*2*h_mean*&
&           h_mean_diff
          cost = cost + station(iobs)%weight*h_mean**2
        END IF
      END DO
    END IF
  END SUBROUTINE UPDATE_COST_FUNCTION_DIFF


END MODULE M_OBS_DIFF

