!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 26 Mar 2024 17:10
!
!  Differentiation of run_model in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: *(*innovation.diff) *(*innovq.diff)
!                *(*innovuv.diff) *(dof.h) *(dof.u) *(dof.v) cost
!   with respect to varying inputs: *(infil.ga).psif *(infil.ga).ks
!                *(infil.ga).deltatheta *(infil.scs).lambdacn *(infil.scs).cn
!                *manning *ptf.kappa *(*(bc.hyd).t) *(*(bc.hyd).q)
!                *(*(bc.rat).h) *(*(bc.rat).q) *(*(bc.rain).t)
!                *(*(bc.rain).q) *xsshape.xcenter *xsshape.s *xsshape.hmax
!                *bathy_cell *manning_beta *(dof0.h) *(dof0.u)
!                *(dof0.v)
!   RW status of diff variables: tc:(loc) *(infil.ga).psif:out
!                *(infil.ga).ks:out *(infil.ga).deltatheta:out
!                *(infil.scs).lambdacn:out *(infil.scs).cn:out
!                *manning:out *ptf.kappa:out *(bc.inflow):(loc)
!                *(bc.outflow):(loc) *(*(bc.hyd).t):out *(*(bc.hyd).q):out
!                *(*(bc.rat).h):out *(*(bc.rat).q):out *(bc.rat).zout:(loc)
!                *(*(bc.rain).t):out *(*(bc.rain).q):out *(bc.rain).qin:(loc)
!                *(bc.rain).cumul:(loc) *(bc.sum_mass_flux):(loc)
!                *xsshape.xcenter:out *xsshape.s:out *xsshape.hmax:out
!                *bathy_cell:out *manning_beta:out *(*innovation.diff):in-killed
!                *(*innovq.diff):in-killed *(*innovw.diff):(loc)
!                *(*innovuv.diff):in-killed dof.h:(loc) *(dof.h):in-killed
!                dof.u:(loc) *(dof.u):in-killed dof.v:(loc) *(dof.v):in-killed
!                *(dof.infil):(loc) cost:in-killed dof0.h:(loc)
!                *(dof0.h):out dof0.u:(loc) *(dof0.u):out dof0.v:(loc)
!                *(dof0.v):out
!   Plus diff mem management of: infil.ga:in infil.scs:in manning:in
!                ptf:in bc.inflow:in bc.outflow:in bc.hyd:in *(bc.hyd).t:in
!                *(bc.hyd).q:in bc.rat:in *(bc.rat).h:in *(bc.rat).q:in
!                bc.hpresc:in *(bc.hpresc).t:in *(bc.hpresc).h:in
!                bc.zspresc:in *(bc.zspresc).t:in *(bc.zspresc).z:in
!                bc.rain:in *(bc.rain).t:in *(bc.rain).q:in bc.sum_mass_flux:in
!                xsshape:in bathy_cell:in manning_beta:in innovation:in
!                *innovation.diff:in innovq:in *innovq.diff:in
!                innovuv:in *innovuv.diff:in dof.h:in dof.u:in
!                dof.v:in dof.infil:in dof0.h:in dof0.u:in dof0.v:in
SUBROUTINE RUN_MODEL_BACK(mesh, dof0, dof0_back, dof, dof_back, cost, &
& cost_back)
  USE M_COMMON ! Replaced by Perl Script
  USE M_LINEAR_ALGEBRA ! Replaced by Perl Script
  USE M_MESH ! Replaced by Perl Script
  USE M_MPI ! Replaced by Perl Script
  USE M_NUMERIC ! Replaced by Perl Script
  USE M_NUMERIC_BACK
  USE M_MODEL ! Replaced by Perl Script
  USE M_OBS ! Replaced by Perl Script
  USE M_OBS_BACK

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  TYPE(MSH), INTENT(INOUT) :: mesh
  TYPE(UNK), INTENT(INOUT) :: dof0
  TYPE(UNK), INTENT(INOUT) :: dof0_back
  TYPE(UNK), INTENT(INOUT) :: dof
  TYPE(UNK), INTENT(INOUT) :: dof_back
  REAL(rp) :: cost
  REAL(rp) :: cost_back
  INTEGER(ip) :: sub_nt, ir, il
  REAL(rp) :: bathy_temp
  REAL(rp) :: bathy_temp_back
  REAL(rp) :: ks_ubound, ks_lbound, z, lambda, shift
  INTRINSIC ABS
  INTRINSIC MIN
  INTRINSIC SIZE
  INTRINSIC MAX
  REAL(rp) :: y1
  REAL(rp) :: y1_back
  REAL(rp) :: y2
  REAL(rp) :: y2_back
  REAL(rp) :: y3
  REAL(rp) :: y3_back
  REAL(rp) :: y4
  REAL(rp) :: y4_back
  REAL(rp) :: min1
  REAL(rp) :: min1_back
  REAL(rp) :: min2
  REAL(rp) :: min2_back
  REAL(rp) :: min3
  REAL(rp) :: min3_back
  REAL(rp) :: min4
  REAL(rp) :: min4_back
  REAL(rp) :: abs0
  REAL(rp) :: abs0_back
  REAL(rp) :: abs1
  REAL(rp) :: abs1_back
  REAL(rp) :: abs2
  REAL(rp) :: abs2_back
  REAL(rp) :: abs3
  REAL(rp) :: abs3_back
  REAL(rp) :: abs4
  REAL(rp) :: abs4_back
  REAL(rp) :: abs5
  REAL(rp) :: abs5_back
  REAL(rp) :: abs6
  REAL(rp) :: abs6_back
  REAL(rp) :: abs7
  REAL(rp) :: abs7_back
  REAL(rp) :: temp
  REAL(rp) :: temp0
  REAL(rp) :: temp1
  REAL(rp) :: temp_back
  REAL(rp) :: temp_back0
  INTEGER*4 :: branch
  INTEGER*4 :: ad_to
  INTEGER :: ad_count
  INTEGER :: i0
  INTEGER :: ii1
  IF (use_xsshp .EQ. 1) THEN
    IF (xsshp_along_y .EQ. 1) THEN
      DO ie=1,mesh%nc
        bathy_temp = bathy_cell(ie)
        IF (mesh%cell(ie)%grav%x .LE. xsshape(1)%xcenter) THEN
          IF (xsshape(1)%hmax .GE. 0.) THEN
            CALL PUSHREAL8(abs0)
            abs0 = xsshape(1)%hmax
            CALL PUSHCONTROL1B(1)
          ELSE
            CALL PUSHREAL8(abs0)
            abs0 = -xsshape(1)%hmax
            CALL PUSHCONTROL1B(0)
          END IF
          IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&             xcenter-xsshape(1)%xleft) .GE. 0.) THEN
            CALL PUSHREAL8(abs4)
            abs4 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)&
&             %xcenter-xsshape(1)%xleft)
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHREAL8(abs4)
            abs4 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape(1)%&
&             xcenter-xsshape(1)%xleft))
            CALL PUSHCONTROL1B(1)
          END IF
          y1 = -(abs0*(1-(abs4/(xsshape(1)%xcenter-xsshape(1)%xleft))**&
&           xsshape(1)%s))
          IF (0._rp .GT. y1) THEN
            min1 = y1
            CALL PUSHCONTROL1B(0)
          ELSE
            min1 = 0._rp
            CALL PUSHCONTROL1B(1)
          END IF
          bathy_cell(ie) = xsshape(1)%topz + min1 + bathy_temp + slope_y&
&           (1)*mesh%cell(ie)%grav%y + slope_x(1)*mesh%cell(ie)%grav%x
          CALL PUSHCONTROL1B(1)
        ELSE
          IF (xsshape(1)%hmax .GE. 0.) THEN
            CALL PUSHREAL8(abs1)
            abs1 = xsshape(1)%hmax
            CALL PUSHCONTROL1B(1)
          ELSE
            CALL PUSHREAL8(abs1)
            abs1 = -xsshape(1)%hmax
            CALL PUSHCONTROL1B(0)
          END IF
          IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&             xcenter-xsshape(1)%xleft) .GE. 0.) THEN
            CALL PUSHREAL8(abs5)
            abs5 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)&
&             %xcenter-xsshape(1)%xleft)
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHREAL8(abs5)
            abs5 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape(1)%&
&             xcenter-xsshape(1)%xleft))
            CALL PUSHCONTROL1B(1)
          END IF
          y2 = -(abs1*(1-(abs5/(xsshape(1)%xright-xsshape(1)%xcenter))**&
&           xsshape(1)%s))
          IF (0._rp .GT. y2) THEN
            min2 = y2
            CALL PUSHCONTROL1B(0)
          ELSE
            min2 = 0._rp
            CALL PUSHCONTROL1B(1)
          END IF
          bathy_cell(ie) = xsshape(1)%topz + min2 + bathy_temp + slope_y&
&           (1)*mesh%cell(ie)%grav%y + slope_x(1)*mesh%cell(ie)%grav%x
          CALL PUSHCONTROL1B(0)
        END IF
      END DO
      CALL PUSHCONTROL2B(0)
    ELSE IF (xsshp_along_x .EQ. 1) THEN
      DO ie=1,mesh%nc
        bathy_temp = bathy_cell(ie)
        IF (mesh%cell(ie)%grav%y .LE. xsshape(1)%xcenter) THEN
          IF (xsshape(1)%hmax .GE. 0.) THEN
            CALL PUSHREAL8(abs2)
            abs2 = xsshape(1)%hmax
            CALL PUSHCONTROL1B(1)
          ELSE
            CALL PUSHREAL8(abs2)
            abs2 = -xsshape(1)%hmax
            CALL PUSHCONTROL1B(0)
          END IF
          IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&             xcenter-xsshape(1)%xleft) .GE. 0.) THEN
            CALL PUSHREAL8(abs6)
            abs6 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)&
&             %xcenter-xsshape(1)%xleft)
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHREAL8(abs6)
            abs6 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape(1)%&
&             xcenter-xsshape(1)%xleft))
            CALL PUSHCONTROL1B(1)
          END IF
          y3 = -(abs2*(1-(abs6/(xsshape(1)%xcenter-xsshape(1)%xleft))**&
&           xsshape(1)%s))
          IF (0._rp .GT. y3) THEN
            min3 = y3
            CALL PUSHCONTROL1B(0)
          ELSE
            min3 = 0._rp
            CALL PUSHCONTROL1B(1)
          END IF
          bathy_cell(ie) = xsshape(1)%topz + min3 + bathy_temp + slope_y&
&           (1)*mesh%cell(ie)%grav%y + slope_x(1)*mesh%cell(ie)%grav%x
          CALL PUSHCONTROL1B(1)
        ELSE
          IF (xsshape(1)%hmax .GE. 0.) THEN
            CALL PUSHREAL8(abs3)
            abs3 = xsshape(1)%hmax
            CALL PUSHCONTROL1B(1)
          ELSE
            CALL PUSHREAL8(abs3)
            abs3 = -xsshape(1)%hmax
            CALL PUSHCONTROL1B(0)
          END IF
          IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&             xcenter-xsshape(1)%xleft) .GE. 0.) THEN
            CALL PUSHREAL8(abs7)
            abs7 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)&
&             %xcenter-xsshape(1)%xleft)
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHREAL8(abs7)
            abs7 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape(1)%&
&             xcenter-xsshape(1)%xleft))
            CALL PUSHCONTROL1B(1)
          END IF
          y4 = -(abs3*(1-(abs7/(xsshape(1)%xright-xsshape(1)%xcenter))**&
&           xsshape(1)%s))
          IF (0._rp .GT. y4) THEN
            min4 = y4
            CALL PUSHCONTROL1B(0)
          ELSE
            min4 = 0._rp
            CALL PUSHCONTROL1B(1)
          END IF
          bathy_cell(ie) = xsshape(1)%topz + min4 + bathy_temp + slope_y&
&           (1)*mesh%cell(ie)%grav%y + slope_x(1)*mesh%cell(ie)%grav%x
          CALL PUSHCONTROL1B(0)
        END IF
      END DO
      CALL PUSHCONTROL2B(1)
    ELSE
      CALL PUSHCONTROL2B(2)
    END IF
  ELSE
    CALL PUSHCONTROL2B(3)
  END IF
  IF (use_ptf .EQ. 1) THEN
    IF (bc_infil .EQ. 1) THEN
      DO i=1,SIZE(phys_desc%soil)
!kg/m2 to m
        infil%ga(i)%ks = 25.4_rp/3600._rp*10._rp**(-ptf(phys_desc%&
&         ptf_land(i))%kappa(7)-ptf(phys_desc%ptf_land(i))%kappa(8)*&
&         phys_desc%soil(i)%clay+ptf(phys_desc%ptf_land(i))%kappa(9)*&
&         phys_desc%soil(i)%sand)/1000._rp
      END DO
      CALL PUSHINTEGER4(i - 1)
      CALL PUSHCONTROL2B(0)
    ELSE IF (bc_infil .EQ. 2) THEN
      CALL PUSHCONTROL2B(1)
      CALL STOPPING_PROGRAM_SUB('PTF for SCS-CN method not defined yet')
    ELSE
      CALL PUSHCONTROL2B(1)
    END IF
  ELSE
    CALL PUSHCONTROL2B(2)
  END IF
  INQUIRE(file='zs_init.txt', exist=file_exist(1)) 
  IF (file_exist(1)) THEN
    DO i=1,mesh%nc
      IF (0._rp .LT. dof0%h(i) - bathy_cell(i) + slope_y(1)*mesh%cell(i)&
&         %grav%y + slope_x(1)*mesh%cell(i)%grav%x) THEN
        dof0%h(i) = dof0%h(i) - bathy_cell(i) + slope_y(1)*mesh%cell(i)%&
&         grav%y + slope_x(1)*mesh%cell(i)%grav%x
        CALL PUSHCONTROL1B(0)
      ELSE
        dof0%h(i) = 0._rp
        CALL PUSHCONTROL1B(1)
      END IF
    END DO
    CALL PUSHCONTROL1B(0)
  ELSE
    CALL PUSHCONTROL1B(1)
  END IF
  dof%h = dof0%h
  dof%u = dof0%u
  dof%v = dof0%v
  tc = tc0
  nt = nt0
  IF (use_obs .EQ. 1) THEN
    IF (use_zobs .EQ. 1) innovation(:)%ind_t = 1_ip
    IF (use_uvobs .EQ. 1) innovuv(:)%ind_t = 1_ip
    IF (use_qobs .EQ. 1 .OR. use_qobs_gr4 .EQ. 1) THEN
      CALL PUSHCONTROL1B(0)
      innovq(:)%ind_t = 1_ip
    ELSE
      CALL PUSHCONTROL1B(0)
    END IF
  ELSE
    CALL PUSHCONTROL1B(1)
  END IF
  IF (use_qobs .EQ. 1 .OR. use_qobs_gr4 .EQ. 1) innovq(:)%ind_t = 1_ip
  cost = 0._rp
  end_time_loop = .false.
  ad_count = 0
  DO WHILE (.NOT.end_time_loop)
    CALL PUSHREAL8ARRAY(dof%infil, size(dof%infil,1))
    CALL PUSHREAL8ARRAY(dof%v, size(dof%v,1))
    CALL PUSHREAL8ARRAY(dof%u, size(dof%u,1))
    CALL PUSHREAL8ARRAY(dof%h, size(dof%h,1))
    IF (ALLOCATED(innovuv)) THEN
      CALL PUSHINTEGER4ARRAY(innovuv%ind_t, size(innovuv,1))
      CALL PUSHCONTROL1B(1)
    ELSE
      CALL PUSHCONTROL1B(0)
    END IF
    IF (ALLOCATED(innovq)) THEN
      CALL PUSHINTEGER4ARRAY(innovq%ind_t, size(innovq,1))
      CALL PUSHCONTROL1B(1)
    ELSE
      CALL PUSHCONTROL1B(0)
    END IF
    IF (ALLOCATED(innovation)) THEN
      CALL PUSHINTEGER4ARRAY(innovation%ind_t, size(innovation,1))
      CALL PUSHCONTROL1B(1)
    ELSE
      CALL PUSHCONTROL1B(0)
    END IF
    IF (ALLOCATED(bathy_cell)) THEN
      CALL PUSHREAL8ARRAY(bathy_cell, size(bathy_cell,1))
      CALL PUSHCONTROL1B(1)
    ELSE
      CALL PUSHCONTROL1B(0)
    END IF
    CALL PUSHREAL8ARRAY(bc%sum_mass_flux, size(bc%sum_mass_flux,1))
    CALL PUSHREAL8ARRAY(bc%rain%cumul, size(bc%rain,1))
    CALL PUSHREAL8ARRAY(bc%rain%qin, size(bc%rain,1))
    CALL PUSHREAL8ARRAY(bc%rat%zout, size(bc%rat,1))
    CALL PUSHREAL8ARRAY(bc%outflow, size(bc%outflow,1))
    CALL PUSHREAL8ARRAY(bc%inflow, size(bc%inflow,1))
    CALL PUSHREAL8(tc)
    CALL PUSHBOOLEAN(end_time_loop)
    CALL PUSHINTEGER4(nt)
    CALL PUSHREAL8(dt)
    CALL SUB_RUN_MODEL()
    ad_count = ad_count + 1
  END DO
  CALL PUSHINTEGER4(ad_count)
  WRITE(*, *) 'call calc_cost_function( cost , mesh )'
  CALL PUSHREAL8(cost)
  CALL CALC_COST_FUNCTION(cost, mesh)
  CALL POPREAL8(cost)
  CALL CALC_COST_FUNCTION_BACK(cost, cost_back, mesh)
  infil_back%ga%psif = 0.0_8
  infil_back%ga%ks = 0.0_8
  infil_back%ga%deltatheta = 0.0_8
  infil_back%scs%lambdacn = 0.0_8
  infil_back%scs%cn = 0.0_8
  IF (ALLOCATED(manning_back)) manning_back = 0.0_8
  bc_back%inflow = 0.0_8
  bc_back%outflow = 0.0_8
  DO ii1=1,size(bc%hyd,1)
    bc_back%hyd(ii1)%t = 0.0_8
  END DO
  DO ii1=1,size(bc%rat,1)
    bc_back%rat(ii1)%h = 0.0_8
  END DO
  DO ii1=1,size(bc%rat,1)
    bc_back%rat(ii1)%q = 0.0_8
  END DO
  bc_back%rat%zout = 0.0_8
  DO ii1=1,size(bc%rain,1)
    bc_back%rain(ii1)%t = 0.0_8
  END DO
  DO ii1=1,size(bc%rain,1)
    bc_back%rain(ii1)%q = 0.0_8
  END DO
  bc_back%rain%qin = 0.0_8
  bc_back%rain%cumul = 0.0_8
  bc_back%sum_mass_flux = 0.0_8
  IF (ALLOCATED(manning_beta_back)) manning_beta_back = 0.0_8
  dof_back%infil = 0.0_8
  CALL POPINTEGER4(ad_count)
  DO i0=1,ad_count
    CALL POPREAL8(dt)
    CALL POPINTEGER4(nt)
    CALL POPBOOLEAN(end_time_loop)
    CALL POPREAL8(tc)
    CALL POPREAL8ARRAY(bc%inflow, size(bc%inflow,1))
    CALL POPREAL8ARRAY(bc%outflow, size(bc%outflow,1))
    CALL POPREAL8ARRAY(bc%rat%zout, size(bc%rat,1))
    CALL POPREAL8ARRAY(bc%rain%qin, size(bc%rain,1))
    CALL POPREAL8ARRAY(bc%rain%cumul, size(bc%rain,1))
    CALL POPREAL8ARRAY(bc%sum_mass_flux, size(bc%sum_mass_flux,1))
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 1) CALL POPREAL8ARRAY(bathy_cell, &
&                                   size(bathy_cell,1))
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 1) CALL POPINTEGER4ARRAY(innovation%ind_t, &
&                                      size(innovation,1))
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 1) CALL POPINTEGER4ARRAY(innovq%ind_t, &
&                                      size(innovq,1))
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 1) CALL POPINTEGER4ARRAY(innovuv%ind_t, &
&                                      size(innovuv,1))
    CALL POPREAL8ARRAY(dof%h, size(dof%h,1))
    CALL POPREAL8ARRAY(dof%u, size(dof%u,1))
    CALL POPREAL8ARRAY(dof%v, size(dof%v,1))
    CALL POPREAL8ARRAY(dof%infil, size(dof%infil,1))
    CALL SUB_RUN_MODEL_BACK()
  END DO
  CALL POPCONTROL1B(branch)
  dof0_back%v = 0.0_8
  dof0_back%v = dof0_back%v + dof_back%v
  dof0_back%u = 0.0_8
  dof0_back%u = dof0_back%u + dof_back%u
  dof0_back%h = 0.0_8
  dof0_back%h = dof0_back%h + dof_back%h
  CALL POPCONTROL1B(branch)
  IF (branch .EQ. 0) THEN
    DO i=mesh%nc,1,-1
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        bathy_cell_back(i) = bathy_cell_back(i) - dof0_back%h(i)
      ELSE
        dof0_back%h(i) = 0.0_8
      END IF
    END DO
  END IF
  CALL POPCONTROL2B(branch)
  IF (branch .EQ. 0) THEN
    IF (ALLOCATED(ptf_back)) THEN
      DO ii1=1,size(ptf,1)
        ptf_back(ii1)%kappa = 0.0_8
      END DO
    END IF
    CALL POPINTEGER4(ad_to)
    DO i=ad_to,1,-1
      temp_back0 = 10._rp**(phys_desc%soil(i)%sand*ptf(phys_desc%&
&       ptf_land(i))%kappa(9)-phys_desc%soil(i)%clay*ptf(phys_desc%&
&       ptf_land(i))%kappa(8)-ptf(phys_desc%ptf_land(i))%kappa(7))*LOG(&
&       10._rp)*25.4_rp*infil_back%ga(i)%ks/(3600._rp*1000._rp)
      infil_back%ga(i)%ks = 0.0_8
      ptf_back(phys_desc%ptf_land(i))%kappa(9) = ptf_back(phys_desc%&
&       ptf_land(i))%kappa(9) + phys_desc%soil(i)%sand*temp_back0
      ptf_back(phys_desc%ptf_land(i))%kappa(8) = ptf_back(phys_desc%&
&       ptf_land(i))%kappa(8) - phys_desc%soil(i)%clay*temp_back0
      ptf_back(phys_desc%ptf_land(i))%kappa(7) = ptf_back(phys_desc%&
&       ptf_land(i))%kappa(7) - temp_back0
    END DO
  ELSE IF (branch .EQ. 1) THEN
    IF (ALLOCATED(ptf_back)) THEN
      DO ii1=1,size(ptf,1)
        ptf_back(ii1)%kappa = 0.0_8
      END DO
    END IF
  ELSE IF (ALLOCATED(ptf_back)) THEN
    DO ii1=1,size(ptf,1)
      ptf_back(ii1)%kappa = 0.0_8
    END DO
  END IF
  CALL POPCONTROL2B(branch)
  IF (branch .LT. 2) THEN
    IF (branch .EQ. 0) THEN
      DO ie=mesh%nc,1,-1
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          min2_back = bathy_cell_back(ie)
          bathy_temp_back = bathy_cell_back(ie)
          bathy_cell_back(ie) = 0.0_8
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            y2_back = min2_back
          ELSE
            y2_back = 0.0_8
          END IF
          temp1 = xsshape(1)%s
          temp0 = abs5/(xsshape(1)%xright-xsshape(1)%xcenter)
          temp = temp0**temp1
          abs1_back = -((1-temp)*y2_back)
          IF (temp0 .LE. 0.0 .AND. (temp1 .EQ. 0.0 .OR. temp1 .NE. INT(&
&             temp1))) THEN
            temp_back = 0.0_8
          ELSE
            temp_back = temp1*temp0**(temp1-1)*abs1*y2_back/(xsshape(1)%&
&             xright-xsshape(1)%xcenter)
          END IF
          IF (.NOT.temp0 .LE. 0.0) xsshape_back(1)%s = xsshape_back(1)%s&
&             + temp*LOG(temp0)*abs1*y2_back
          abs5_back = temp_back
          xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + temp0*&
&           temp_back
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            CALL POPREAL8(abs5)
            xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - &
&             abs5_back
          ELSE
            CALL POPREAL8(abs5)
            xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + &
&             abs5_back
          END IF
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            CALL POPREAL8(abs1)
            xsshape_back(1)%hmax = xsshape_back(1)%hmax - abs1_back
          ELSE
            CALL POPREAL8(abs1)
            xsshape_back(1)%hmax = xsshape_back(1)%hmax + abs1_back
          END IF
        ELSE
          min1_back = bathy_cell_back(ie)
          bathy_temp_back = bathy_cell_back(ie)
          bathy_cell_back(ie) = 0.0_8
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            y1_back = min1_back
          ELSE
            y1_back = 0.0_8
          END IF
          temp = xsshape(1)%s
          temp0 = abs4/(xsshape(1)%xcenter-xsshape(1)%xleft)
          temp1 = temp0**temp
          abs0_back = -((1-temp1)*y1_back)
          IF (temp0 .LE. 0.0 .AND. (temp .EQ. 0.0 .OR. temp .NE. INT(&
&             temp))) THEN
            temp_back = 0.0_8
          ELSE
            temp_back = temp*temp0**(temp-1)*abs0*y1_back/(xsshape(1)%&
&             xcenter-xsshape(1)%xleft)
          END IF
          IF (.NOT.temp0 .LE. 0.0) xsshape_back(1)%s = xsshape_back(1)%s&
&             + temp1*LOG(temp0)*abs0*y1_back
          abs4_back = temp_back
          xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - temp0*&
&           temp_back
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            CALL POPREAL8(abs4)
            xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - &
&             abs4_back
          ELSE
            CALL POPREAL8(abs4)
            xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + &
&             abs4_back
          END IF
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            CALL POPREAL8(abs0)
            xsshape_back(1)%hmax = xsshape_back(1)%hmax - abs0_back
          ELSE
            CALL POPREAL8(abs0)
            xsshape_back(1)%hmax = xsshape_back(1)%hmax + abs0_back
          END IF
        END IF
        bathy_cell_back(ie) = bathy_cell_back(ie) + bathy_temp_back
      END DO
    ELSE
      DO ie=mesh%nc,1,-1
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          min4_back = bathy_cell_back(ie)
          bathy_temp_back = bathy_cell_back(ie)
          bathy_cell_back(ie) = 0.0_8
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            y4_back = min4_back
          ELSE
            y4_back = 0.0_8
          END IF
          temp1 = xsshape(1)%s
          temp0 = abs7/(xsshape(1)%xright-xsshape(1)%xcenter)
          temp = temp0**temp1
          abs3_back = -((1-temp)*y4_back)
          IF (temp0 .LE. 0.0 .AND. (temp1 .EQ. 0.0 .OR. temp1 .NE. INT(&
&             temp1))) THEN
            temp_back = 0.0_8
          ELSE
            temp_back = temp1*temp0**(temp1-1)*abs3*y4_back/(xsshape(1)%&
&             xright-xsshape(1)%xcenter)
          END IF
          IF (.NOT.temp0 .LE. 0.0) xsshape_back(1)%s = xsshape_back(1)%s&
&             + temp*LOG(temp0)*abs3*y4_back
          abs7_back = temp_back
          xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + temp0*&
&           temp_back
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            CALL POPREAL8(abs7)
            xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - &
&             abs7_back
          ELSE
            CALL POPREAL8(abs7)
            xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + &
&             abs7_back
          END IF
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            CALL POPREAL8(abs3)
            xsshape_back(1)%hmax = xsshape_back(1)%hmax - abs3_back
          ELSE
            CALL POPREAL8(abs3)
            xsshape_back(1)%hmax = xsshape_back(1)%hmax + abs3_back
          END IF
        ELSE
          min3_back = bathy_cell_back(ie)
          bathy_temp_back = bathy_cell_back(ie)
          bathy_cell_back(ie) = 0.0_8
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            y3_back = min3_back
          ELSE
            y3_back = 0.0_8
          END IF
          temp1 = xsshape(1)%s
          temp0 = abs6/(xsshape(1)%xcenter-xsshape(1)%xleft)
          temp = temp0**temp1
          abs2_back = -((1-temp)*y3_back)
          IF (temp0 .LE. 0.0 .AND. (temp1 .EQ. 0.0 .OR. temp1 .NE. INT(&
&             temp1))) THEN
            temp_back = 0.0_8
          ELSE
            temp_back = temp1*temp0**(temp1-1)*abs2*y3_back/(xsshape(1)%&
&             xcenter-xsshape(1)%xleft)
          END IF
          IF (.NOT.temp0 .LE. 0.0) xsshape_back(1)%s = xsshape_back(1)%s&
&             + temp*LOG(temp0)*abs2*y3_back
          abs6_back = temp_back
          xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - temp0*&
&           temp_back
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            CALL POPREAL8(abs6)
            xsshape_back(1)%xcenter = xsshape_back(1)%xcenter - &
&             abs6_back
          ELSE
            CALL POPREAL8(abs6)
            xsshape_back(1)%xcenter = xsshape_back(1)%xcenter + &
&             abs6_back
          END IF
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            CALL POPREAL8(abs2)
            xsshape_back(1)%hmax = xsshape_back(1)%hmax - abs2_back
          ELSE
            CALL POPREAL8(abs2)
            xsshape_back(1)%hmax = xsshape_back(1)%hmax + abs2_back
          END IF
        END IF
        bathy_cell_back(ie) = bathy_cell_back(ie) + bathy_temp_back
      END DO
    END IF
  END IF

CONTAINS
!  Differentiation of sub_run_model in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: *(infil.ga).psif[from module m_model]
!                *(infil.ga).ks[from module m_model] *(infil.ga).deltatheta[from module m_model]
!                *(infil.scs).lambdacn[from module m_model] *(infil.scs).cn[from module m_model]
!                *manning[from module m_model] *(bc.inflow)[from module m_model]
!                *(bc.outflow)[from module m_model] *(*(bc.hyd).t)[from module m_model]
!                *(*(bc.hyd).q)[from module m_model] *(*(bc.rat).h)[from module m_model]
!                *(*(bc.rat).q)[from module m_model] *(bc.rat).zout[from module m_model]
!                *(*(bc.rain).t)[from module m_model] *(*(bc.rain).q)[from module m_model]
!                *(bc.rain).qin[from module m_model] *(bc.rain).cumul[from module m_model]
!                *(bc.sum_mass_flux)[from module m_model] *bathy_cell[from module m_model]
!                *manning_beta[from module m_model] *(*innovation.diff)[from module m_obs]
!                *(*innovq.diff)[from module m_obs] *(*innovuv.diff)[from module m_obs]
!                *(dof.h) *(dof.u) *(dof.v) *(dof.infil) cost
!   with respect to varying inputs: *(infil.ga).psif[from module m_model]
!                *(infil.ga).ks[from module m_model] *(infil.ga).deltatheta[from module m_model]
!                *(infil.scs).lambdacn[from module m_model] *(infil.scs).cn[from module m_model]
!                *manning[from module m_model] *(bc.inflow)[from module m_model]
!                *(bc.outflow)[from module m_model] *(*(bc.hyd).t)[from module m_model]
!                *(*(bc.hyd).q)[from module m_model] *(*(bc.rat).h)[from module m_model]
!                *(*(bc.rat).q)[from module m_model] *(bc.rat).zout[from module m_model]
!                *(*(bc.rain).t)[from module m_model] *(*(bc.rain).q)[from module m_model]
!                *(bc.rain).qin[from module m_model] *(bc.rain).cumul[from module m_model]
!                *(bc.sum_mass_flux)[from module m_model] *bathy_cell[from module m_model]
!                *manning_beta[from module m_model] *(*innovation.diff)[from module m_obs]
!                *(*innovq.diff)[from module m_obs] *(*innovuv.diff)[from module m_obs]
!                *(dof.h) *(dof.u) *(dof.v) *(dof.infil) cost
!   Plus diff mem management of: infil.ga[from module m_model]:in
!                infil.scs[from module m_model]:in manning[from module m_model]:in
!                bc.inflow[from module m_model]:in bc.outflow[from module m_model]:in
!                bc.hyd[from module m_model]:in *(bc.hyd).t[from module m_model]:in
!                *(bc.hyd).q[from module m_model]:in bc.rat[from module m_model]:in
!                *(bc.rat).h[from module m_model]:in *(bc.rat).q[from module m_model]:in
!                bc.hpresc[from module m_model]:in *(bc.hpresc).t[from module m_model]:in
!                *(bc.hpresc).h[from module m_model]:in bc.zspresc[from module m_model]:in
!                *(bc.zspresc).t[from module m_model]:in *(bc.zspresc).z[from module m_model]:in
!                bc.rain[from module m_model]:in *(bc.rain).t[from module m_model]:in
!                *(bc.rain).q[from module m_model]:in bc.sum_mass_flux[from module m_model]:in
!                bathy_cell[from module m_model]:in manning_beta[from module m_model]:in
!                innovation[from module m_obs]:in *innovation.diff[from module m_obs]:in
!                innovq[from module m_obs]:in *innovq.diff[from module m_obs]:in
!                innovuv[from module m_obs]:in *innovuv.diff[from module m_obs]:in
!                dof.h:in dof.u:in dof.v:in dof.infil:in
  SUBROUTINE SUB_RUN_MODEL_BACK()

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    INTEGER*4 :: branch
    INTEGER :: ad_count
    INTEGER :: i0
    sub_nt = 0
    ad_count = 0
    DO WHILE (.NOT.end_time_loop .AND. sub_nt .LT. max_nt_for_adjoint)
      CALL PUSHREAL8ARRAY(bc%rain%qin, size(bc%rain,1))
      CALL PUSHREAL8ARRAY(bc%rat%zout, size(bc%rat,1))
      CALL PUSHREAL8ARRAY(bc%outflow, size(bc%outflow,1))
      CALL PUSHREAL8ARRAY(bc%inflow, size(bc%inflow,1))
      CALL PUSHREAL8ARRAY(dof%h, size(dof%h,1))
      CALL SET_BC(dof, mesh) ! Replaced by Perl Script
      CALL PUSHREAL8(tc)
      CALL PUSHINTEGER4(nt)
      CALL PUSHREAL8(dt)
      CALL ADVANCE_TIME(dof, mesh) ! Replaced by Perl Script
      CALL PUSHREAL8ARRAY(bc%sum_mass_flux, size(bc%sum_mass_flux,1))
      bc%sum_mass_flux(:) = 0._rp
      SELECT CASE  (temp_scheme) 
      CASE ('euler') 
        SELECT CASE  (spatial_scheme) 
        CASE ('first_b1') 
          IF (ALLOCATED(bathy_cell)) THEN
            CALL PUSHREAL8ARRAY(bathy_cell, size(bathy_cell,1))
            CALL PUSHCONTROL1B(1)
          ELSE
            CALL PUSHCONTROL1B(0)
          END IF
          CALL PUSHREAL8ARRAY(bc%sum_mass_flux, &
&                       size(bc%sum_mass_flux,1))
          CALL PUSHREAL8ARRAY(bc%rain%cumul, size(bc%rain,1))
          CALL PUSHREAL8ARRAY(dof%h, size(dof%h,1))
          CALL PUSHREAL8ARRAY(dof%u, size(dof%u,1))
          CALL PUSHREAL8ARRAY(dof%v, size(dof%v,1))
          CALL PUSHREAL8ARRAY(dof%infil, size(dof%infil,1))
          CALL EULER_TIME_STEP_FIRST_B1(dof, mesh) ! Replaced by Perl Script
          CALL PUSHCONTROL2B(0)
        CASE DEFAULT
          CALL PUSHCONTROL2B(1)
        END SELECT
      CASE DEFAULT
        CALL PUSHCONTROL2B(2)
      END SELECT
      CALL PUSHREAL8ARRAY(bc%sum_mass_flux, size(bc%sum_mass_flux,1))
      CALL SW_POST_TREATMENT(dof, mesh) ! Replaced by Perl Script
      IF (use_obs .EQ. 1) THEN
        IF (use_zobs .EQ. 1) THEN
          IF (ALLOCATED(innovation)) THEN
            CALL PUSHINTEGER4ARRAY(innovation%ind_t, &
&                            size(innovation,1))
            CALL PUSHCONTROL1B(1)
          ELSE
            CALL PUSHCONTROL1B(0)
          END IF
          CALL CALC_INNOVATION(dof, mesh) ! Replaced by Perl Script
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHCONTROL1B(1)
        END IF
        IF (use_uvobs .EQ. 1) THEN
          IF (ALLOCATED(innovuv)) THEN
            CALL PUSHINTEGER4ARRAY(innovuv%ind_t, size(innovuv,1))
            CALL PUSHCONTROL1B(1)
          ELSE
            CALL PUSHCONTROL1B(0)
          END IF
          CALL CALC_INNOVUV(dof, mesh) ! Replaced by Perl Script
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHCONTROL1B(1)
        END IF
        IF (use_qobs .EQ. 1) THEN
          IF (ALLOCATED(innovq)) THEN
            CALL PUSHINTEGER4ARRAY(innovq%ind_t, size(innovq,1))
            CALL PUSHCONTROL1B(1)
          ELSE
            CALL PUSHCONTROL1B(0)
          END IF
          CALL CALC_INNOVQ(dof, mesh) ! Replaced by Perl Script
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHCONTROL1B(1)
        END IF
        IF (.NOT.use_obs .EQ. 1) THEN
          CALL PUSHCONTROL2B(1)
        ELSE
          CALL PUSHCONTROL2B(2)
        END IF
        sub_nt = sub_nt + 1
      ELSE
        CALL PUSHCONTROL2B(0)
      END IF
      ad_count = ad_count + 1
    END DO
    DO i0=1,ad_count
      CALL POPCONTROL2B(branch)
      IF (branch .NE. 0) THEN
        IF (branch .EQ. 1) CALL UPDATE_COST_FUNCTION_BACK(dof, dof_back&
&                                                   , cost, cost_back)
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 1) CALL POPINTEGER4ARRAY(innovq%ind_t, &
&                                            size(innovq,1))
          CALL CALC_INNOVQ_BACK(dof, mesh)
        END IF
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 1) CALL POPINTEGER4ARRAY(innovuv%ind_t, &
&                                            size(innovuv,1))
          CALL CALC_INNOVUV_BACK(dof, dof_back, mesh)
        END IF
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 1) CALL POPINTEGER4ARRAY(innovation%ind_t, &
&                                            size(innovation,1))
          CALL CALC_INNOVATION_BACK(dof, dof_back, mesh)
        END IF
      END IF
      CALL POPREAL8ARRAY(bc%sum_mass_flux, size(bc%sum_mass_flux,1))
      CALL SW_POST_TREATMENT_BACK(dof, mesh)
      CALL POPCONTROL2B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPREAL8ARRAY(dof%infil, size(dof%infil,1))
        CALL POPREAL8ARRAY(dof%v, size(dof%v,1))
        CALL POPREAL8ARRAY(dof%u, size(dof%u,1))
        CALL POPREAL8ARRAY(dof%h, size(dof%h,1))
        CALL POPREAL8ARRAY(bc%rain%cumul, size(bc%rain,1))
        CALL POPREAL8ARRAY(bc%sum_mass_flux, size(bc%sum_mass_flux,1)&
&                   )
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 1) CALL POPREAL8ARRAY(bathy_cell, &
&                                       size(bathy_cell,1))
        CALL EULER_TIME_STEP_FIRST_B1_BACK(dof, dof_back, mesh)
      END IF
      CALL POPREAL8ARRAY(bc%sum_mass_flux, size(bc%sum_mass_flux,1))
      bc_back%sum_mass_flux = 0.0_8
      CALL POPREAL8(dt)
      CALL POPINTEGER4(nt)
      CALL POPREAL8(tc)
      CALL POPREAL8ARRAY(dof%h, size(dof%h,1))
      CALL POPREAL8ARRAY(bc%inflow, size(bc%inflow,1))
      CALL POPREAL8ARRAY(bc%outflow, size(bc%outflow,1))
      CALL POPREAL8ARRAY(bc%rat%zout, size(bc%rat,1))
      CALL POPREAL8ARRAY(bc%rain%qin, size(bc%rain,1))
      CALL SET_BC_BACK(dof, dof_back, mesh)
    END DO
  END SUBROUTINE SUB_RUN_MODEL_BACK

  SUBROUTINE SUB_RUN_MODEL()

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    sub_nt = 0
    DO WHILE (.NOT.end_time_loop .AND. sub_nt .LT. max_nt_for_adjoint)
      CALL SET_BC(dof, mesh) ! Replaced by Perl Script
      CALL ADVANCE_TIME(dof, mesh) ! Replaced by Perl Script
      bc%sum_mass_flux(:) = 0._rp
      SELECT CASE  (temp_scheme) 
      CASE ('euler') 
        SELECT CASE  (spatial_scheme) 
        CASE ('first_b1') 
          CALL EULER_TIME_STEP_FIRST_B1(dof, mesh) ! Replaced by Perl Script
        CASE DEFAULT
          CALL STOPPING_PROGRAM_SUB('Unknow spatial scheme')
        END SELECT
      CASE DEFAULT
        CALL STOPPING_PROGRAM_SUB('Unknow temporal scheme')
      END SELECT
      CALL SW_POST_TREATMENT(dof, mesh) ! Replaced by Perl Script
      IF (use_obs .EQ. 1) THEN
        IF (use_zobs .EQ. 1) CALL CALC_INNOVATION(dof, mesh) ! Replaced by Perl Script
        IF (use_uvobs .EQ. 1) CALL CALC_INNOVUV(dof, mesh) ! Replaced by Perl Script
        IF (use_qobs .EQ. 1) CALL CALC_INNOVQ(dof, mesh) ! Replaced by Perl Script
        IF (.NOT.use_obs .EQ. 1) CALL UPDATE_COST_FUNCTION(dof, cost)
        sub_nt = sub_nt + 1
      END IF
    END DO
  END SUBROUTINE SUB_RUN_MODEL

END SUBROUTINE RUN_MODEL_BACK

