!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 25 Jun 2025 16:38
!
!  Differentiation of run_model in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: *(*innovation.diff) *(*innovq.diff)
!                *(*innovuv.diff) *(dof.h) *(dof.u) *(dof.v) cost
!   with respect to varying inputs: *(infil.ga).psif *(infil.ga).ks
!                *(infil.ga).deltatheta *(infil.scs).lambdacn *(infil.scs).cn
!                *manning *ptf.kappa *(*(bc.hyd).t) *(*(bc.hyd).q)
!                *(*(bc.rat).h) *(*(bc.rat).q) *(*(bc.rain).t)
!                *(*(bc.rain).q) *xsshape.xcenter *xsshape.s *xsshape.hmax
!                *bathy_cell *manning_beta *(sporosity.phi) *(dof0.h)
!                *(dof0.u) *(dof0.v)
!   RW status of diff variables: tc:(loc) *(infil.ga).psif:in *(infil.ga).ks:in-killed
!                *(infil.ga).deltatheta:in *(infil.scs).lambdacn:in
!                *(infil.scs).cn:in *manning:in *ptf.kappa:in *(bc.inflow):(loc)
!                *(bc.outflow):(loc) *(*(bc.hyd).t):in *(*(bc.hyd).q):in
!                *(*(bc.rat).h):in *(*(bc.rat).q):in *(bc.rat).zout:(loc)
!                *(*(bc.rain).t):in *(*(bc.rain).q):in *(bc.rain).qin:(loc)
!                *(bc.rain).cumul:(loc) *(bc.sum_mass_flux):(loc)
!                *xsshape.xcenter:in *xsshape.s:in *xsshape.hmax:in
!                *bathy_cell:in-killed *manning_beta:in *(sporosity.phi):in-killed
!                *(*innovation.diff):out *(*innovq.diff):out *(*innovw.diff):(loc)
!                *(*innovuv.diff):out dof.h:(loc) *(dof.h):out
!                dof.u:(loc) *(dof.u):out dof.v:(loc) *(dof.v):out
!                *(dof.infil):(loc) cost:out dof0.h:(loc) *(dof0.h):in-killed
!                dof0.u:(loc) *(dof0.u):in dof0.v:(loc) *(dof0.v):in
!   Plus diff mem management of: infil.ga:in infil.scs:in manning:in
!                ptf:in bc.inflow:in bc.outflow:in bc.hyd:in *(bc.hyd).t:in
!                *(bc.hyd).q:in bc.rat:in *(bc.rat).h:in *(bc.rat).q:in
!                bc.hpresc:in *(bc.hpresc).t:in *(bc.hpresc).h:in
!                bc.zspresc:in *(bc.zspresc).t:in *(bc.zspresc).z:in
!                bc.rain:in *(bc.rain).t:in *(bc.rain).q:in bc.sum_mass_flux:in
!                xsshape:in bathy_cell:in manning_beta:in sporosity.phi:in
!                innovation:in *innovation.diff:in innovq:in *innovq.diff:in
!                innovuv:in *innovuv.diff:in dof.h:in dof.u:in
!                dof.v:in dof.infil:in dof0.h:in dof0.u:in dof0.v:in
SUBROUTINE RUN_MODEL_DIFF(mesh, dof0, dof0_diff, dof, dof_diff, cost, &
& cost_diff)
  USE M_COMMON ! Replaced by Perl Script
  USE M_LINEAR_ALGEBRA ! Replaced by Perl Script
  USE M_MESH ! Replaced by Perl Script
  USE M_MPI ! Replaced by Perl Script
  USE M_NUMERIC ! Replaced by Perl Script
  USE M_NUMERIC_DIFF
  USE M_MODEL ! Replaced by Perl Script
  USE M_OBS ! Replaced by Perl Script
  USE M_OBS_DIFF

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  TYPE(MSH), INTENT(INOUT) :: mesh
  TYPE(UNK), INTENT(INOUT) :: dof0
  TYPE(UNK), INTENT(INOUT) :: dof0_diff ! Replaced by Perl Script
  TYPE(UNK), INTENT(INOUT) :: dof
  TYPE(UNK), INTENT(INOUT) :: dof_diff ! Replaced by Perl Script
  REAL(rp), INTENT(OUT) :: cost
  REAL(rp), INTENT(OUT) :: cost_diff
  INTEGER(ip) :: sub_nt, ir, il
  REAL(rp) :: bathy_temp
  REAL(rp) :: bathy_temp_diff
  REAL(rp) :: ks_ubound, ks_lbound, z, lambda, shift
  INTEGER :: poro_unit
  INTRINSIC ABS
  INTRINSIC MIN
  INTRINSIC SIZE
  INTRINSIC MAX
  REAL(rp) :: y1
  REAL(rp) :: y1_diff
  REAL(rp) :: y2
  REAL(rp) :: y2_diff
  REAL(rp) :: y3
  REAL(rp) :: y3_diff
  REAL(rp) :: y4
  REAL(rp) :: y4_diff
  REAL(rp) :: min1
  REAL(rp) :: min1_diff
  REAL(rp) :: min2
  REAL(rp) :: min2_diff
  REAL(rp) :: min3
  REAL(rp) :: min3_diff
  REAL(rp) :: min4
  REAL(rp) :: min4_diff
  REAL(rp) :: abs0
  REAL(rp) :: abs0_diff
  REAL(rp) :: abs1
  REAL(rp) :: abs1_diff
  REAL(rp) :: abs2
  REAL(rp) :: abs2_diff
  REAL(rp) :: abs3
  REAL(rp) :: abs3_diff
  REAL(rp) :: abs4
  REAL(rp) :: abs4_diff
  REAL(rp) :: abs5
  REAL(rp) :: abs5_diff
  REAL(rp) :: abs6
  REAL(rp) :: abs6_diff
  REAL(rp) :: abs7
  REAL(rp) :: abs7_diff
  REAL(rp) :: abs8
  REAL(rp) :: abs8_diff
  REAL(rp) :: abs9
  REAL(rp) :: abs9_diff
  REAL(rp) :: abs10
  REAL(rp) :: abs10_diff
  REAL(rp) :: abs11
  REAL(rp) :: abs11_diff
  REAL(rp) :: temp
  REAL(rp) :: temp0
  REAL(rp) :: temp_diff
  REAL(rp) :: temp_diff0
  INTEGER :: ii1
  OPEN(newunit=poro_unit, file='res/porosity_history.dat', form=&
&'FORMATTED', status='REPLACE') 
  IF (use_xsshp .EQ. 1) THEN
    IF (xsshp_along_y .EQ. 1) THEN
      DO ie=1,mesh%nc
        bathy_temp_diff = bathy_cell_diff(ie)
        bathy_temp = bathy_cell(ie)
        IF (mesh%cell(ie)%grav%x .LE. xsshape(1)%xcenter) THEN
          IF (xsshape(1)%hmax .GE. 0.) THEN
            abs0_diff = xsshape_diff(1)%hmax
            abs0 = xsshape(1)%hmax
          ELSE
            abs0_diff = -xsshape_diff(1)%hmax
            abs0 = -xsshape(1)%hmax
          END IF
          IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&             xcenter-xsshape(1)%xleft) .GE. 0.) THEN
            abs4_diff = -xsshape_diff(1)%xcenter
            abs4 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)&
&             %xcenter-xsshape(1)%xleft)
          ELSE
            abs4_diff = xsshape_diff(1)%xcenter
            abs4 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape(1)%&
&             xcenter-xsshape(1)%xleft))
          END IF
          IF (xsshape(1)%s .GE. 0.) THEN
            abs8_diff = xsshape_diff(1)%s
            abs8 = xsshape(1)%s
          ELSE
            abs8_diff = -xsshape_diff(1)%s
            abs8 = -xsshape(1)%s
          END IF
          temp = abs4/(xsshape(1)%xcenter-xsshape(1)%xleft)
          temp0 = temp**abs8
          IF (temp .LE. 0.0 .AND. (abs8 .EQ. 0.0 .OR. abs8 .NE. INT(abs8&
&             ))) THEN
            temp_diff = 0.0_8
          ELSE IF (temp .LE. 0.0) THEN
            temp_diff = abs8*temp**(abs8-1)*(abs4_diff-temp*xsshape_diff&
&             (1)%xcenter)/(xsshape(1)%xcenter-xsshape(1)%xleft)
          ELSE
            temp_diff = abs8*temp**(abs8-1)*(abs4_diff-temp*xsshape_diff&
&             (1)%xcenter)/(xsshape(1)%xcenter-xsshape(1)%xleft) + temp0&
&             *LOG(temp)*abs8_diff
          END IF
          y1_diff = -((1-temp0)*abs0_diff-abs0*temp_diff)
          y1 = -(abs0*(1-temp0))
          IF (0._rp .GT. y1) THEN
            min1_diff = y1_diff
            min1 = y1
          ELSE
            min1 = 0._rp
            min1_diff = 0.0_8
          END IF
          bathy_cell_diff(ie) = min1_diff + bathy_temp_diff
          bathy_cell(ie) = xsshape(1)%topz + min1 + bathy_temp + slope_y&
&           (1)*mesh%cell(ie)%grav%y + slope_x(1)*mesh%cell(ie)%grav%x
        ELSE
          IF (xsshape(1)%hmax .GE. 0.) THEN
            abs1_diff = xsshape_diff(1)%hmax
            abs1 = xsshape(1)%hmax
          ELSE
            abs1_diff = -xsshape_diff(1)%hmax
            abs1 = -xsshape(1)%hmax
          END IF
          IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&             xcenter-xsshape(1)%xleft) .GE. 0.) THEN
            abs5_diff = -xsshape_diff(1)%xcenter
            abs5 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)&
&             %xcenter-xsshape(1)%xleft)
          ELSE
            abs5_diff = xsshape_diff(1)%xcenter
            abs5 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape(1)%&
&             xcenter-xsshape(1)%xleft))
          END IF
          IF (xsshape(1)%s .GE. 0.) THEN
            abs9_diff = xsshape_diff(1)%s
            abs9 = xsshape(1)%s
          ELSE
            abs9_diff = -xsshape_diff(1)%s
            abs9 = -xsshape(1)%s
          END IF
          temp0 = abs5/(xsshape(1)%xright-xsshape(1)%xcenter)
          temp = temp0**abs9
          IF (temp0 .LE. 0.0 .AND. (abs9 .EQ. 0.0 .OR. abs9 .NE. INT(&
&             abs9))) THEN
            temp_diff0 = 0.0_8
          ELSE IF (temp0 .LE. 0.0) THEN
            temp_diff0 = abs9*temp0**(abs9-1)*(abs5_diff+temp0*&
&             xsshape_diff(1)%xcenter)/(xsshape(1)%xright-xsshape(1)%&
&             xcenter)
          ELSE
            temp_diff0 = abs9*temp0**(abs9-1)*(abs5_diff+temp0*&
&             xsshape_diff(1)%xcenter)/(xsshape(1)%xright-xsshape(1)%&
&             xcenter) + temp*LOG(temp0)*abs9_diff
          END IF
          y2_diff = -((1-temp)*abs1_diff-abs1*temp_diff0)
          y2 = -(abs1*(1-temp))
          IF (0._rp .GT. y2) THEN
            min2_diff = y2_diff
            min2 = y2
          ELSE
            min2 = 0._rp
            min2_diff = 0.0_8
          END IF
          bathy_cell_diff(ie) = min2_diff + bathy_temp_diff
          bathy_cell(ie) = xsshape(1)%topz + min2 + bathy_temp + slope_y&
&           (1)*mesh%cell(ie)%grav%y + slope_x(1)*mesh%cell(ie)%grav%x
        END IF
      END DO
    ELSE IF (xsshp_along_x .EQ. 1) THEN
      DO ie=1,mesh%nc
        bathy_temp_diff = bathy_cell_diff(ie)
        bathy_temp = bathy_cell(ie)
        IF (mesh%cell(ie)%grav%y .LE. xsshape(1)%xcenter) THEN
          IF (xsshape(1)%hmax .GE. 0.) THEN
            abs2_diff = xsshape_diff(1)%hmax
            abs2 = xsshape(1)%hmax
          ELSE
            abs2_diff = -xsshape_diff(1)%hmax
            abs2 = -xsshape(1)%hmax
          END IF
          IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&             xcenter-xsshape(1)%xleft) .GE. 0.) THEN
            abs6_diff = -xsshape_diff(1)%xcenter
            abs6 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)&
&             %xcenter-xsshape(1)%xleft)
          ELSE
            abs6_diff = xsshape_diff(1)%xcenter
            abs6 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape(1)%&
&             xcenter-xsshape(1)%xleft))
          END IF
          IF (xsshape(1)%s .GE. 0.) THEN
            abs10_diff = xsshape_diff(1)%s
            abs10 = xsshape(1)%s
          ELSE
            abs10_diff = -xsshape_diff(1)%s
            abs10 = -xsshape(1)%s
          END IF
          temp0 = abs6/(xsshape(1)%xcenter-xsshape(1)%xleft)
          temp = temp0**abs10
          IF (temp0 .LE. 0.0 .AND. (abs10 .EQ. 0.0 .OR. abs10 .NE. INT(&
&             abs10))) THEN
            temp_diff0 = 0.0_8
          ELSE IF (temp0 .LE. 0.0) THEN
            temp_diff0 = abs10*temp0**(abs10-1)*(abs6_diff-temp0*&
&             xsshape_diff(1)%xcenter)/(xsshape(1)%xcenter-xsshape(1)%&
&             xleft)
          ELSE
            temp_diff0 = abs10*temp0**(abs10-1)*(abs6_diff-temp0*&
&             xsshape_diff(1)%xcenter)/(xsshape(1)%xcenter-xsshape(1)%&
&             xleft) + temp*LOG(temp0)*abs10_diff
          END IF
          y3_diff = -((1-temp)*abs2_diff-abs2*temp_diff0)
          y3 = -(abs2*(1-temp))
          IF (0._rp .GT. y3) THEN
            min3_diff = y3_diff
            min3 = y3
          ELSE
            min3 = 0._rp
            min3_diff = 0.0_8
          END IF
          bathy_cell_diff(ie) = min3_diff + bathy_temp_diff
          bathy_cell(ie) = xsshape(1)%topz + min3 + bathy_temp + slope_y&
&           (1)*mesh%cell(ie)%grav%y + slope_x(1)*mesh%cell(ie)%grav%x
        ELSE
          IF (xsshape(1)%hmax .GE. 0.) THEN
            abs3_diff = xsshape_diff(1)%hmax
            abs3 = xsshape(1)%hmax
          ELSE
            abs3_diff = -xsshape_diff(1)%hmax
            abs3 = -xsshape(1)%hmax
          END IF
          IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&             xcenter-xsshape(1)%xleft) .GE. 0.) THEN
            abs7_diff = -xsshape_diff(1)%xcenter
            abs7 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)&
&             %xcenter-xsshape(1)%xleft)
          ELSE
            abs7_diff = xsshape_diff(1)%xcenter
            abs7 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape(1)%&
&             xcenter-xsshape(1)%xleft))
          END IF
          IF (xsshape(1)%s .GE. 0.) THEN
            abs11_diff = xsshape_diff(1)%s
            abs11 = xsshape(1)%s
          ELSE
            abs11_diff = -xsshape_diff(1)%s
            abs11 = -xsshape(1)%s
          END IF
          temp0 = abs7/(xsshape(1)%xright-xsshape(1)%xcenter)
          temp = temp0**abs11
          IF (temp0 .LE. 0.0 .AND. (abs11 .EQ. 0.0 .OR. abs11 .NE. INT(&
&             abs11))) THEN
            temp_diff0 = 0.0_8
          ELSE IF (temp0 .LE. 0.0) THEN
            temp_diff0 = abs11*temp0**(abs11-1)*(abs7_diff+temp0*&
&             xsshape_diff(1)%xcenter)/(xsshape(1)%xright-xsshape(1)%&
&             xcenter)
          ELSE
            temp_diff0 = abs11*temp0**(abs11-1)*(abs7_diff+temp0*&
&             xsshape_diff(1)%xcenter)/(xsshape(1)%xright-xsshape(1)%&
&             xcenter) + temp*LOG(temp0)*abs11_diff
          END IF
          y4_diff = -((1-temp)*abs3_diff-abs3*temp_diff0)
          y4 = -(abs3*(1-temp))
          IF (0._rp .GT. y4) THEN
            min4_diff = y4_diff
            min4 = y4
          ELSE
            min4 = 0._rp
            min4_diff = 0.0_8
          END IF
          bathy_cell_diff(ie) = min4_diff + bathy_temp_diff
          bathy_cell(ie) = xsshape(1)%topz + min4 + bathy_temp + slope_y&
&           (1)*mesh%cell(ie)%grav%y + slope_x(1)*mesh%cell(ie)%grav%x
        END IF
      END DO
    END IF
  END IF
  IF (use_ptf .EQ. 1) THEN
    IF (bc_infil .EQ. 1) THEN
      DO i=1,SIZE(phys_desc%soil)
!kg/m2 to m
        temp0 = 10._rp**(phys_desc%soil(i)%sand*ptf(phys_desc%ptf_land(i&
&         ))%kappa(9)-phys_desc%soil(i)%clay*ptf(phys_desc%ptf_land(i))%&
&         kappa(8)-ptf(phys_desc%ptf_land(i))%kappa(7))
        infil_diff%ga(i)%ks = 25.4_rp*temp0*LOG(10._rp)*(phys_desc%soil(&
&         i)%sand*ptf_diff(phys_desc%ptf_land(i))%kappa(9)-phys_desc%&
&         soil(i)%clay*ptf_diff(phys_desc%ptf_land(i))%kappa(8)-ptf_diff&
&         (phys_desc%ptf_land(i))%kappa(7))/(3600._rp*1000._rp)
        infil%ga(i)%ks = 25.4_rp*(temp0/(3600._rp*1000._rp))
      END DO
    ELSE IF (bc_infil .EQ. 2) THEN
      CALL STOPPING_PROGRAM_SUB('PTF for SCS-CN method not defined yet')
    END IF
  END IF
  INQUIRE(file='zs_init.txt', exist=file_exist(1)) 
  IF (file_exist(1)) THEN
    WRITE(*, *) 'Using zs_init.txt to initialize water depth'
    DO i=1,mesh%nc
      IF (0._rp .LT. dof0%h(i) - bathy_cell(i) + slope_y(1)*mesh%cell(i)&
&         %grav%y + slope_x(1)*mesh%cell(i)%grav%x) THEN
        dof0_diff%h(i) = dof0_diff%h(i) - bathy_cell_diff(i)
        dof0%h(i) = dof0%h(i) - bathy_cell(i) + slope_y(1)*mesh%cell(i)%&
&         grav%y + slope_x(1)*mesh%cell(i)%grav%x
      ELSE
        dof0_diff%h(i) = 0.0_8
        dof0%h(i) = 0._rp
      END IF
    END DO
  END IF
  dof_diff%h = 0.0_8
  dof_diff%h = dof0_diff%h
  dof%h = dof0%h
  dof_diff%u = 0.0_8
  dof_diff%u = dof0_diff%u
  dof%u = dof0%u
  dof_diff%v = 0.0_8
  dof_diff%v = dof0_diff%v
  dof%v = dof0%v
  tc = tc0
  nt = nt0
  IF (use_obs .EQ. 1) THEN
    IF (use_zobs .EQ. 1) innovation(:)%ind_t = 1_ip
    IF (use_uvobs .EQ. 1) innovuv(:)%ind_t = 1_ip
    IF (use_qobs .EQ. 1 .OR. use_qobs_gr4 .EQ. 1) innovq(:)%ind_t = 1_ip
  END IF
  IF (use_qobs .EQ. 1 .OR. use_qobs_gr4 .EQ. 1) innovq(:)%ind_t = 1_ip
  cost = 0._rp
  end_time_loop = .false.
  bc_diff%inflow = 0.0_8
  bc_diff%outflow = 0.0_8
  bc_diff%rat%zout = 0.0_8
  bc_diff%rain%qin = 0.0_8
  bc_diff%rain%cumul = 0.0_8
  bc_diff%sum_mass_flux = 0.0_8
  IF (ALLOCATED(innovation_diff)) THEN
    DO ii1=1,size(innovation,1)
      innovation_diff(ii1)%diff = 0.0_8
    END DO
  END IF
  IF (ALLOCATED(innovq_diff)) THEN
    DO ii1=1,size(innovq,1)
      innovq_diff(ii1)%diff = 0.0_8
    END DO
  END IF
  IF (ALLOCATED(innovuv_diff)) THEN
    DO ii1=1,size(innovuv,1)
      innovuv_diff(ii1)%diff = 0.0_8
    END DO
  END IF
  dof_diff%infil = 0.0_8
  cost_diff = 0.0_8
  DO WHILE (.NOT.end_time_loop)
    CALL SUB_RUN_MODEL_DIFF()
  END DO
  CALL CALC_COST_FUNCTION_DIFF(cost, cost_diff, mesh)
  CLOSE(poro_unit) 
  IF (ALLOCATED(innovw_diff)) THEN
    DO ii1=1,size(innovw,1)
      innovw_diff(ii1)%diff = 0.0_8
    END DO
  END IF

CONTAINS
!  Differentiation of sub_run_model in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: *(bc.inflow)[from module m_model]
!                *(bc.outflow)[from module m_model] *(bc.rat).zout[from module m_model]
!                *(bc.rain).qin[from module m_model] *(bc.rain).cumul[from module m_model]
!                *(bc.sum_mass_flux)[from module m_model] *bathy_cell[from module m_model]
!                *(sporosity.phi)[from module m_model] *(*innovation.diff)[from module m_obs]
!                *(*innovq.diff)[from module m_obs] *(*innovuv.diff)[from module m_obs]
!                *(dof.h) *(dof.u) *(dof.v) *(dof.infil) cost
!   with respect to varying inputs: *(infil.ga).psif[from module m_model]
!                *(infil.ga).ks[from module m_model] *(infil.ga).deltatheta[from module m_model]
!                *(infil.scs).lambdacn[from module m_model] *(infil.scs).cn[from module m_model]
!                *manning[from module m_model] *(bc.inflow)[from module m_model]
!                *(bc.outflow)[from module m_model] *(*(bc.hyd).t)[from module m_model]
!                *(*(bc.hyd).q)[from module m_model] *(*(bc.rat).h)[from module m_model]
!                *(*(bc.rat).q)[from module m_model] *(bc.rat).zout[from module m_model]
!                *(*(bc.rain).t)[from module m_model] *(*(bc.rain).q)[from module m_model]
!                *(bc.rain).qin[from module m_model] *(bc.rain).cumul[from module m_model]
!                *(bc.sum_mass_flux)[from module m_model] *bathy_cell[from module m_model]
!                *manning_beta[from module m_model] *(sporosity.phi)[from module m_model]
!                *(*innovation.diff)[from module m_obs] *(*innovq.diff)[from module m_obs]
!                *(*innovuv.diff)[from module m_obs] *(dof.h) *(dof.u)
!                *(dof.v) *(dof.infil) cost
!   Plus diff mem management of: infil.ga[from module m_model]:in
!                infil.scs[from module m_model]:in manning[from module m_model]:in
!                bc.inflow[from module m_model]:in bc.outflow[from module m_model]:in
!                bc.hyd[from module m_model]:in *(bc.hyd).t[from module m_model]:in
!                *(bc.hyd).q[from module m_model]:in bc.rat[from module m_model]:in
!                *(bc.rat).h[from module m_model]:in *(bc.rat).q[from module m_model]:in
!                bc.hpresc[from module m_model]:in *(bc.hpresc).t[from module m_model]:in
!                *(bc.hpresc).h[from module m_model]:in bc.zspresc[from module m_model]:in
!                *(bc.zspresc).t[from module m_model]:in *(bc.zspresc).z[from module m_model]:in
!                bc.rain[from module m_model]:in *(bc.rain).t[from module m_model]:in
!                *(bc.rain).q[from module m_model]:in bc.sum_mass_flux[from module m_model]:in
!                bathy_cell[from module m_model]:in manning_beta[from module m_model]:in
!                sporosity.phi[from module m_model]:in innovation[from module m_obs]:in
!                *innovation.diff[from module m_obs]:in innovq[from module m_obs]:in
!                *innovq.diff[from module m_obs]:in innovuv[from module m_obs]:in
!                *innovuv.diff[from module m_obs]:in dof.h:in dof.u:in
!                dof.v:in dof.infil:in
  SUBROUTINE SUB_RUN_MODEL_DIFF()

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    sub_nt = 0
    DO WHILE (.NOT.end_time_loop .AND. sub_nt .LT. max_nt_for_adjoint)
      CALL SET_BC_DIFF(dof, dof_diff, mesh)
      CALL ADVANCE_TIME(dof, mesh) ! Replaced by Perl Script
      bc_diff%sum_mass_flux(:) = 0.0_8
      bc%sum_mass_flux(:) = 0._rp
      SELECT CASE (temp_scheme)
      CASE ('euler')
        SELECT CASE (spatial_scheme)
        CASE ('first_b1')
! Compiltation flags for porosity now added in euler_time_step_first_b1
          CALL EULER_TIME_STEP_FIRST_B1_DIFF(dof, dof_diff, mesh, &
&                                      poro_unit, nt)
        CASE DEFAULT
          CALL STOPPING_PROGRAM_SUB('Unknow spatial scheme')
        END SELECT
      CASE DEFAULT
        CALL STOPPING_PROGRAM_SUB('Unknow temporal scheme')
      END SELECT
      CALL SW_POST_TREATMENT_DIFF(dof, mesh)
      IF (use_obs .EQ. 1) THEN
        IF (use_zobs .EQ. 1) CALL CALC_INNOVATION_DIFF(dof, dof_diff, &
&                                                mesh)
        IF (use_uvobs .EQ. 1) CALL CALC_INNOVUV_DIFF(dof, dof_diff, mesh&
&                                             )
        IF (use_qobs .EQ. 1) CALL CALC_INNOVQ_DIFF(dof, mesh)
        IF (.NOT.use_obs .EQ. 1) CALL UPDATE_COST_FUNCTION_DIFF(dof, &
&                                                         dof_diff, cost&
&                                                         , cost_diff)
        sub_nt = sub_nt + 1
      END IF
    END DO
  END SUBROUTINE SUB_RUN_MODEL_DIFF

  SUBROUTINE SUB_RUN_MODEL()

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    sub_nt = 0
    DO WHILE (.NOT.end_time_loop .AND. sub_nt .LT. max_nt_for_adjoint)
      CALL SET_BC(dof, mesh) ! Replaced by Perl Script
      CALL ADVANCE_TIME(dof, mesh) ! Replaced by Perl Script
      bc%sum_mass_flux(:) = 0._rp
      SELECT CASE (temp_scheme)
      CASE ('euler')
        SELECT CASE (spatial_scheme)
        CASE ('first_b1')
! Compiltation flags for porosity now added in euler_time_step_first_b1
          CALL EULER_TIME_STEP_FIRST_B1(dof, mesh, poro_unit, nt) ! Replaced by Perl Script
        CASE DEFAULT
          CALL STOPPING_PROGRAM_SUB('Unknow spatial scheme')
        END SELECT
      CASE DEFAULT
        CALL STOPPING_PROGRAM_SUB('Unknow temporal scheme')
      END SELECT
      CALL SW_POST_TREATMENT(dof, mesh) ! Replaced by Perl Script
      IF (use_obs .EQ. 1) THEN
        IF (use_zobs .EQ. 1) CALL CALC_INNOVATION(dof, mesh) ! Replaced by Perl Script
        IF (use_uvobs .EQ. 1) CALL CALC_INNOVUV(dof, mesh) ! Replaced by Perl Script
        IF (use_qobs .EQ. 1) CALL CALC_INNOVQ(dof, mesh) ! Replaced by Perl Script
        IF (.NOT.use_obs .EQ. 1) CALL UPDATE_COST_FUNCTION(dof, cost)
        sub_nt = sub_nt + 1
      END IF
    END DO
  END SUBROUTINE SUB_RUN_MODEL

END SUBROUTINE RUN_MODEL_DIFF

