!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 25 Jun 2025 16:38
!
!  Differentiation of run_model in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: *(*innovation.diff) *(*innovuv.diff)
!                *(dof.h) *(dof.u) *(dof.v) cost
!   with respect to varying inputs: *(*(bc.hyd).q) *xsshape.xcenter
!                *xsshape.s *xsshape.hmax *bathy_cell *(dof0.h)
!                *(dof0.u) *(dof0.v)
!   RW status of diff variables: *(infil.ga).psif:(loc) *(infil.ga).ks:(loc)
!                *(infil.ga).deltatheta:(loc) *(infil.scs).lambdacn:(loc)
!                *(infil.scs).cn:(loc) *manning:(loc) *ptf.kappa:(loc)
!                *(*(bc.hyd).t):(loc) *(*(bc.hyd).q):in *(*(bc.rat).h):(loc)
!                *(*(bc.rat).q):(loc) *(*(bc.rain).t):(loc) *(*(bc.rain).q):(loc)
!                *xsshape.xcenter:in *xsshape.s:in *xsshape.hmax:in
!                *bathy_cell:in-killed *manning_beta:(loc) *(sporosity.phi):(loc)
!                *(*innovation.diff):out *(*innovq.diff):(loc)
!                *(*innovw.diff):(loc) *(*innovuv.diff):out dof.h:(loc)
!                *(dof.h):out dof.u:(loc) *(dof.u):out dof.v:(loc)
!                *(dof.v):out *(dof.infil):(loc) dof.t_display:(loc)
!                *(dof.grad_h).x:(loc) *(dof.grad_h).y:(loc) *(dof.grad_u).x:(loc)
!                *(dof.grad_u).y:(loc) *(dof.grad_v).x:(loc) *(dof.grad_v).y:(loc)
!                *(dof.grad_z).x:(loc) *(dof.grad_z).y:(loc) *(mesh.node).coord.x:(loc)
!                *(mesh.node).coord.y:(loc) *(mesh.cell).surf:(loc)
!                *(mesh.cell).invsurf:(loc) *(mesh.cell).peri:(loc)
!                *(mesh.cell).grav.x:(loc) *(mesh.cell).grav.y:(loc)
!                *(mesh.cellb).grav.x:(loc) *(mesh.cellb).grav.y:(loc)
!                *(mesh.edge).length:(loc) *(mesh.edge).center.x:(loc)
!                *(mesh.edge).center.y:(loc) *(mesh.edge).normal.x:(loc)
!                *(mesh.edge).normal.y:(loc) *(mesh.edge).tangent.x:(loc)
!                *(mesh.edge).tangent.y:(loc) *(mesh.edge).vcell.x:(loc)
!                *(mesh.edge).vcell.y:(loc) *(mesh.edge).v_edge_cell.x:(loc)
!                *(mesh.edge).v_edge_cell.y:(loc) mesh.scal:(loc)
!                mesh.surf:(loc) cost:out dof0.h:(loc) *(dof0.h):in-killed
!                dof0.u:(loc) *(dof0.u):in dof0.v:(loc) *(dof0.v):in
!   Plus diff mem management of: bc.hyd:in *(bc.hyd).q:in xsshape:in
!                bathy_cell:in innovation:in *innovation.diff:in
!                innovuv:in *innovuv.diff:in dof.h:in-out dof.u:in-out
!                dof.v:in-out dof.infil:in-out dof.grad_h:in-out
!                dof.grad_u:in-out dof.grad_v:in-out dof.grad_z:in-out
!                mesh.node:in-out mesh.cell:in-out mesh.cellb:in-out
!                mesh.edge:in-out dof0.h:in dof0.u:in dof0.v:in
SUBROUTINE RUN_MODEL_DIFF(mesh, mesh_diff, dof0, dof0_diff, dof, &
& dof_diff, cost, cost_diff)
  USE M_COMMON
  USE M_LINEAR_ALGEBRA ! Replaced by Perl Script
  USE M_MESH ! Replaced by Perl Script
  USE M_MPI ! Replaced by Perl Script
  USE M_NUMERIC ! Replaced by Perl Script
  USE M_NUMERIC_DIFF
  USE M_MODEL ! Replaced by Perl Script
  USE M_OBS ! Replaced by Perl Script
  USE M_OBS_DIFF

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  TYPE(MSH), INTENT(INOUT) :: mesh
  TYPE(MSH), INTENT(INOUT) :: mesh_diff ! Replaced by Perl Script
  TYPE(UNK), INTENT(INOUT) :: dof0
  TYPE(UNK), INTENT(INOUT) :: dof0_diff
  TYPE(UNK), INTENT(INOUT) :: dof
  TYPE(UNK), INTENT(INOUT) :: dof_diff
  REAL(rp), INTENT(OUT) :: cost
  REAL(rp), INTENT(OUT) :: cost_diff
  INTEGER(ip) :: sub_nt, ir, il
  REAL(rp) :: bathy_temp
  REAL(rp) :: bathy_temp_diff
  REAL(rp) :: ks_ubound, ks_lbound, z, lambda, shift
  INTRINSIC ABS
  INTRINSIC MIN
  INTRINSIC SIZE
  INTRINSIC MAX
  REAL(rp) :: y1
  REAL(rp) :: y1_diff
  REAL(rp) :: y2
  REAL(rp) :: y2_diff
  REAL(rp) :: y3
  REAL(rp) :: y3_diff
  REAL(rp) :: y4
  REAL(rp) :: y4_diff
  REAL(rp) :: min1
  REAL(rp) :: min1_diff
  REAL(rp) :: min2
  REAL(rp) :: min2_diff
  REAL(rp) :: min3
  REAL(rp) :: min3_diff
  REAL(rp) :: min4
  REAL(rp) :: min4_diff
  REAL(rp) :: abs0
  REAL(rp) :: abs0_diff
  REAL(rp) :: abs1
  REAL(rp) :: abs1_diff
  REAL(rp) :: abs2
  REAL(rp) :: abs2_diff
  REAL(rp) :: abs3
  REAL(rp) :: abs3_diff
  REAL(rp) :: abs4
  REAL(rp) :: abs4_diff
  REAL(rp) :: abs5
  REAL(rp) :: abs5_diff
  REAL(rp) :: abs6
  REAL(rp) :: abs6_diff
  REAL(rp) :: abs7
  REAL(rp) :: abs7_diff
  REAL(rp) :: abs8
  REAL(rp) :: abs8_diff
  REAL(rp) :: abs9
  REAL(rp) :: abs9_diff
  REAL(rp) :: abs10
  REAL(rp) :: abs10_diff
  REAL(rp) :: abs11
  REAL(rp) :: abs11_diff
  REAL(rp) :: temp
  REAL(rp) :: temp0
  REAL(rp) :: temp_diff
  REAL(rp) :: temp_diff0
  INTEGER :: ii1
  IF (use_xsshp .EQ. 1) THEN
    IF (xsshp_along_y .EQ. 1) THEN
      DO ie=1,mesh%nc
        bathy_temp_diff = bathy_cell_diff(ie)
        bathy_temp = bathy_cell(ie)
        IF (mesh%cell(ie)%grav%x .LE. xsshape(1)%xcenter) THEN
          IF (xsshape(1)%hmax .GE. 0.) THEN
            abs0_diff = xsshape_diff(1)%hmax
            abs0 = xsshape(1)%hmax
          ELSE
            abs0_diff = -xsshape_diff(1)%hmax
            abs0 = -xsshape(1)%hmax
          END IF
          IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&             xcenter-xsshape(1)%xleft) .GE. 0.) THEN
            abs4_diff = -xsshape_diff(1)%xcenter
            abs4 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)&
&             %xcenter-xsshape(1)%xleft)
          ELSE
            abs4_diff = xsshape_diff(1)%xcenter
            abs4 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape(1)%&
&             xcenter-xsshape(1)%xleft))
          END IF
          IF (xsshape(1)%s .GE. 0.) THEN
            abs8_diff = xsshape_diff(1)%s
            abs8 = xsshape(1)%s
          ELSE
            abs8_diff = -xsshape_diff(1)%s
            abs8 = -xsshape(1)%s
          END IF
          temp = abs4/(xsshape(1)%xcenter-xsshape(1)%xleft)
          temp0 = temp**abs8
          IF (temp .LE. 0.0 .AND. (abs8 .EQ. 0.0 .OR. abs8 .NE. INT(abs8&
&             ))) THEN
            temp_diff = 0.0_8
          ELSE IF (temp .LE. 0.0) THEN
            temp_diff = abs8*temp**(abs8-1)*(abs4_diff-temp*xsshape_diff&
&             (1)%xcenter)/(xsshape(1)%xcenter-xsshape(1)%xleft)
          ELSE
            temp_diff = abs8*temp**(abs8-1)*(abs4_diff-temp*xsshape_diff&
&             (1)%xcenter)/(xsshape(1)%xcenter-xsshape(1)%xleft) + temp0&
&             *LOG(temp)*abs8_diff
          END IF
          y1_diff = -((1-temp0)*abs0_diff-abs0*temp_diff)
          y1 = -(abs0*(1-temp0))
          IF (0._rp .GT. y1) THEN
            min1_diff = y1_diff
            min1 = y1
          ELSE
            min1 = 0._rp
            min1_diff = 0.0_8
          END IF
          bathy_cell_diff(ie) = min1_diff + bathy_temp_diff
          bathy_cell(ie) = xsshape(1)%topz + min1 + bathy_temp + slope_y&
&           (1)*mesh%cell(ie)%grav%y + slope_x(1)*mesh%cell(ie)%grav%x
        ELSE
          IF (xsshape(1)%hmax .GE. 0.) THEN
            abs1_diff = xsshape_diff(1)%hmax
            abs1 = xsshape(1)%hmax
          ELSE
            abs1_diff = -xsshape_diff(1)%hmax
            abs1 = -xsshape(1)%hmax
          END IF
          IF (mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)%&
&             xcenter-xsshape(1)%xleft) .GE. 0.) THEN
            abs5_diff = -xsshape_diff(1)%xcenter
            abs5 = mesh%cell(ie)%grav%x - xsshape(1)%xleft - (xsshape(1)&
&             %xcenter-xsshape(1)%xleft)
          ELSE
            abs5_diff = xsshape_diff(1)%xcenter
            abs5 = -(mesh%cell(ie)%grav%x-xsshape(1)%xleft-(xsshape(1)%&
&             xcenter-xsshape(1)%xleft))
          END IF
          IF (xsshape(1)%s .GE. 0.) THEN
            abs9_diff = xsshape_diff(1)%s
            abs9 = xsshape(1)%s
          ELSE
            abs9_diff = -xsshape_diff(1)%s
            abs9 = -xsshape(1)%s
          END IF
          temp0 = abs5/(xsshape(1)%xright-xsshape(1)%xcenter)
          temp = temp0**abs9
          IF (temp0 .LE. 0.0 .AND. (abs9 .EQ. 0.0 .OR. abs9 .NE. INT(&
&             abs9))) THEN
            temp_diff0 = 0.0_8
          ELSE IF (temp0 .LE. 0.0) THEN
            temp_diff0 = abs9*temp0**(abs9-1)*(abs5_diff+temp0*&
&             xsshape_diff(1)%xcenter)/(xsshape(1)%xright-xsshape(1)%&
&             xcenter)
          ELSE
            temp_diff0 = abs9*temp0**(abs9-1)*(abs5_diff+temp0*&
&             xsshape_diff(1)%xcenter)/(xsshape(1)%xright-xsshape(1)%&
&             xcenter) + temp*LOG(temp0)*abs9_diff
          END IF
          y2_diff = -((1-temp)*abs1_diff-abs1*temp_diff0)
          y2 = -(abs1*(1-temp))
          IF (0._rp .GT. y2) THEN
            min2_diff = y2_diff
            min2 = y2
          ELSE
            min2 = 0._rp
            min2_diff = 0.0_8
          END IF
          bathy_cell_diff(ie) = min2_diff + bathy_temp_diff
          bathy_cell(ie) = xsshape(1)%topz + min2 + bathy_temp + slope_y&
&           (1)*mesh%cell(ie)%grav%y + slope_x(1)*mesh%cell(ie)%grav%x
        END IF
      END DO
    ELSE IF (xsshp_along_x .EQ. 1) THEN
      DO ie=1,mesh%nc
        bathy_temp_diff = bathy_cell_diff(ie)
        bathy_temp = bathy_cell(ie)
        IF (mesh%cell(ie)%grav%y .LE. xsshape(1)%xcenter) THEN
          IF (xsshape(1)%hmax .GE. 0.) THEN
            abs2_diff = xsshape_diff(1)%hmax
            abs2 = xsshape(1)%hmax
          ELSE
            abs2_diff = -xsshape_diff(1)%hmax
            abs2 = -xsshape(1)%hmax
          END IF
          IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&             xcenter-xsshape(1)%xleft) .GE. 0.) THEN
            abs6_diff = -xsshape_diff(1)%xcenter
            abs6 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)&
&             %xcenter-xsshape(1)%xleft)
          ELSE
            abs6_diff = xsshape_diff(1)%xcenter
            abs6 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape(1)%&
&             xcenter-xsshape(1)%xleft))
          END IF
          IF (xsshape(1)%s .GE. 0.) THEN
            abs10_diff = xsshape_diff(1)%s
            abs10 = xsshape(1)%s
          ELSE
            abs10_diff = -xsshape_diff(1)%s
            abs10 = -xsshape(1)%s
          END IF
          temp0 = abs6/(xsshape(1)%xcenter-xsshape(1)%xleft)
          temp = temp0**abs10
          IF (temp0 .LE. 0.0 .AND. (abs10 .EQ. 0.0 .OR. abs10 .NE. INT(&
&             abs10))) THEN
            temp_diff0 = 0.0_8
          ELSE IF (temp0 .LE. 0.0) THEN
            temp_diff0 = abs10*temp0**(abs10-1)*(abs6_diff-temp0*&
&             xsshape_diff(1)%xcenter)/(xsshape(1)%xcenter-xsshape(1)%&
&             xleft)
          ELSE
            temp_diff0 = abs10*temp0**(abs10-1)*(abs6_diff-temp0*&
&             xsshape_diff(1)%xcenter)/(xsshape(1)%xcenter-xsshape(1)%&
&             xleft) + temp*LOG(temp0)*abs10_diff
          END IF
          y3_diff = -((1-temp)*abs2_diff-abs2*temp_diff0)
          y3 = -(abs2*(1-temp))
          IF (0._rp .GT. y3) THEN
            min3_diff = y3_diff
            min3 = y3
          ELSE
            min3 = 0._rp
            min3_diff = 0.0_8
          END IF
          bathy_cell_diff(ie) = min3_diff + bathy_temp_diff
          bathy_cell(ie) = xsshape(1)%topz + min3 + bathy_temp + slope_y&
&           (1)*mesh%cell(ie)%grav%y + slope_x(1)*mesh%cell(ie)%grav%x
        ELSE
          IF (xsshape(1)%hmax .GE. 0.) THEN
            abs3_diff = xsshape_diff(1)%hmax
            abs3 = xsshape(1)%hmax
          ELSE
            abs3_diff = -xsshape_diff(1)%hmax
            abs3 = -xsshape(1)%hmax
          END IF
          IF (mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)%&
&             xcenter-xsshape(1)%xleft) .GE. 0.) THEN
            abs7_diff = -xsshape_diff(1)%xcenter
            abs7 = mesh%cell(ie)%grav%y - xsshape(1)%xleft - (xsshape(1)&
&             %xcenter-xsshape(1)%xleft)
          ELSE
            abs7_diff = xsshape_diff(1)%xcenter
            abs7 = -(mesh%cell(ie)%grav%y-xsshape(1)%xleft-(xsshape(1)%&
&             xcenter-xsshape(1)%xleft))
          END IF
          IF (xsshape(1)%s .GE. 0.) THEN
            abs11_diff = xsshape_diff(1)%s
            abs11 = xsshape(1)%s
          ELSE
            abs11_diff = -xsshape_diff(1)%s
            abs11 = -xsshape(1)%s
          END IF
          temp0 = abs7/(xsshape(1)%xright-xsshape(1)%xcenter)
          temp = temp0**abs11
          IF (temp0 .LE. 0.0 .AND. (abs11 .EQ. 0.0 .OR. abs11 .NE. INT(&
&             abs11))) THEN
            temp_diff0 = 0.0_8
          ELSE IF (temp0 .LE. 0.0) THEN
            temp_diff0 = abs11*temp0**(abs11-1)*(abs7_diff+temp0*&
&             xsshape_diff(1)%xcenter)/(xsshape(1)%xright-xsshape(1)%&
&             xcenter)
          ELSE
            temp_diff0 = abs11*temp0**(abs11-1)*(abs7_diff+temp0*&
&             xsshape_diff(1)%xcenter)/(xsshape(1)%xright-xsshape(1)%&
&             xcenter) + temp*LOG(temp0)*abs11_diff
          END IF
          y4_diff = -((1-temp)*abs3_diff-abs3*temp_diff0)
          y4 = -(abs3*(1-temp))
          IF (0._rp .GT. y4) THEN
            min4_diff = y4_diff
            min4 = y4
          ELSE
            min4 = 0._rp
            min4_diff = 0.0_8
          END IF
          bathy_cell_diff(ie) = min4_diff + bathy_temp_diff
          bathy_cell(ie) = xsshape(1)%topz + min4 + bathy_temp + slope_y&
&           (1)*mesh%cell(ie)%grav%y + slope_x(1)*mesh%cell(ie)%grav%x
        END IF
      END DO
    END IF
  END IF
  IF (use_ptf .EQ. 1) THEN
    IF (bc_infil .EQ. 1) THEN
      DO i=1,SIZE(phys_desc%soil)
!kg/m2 to m
        infil_diff%ga(i)%ks = 0.0_8
        infil%ga(i)%ks = 25.4_rp/3600._rp*10._rp**(-ptf(phys_desc%&
&         ptf_land(i))%kappa(7)-ptf(phys_desc%ptf_land(i))%kappa(8)*&
&         phys_desc%soil(i)%clay+ptf(phys_desc%ptf_land(i))%kappa(9)*&
&         phys_desc%soil(i)%sand)/1000._rp
      END DO
    ELSE IF (bc_infil .EQ. 2) THEN
      CALL STOPPING_PROGRAM_SUB('PTF for SCS-CN method not defined yet')
    END IF
  END IF
  INQUIRE(file='zs_init.txt', exist=file_exist(1)) 
  IF (file_exist(1)) THEN
    WRITE(*, *) 'Using zs_init.txt to initialize water depth'
    DO i=1,mesh%nc
      IF (0._rp .LT. dof0%h(i) - bathy_cell(i) + slope_y(1)*mesh%cell(i)&
&         %grav%y + slope_x(1)*mesh%cell(i)%grav%x) THEN
        dof0_diff%h(i) = dof0_diff%h(i) - bathy_cell_diff(i)
        dof0%h(i) = dof0%h(i) - bathy_cell(i) + slope_y(1)*mesh%cell(i)%&
&         grav%y + slope_x(1)*mesh%cell(i)%grav%x
      ELSE
        dof0_diff%h(i) = 0.0_8
        dof0%h(i) = 0._rp
      END IF
    END DO
  END IF
  dof_diff%h = 0.0_8
  dof_diff%h = dof0_diff%h
  dof%h = dof0%h
  dof_diff%u = 0.0_8
  dof_diff%u = dof0_diff%u
  dof%u = dof0%u
  dof_diff%v = 0.0_8
  dof_diff%v = dof0_diff%v
  dof%v = dof0%v
  tc = tc0
  nt = nt0
  IF (use_obs .EQ. 1) THEN
    IF (use_zobs .EQ. 1) innovation(:)%ind_t = 1_ip
    IF (use_uvobs .EQ. 1) innovuv(:)%ind_t = 1_ip
    IF (use_qobs .EQ. 1 .OR. use_qobs_gr4 .EQ. 1) innovq(:)%ind_t = 1_ip
  END IF
  IF (use_qobs .EQ. 1 .OR. use_qobs_gr4 .EQ. 1) innovq(:)%ind_t = 1_ip
  cost = 0._rp
  end_time_loop = .false.
  IF (ALLOCATED(innovation_diff)) THEN
    DO ii1=1,size(innovation,1)
      innovation_diff(ii1)%diff = 0.0_8
    END DO
  END IF
  IF (ALLOCATED(innovuv_diff)) THEN
    DO ii1=1,size(innovuv,1)
      innovuv_diff(ii1)%diff = 0.0_8
    END DO
  END IF
  dof_diff%infil = 0.0_8
  dof_diff%t_display = 0.0_8
  dof_diff%grad_h%x = 0.0_8
  dof_diff%grad_h%y = 0.0_8
  dof_diff%grad_u%x = 0.0_8
  dof_diff%grad_u%y = 0.0_8
  dof_diff%grad_v%x = 0.0_8
  dof_diff%grad_v%y = 0.0_8
  dof_diff%grad_z%x = 0.0_8
  dof_diff%grad_z%y = 0.0_8
  mesh_diff%node%coord%x = 0.0_8
  mesh_diff%node%coord%y = 0.0_8
  mesh_diff%cell%surf = 0.0_8
  mesh_diff%cell%invsurf = 0.0_8
  mesh_diff%cell%peri = 0.0_8
  mesh_diff%cell%grav%x = 0.0_8
  mesh_diff%cell%grav%y = 0.0_8
  mesh_diff%cellb%grav%x = 0.0_8
  mesh_diff%cellb%grav%y = 0.0_8
  mesh_diff%edge%length = 0.0_8
  mesh_diff%edge%center%x = 0.0_8
  mesh_diff%edge%center%y = 0.0_8
  mesh_diff%edge%normal%x = 0.0_8
  mesh_diff%edge%normal%y = 0.0_8
  mesh_diff%edge%tangent%x = 0.0_8
  mesh_diff%edge%tangent%y = 0.0_8
  mesh_diff%edge%vcell%x = 0.0_8
  mesh_diff%edge%vcell%y = 0.0_8
  DO ii1=1,size(mesh%edge,1)
    mesh_diff%edge(ii1)%v_edge_cell%x = 0.0_8
  END DO
  DO ii1=1,size(mesh%edge,1)
    mesh_diff%edge(ii1)%v_edge_cell%y = 0.0_8
  END DO
  mesh_diff%scal = 0.0_8
  mesh_diff%surf = 0.0_8
  cost_diff = 0.0_8
  DO WHILE (.NOT.end_time_loop)
    CALL SUB_RUN_MODEL_DIFF()
  END DO
  CALL CALC_COST_FUNCTION_DIFF(cost, cost_diff, mesh, mesh_diff)
  IF (ALLOCATED(innovq_diff)) THEN
    DO ii1=1,size(innovq,1)
      innovq_diff(ii1)%diff = 0.0_8
    END DO
  END IF
  IF (ALLOCATED(innovw_diff)) THEN
    DO ii1=1,size(innovw,1)
      innovw_diff(ii1)%diff = 0.0_8
    END DO
  END IF

CONTAINS
!  Differentiation of sub_run_model in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: *(*innovation.diff)[from module m_obs]
!                *(*innovuv.diff)[from module m_obs] *(dof.h) *(dof.u)
!                *(dof.v) *(dof.infil) dof.t_display *(dof.grad_h).x
!                *(dof.grad_h).y *(dof.grad_u).x *(dof.grad_u).y
!                *(dof.grad_v).x *(dof.grad_v).y *(dof.grad_z).x
!                *(dof.grad_z).y *(mesh.node).coord.x *(mesh.node).coord.y
!                *(mesh.cell).surf *(mesh.cell).invsurf *(mesh.cell).peri
!                *(mesh.cell).grav.x *(mesh.cell).grav.y *(mesh.cellb).grav.x
!                *(mesh.cellb).grav.y *(mesh.edge).length *(mesh.edge).center.x
!                *(mesh.edge).center.y *(mesh.edge).normal.x *(mesh.edge).normal.y
!                *(mesh.edge).tangent.x *(mesh.edge).tangent.y
!                *(mesh.edge).vcell.x *(mesh.edge).vcell.y *(mesh.edge).v_edge_cell.x
!                *(mesh.edge).v_edge_cell.y mesh.scal mesh.surf
!                cost
!   with respect to varying inputs: *bathy_cell[from module m_model]
!                *(*innovation.diff)[from module m_obs] *(*innovuv.diff)[from module m_obs]
!                *(dof.h) *(dof.u) *(dof.v) *(dof.infil) dof.t_display
!                *(dof.grad_h).x *(dof.grad_h).y *(dof.grad_u).x
!                *(dof.grad_u).y *(dof.grad_v).x *(dof.grad_v).y
!                *(dof.grad_z).x *(dof.grad_z).y *(mesh.node).coord.x
!                *(mesh.node).coord.y *(mesh.cell).surf *(mesh.cell).invsurf
!                *(mesh.cell).peri *(mesh.cell).grav.x *(mesh.cell).grav.y
!                *(mesh.cellb).grav.x *(mesh.cellb).grav.y *(mesh.edge).length
!                *(mesh.edge).center.x *(mesh.edge).center.y *(mesh.edge).normal.x
!                *(mesh.edge).normal.y *(mesh.edge).tangent.x *(mesh.edge).tangent.y
!                *(mesh.edge).vcell.x *(mesh.edge).vcell.y *(mesh.edge).v_edge_cell.x
!                *(mesh.edge).v_edge_cell.y mesh.scal mesh.surf
!                cost
!   Plus diff mem management of: bathy_cell[from module m_model]:in
!                innovation[from module m_obs]:in *innovation.diff[from module m_obs]:in
!                innovuv[from module m_obs]:in *innovuv.diff[from module m_obs]:in
!                dof.h:in-out dof.u:in-out dof.v:in-out dof.infil:in-out
!                dof.grad_h:in-out dof.grad_u:in-out dof.grad_v:in-out
!                dof.grad_z:in-out mesh.node:in-out mesh.cell:in-out
!                mesh.cellb:in-out mesh.edge:in-out
  SUBROUTINE SUB_RUN_MODEL_DIFF()

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    EXTERNAL EULER_TIME_STEP_FIRST_B1
    EXTERNAL EULER_TIME_STEP_FIRST_B1_DIFF
    sub_nt = 0
    DO WHILE (.NOT.end_time_loop .AND. sub_nt .LT. max_nt_for_adjoint)
      CALL SET_BC_DIFF(dof, dof_diff, mesh, mesh_diff)
      CALL ADVANCE_TIME(dof, mesh) ! Replaced by Perl Script
      bc%sum_mass_flux(:) = 0._rp
      SELECT CASE (temp_scheme)
      CASE ('euler')
        SELECT CASE (spatial_scheme)
        CASE ('first_b1')
! Compiltation flags for porosity now added in euler_time_step_first_b1
          CALL EULER_TIME_STEP_FIRST_B1_DIFF(dof, dof_diff, mesh, &
&                                      mesh_diff)
        CASE DEFAULT
          CALL STOPPING_PROGRAM_SUB('Unknow spatial scheme')
        END SELECT
      CASE DEFAULT
        CALL STOPPING_PROGRAM_SUB('Unknow temporal scheme')
      END SELECT
      CALL SW_POST_TREATMENT(dof, mesh) ! Replaced by Perl Script
      IF (use_obs .EQ. 1) THEN
        IF (use_zobs .EQ. 1) CALL CALC_INNOVATION_DIFF(dof, dof_diff, &
&                                                mesh, mesh_diff)
        IF (use_uvobs .EQ. 1) CALL CALC_INNOVUV_DIFF(dof, dof_diff, mesh&
&                                              , mesh_diff)
        IF (use_qobs .EQ. 1) CALL CALC_INNOVQ(dof, mesh) ! Replaced by Perl Script
        IF (.NOT.use_obs .EQ. 1) CALL UPDATE_COST_FUNCTION_DIFF(dof, &
&                                                         dof_diff, cost&
&                                                         , cost_diff)
        sub_nt = sub_nt + 1
      END IF
    END DO
  END SUBROUTINE SUB_RUN_MODEL_DIFF

  SUBROUTINE SUB_RUN_MODEL()

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

    IMPLICIT NONE
    EXTERNAL EULER_TIME_STEP_FIRST_B1
    sub_nt = 0
    DO WHILE (.NOT.end_time_loop .AND. sub_nt .LT. max_nt_for_adjoint)
      CALL SET_BC(dof, mesh) ! Replaced by Perl Script
      CALL ADVANCE_TIME(dof, mesh) ! Replaced by Perl Script
      bc%sum_mass_flux(:) = 0._rp
      SELECT CASE (temp_scheme)
      CASE ('euler')
        SELECT CASE (spatial_scheme)
        CASE ('first_b1')
! Compiltation flags for porosity now added in euler_time_step_first_b1
          CALL EULER_TIME_STEP_FIRST_B1(dof, mesh)
        CASE DEFAULT
          CALL STOPPING_PROGRAM_SUB('Unknow spatial scheme')
        END SELECT
      CASE DEFAULT
        CALL STOPPING_PROGRAM_SUB('Unknow temporal scheme')
      END SELECT
      CALL SW_POST_TREATMENT(dof, mesh) ! Replaced by Perl Script
      IF (use_obs .EQ. 1) THEN
        IF (use_zobs .EQ. 1) CALL CALC_INNOVATION(dof, mesh) ! Replaced by Perl Script
        IF (use_uvobs .EQ. 1) CALL CALC_INNOVUV(dof, mesh) ! Replaced by Perl Script
        IF (use_qobs .EQ. 1) CALL CALC_INNOVQ(dof, mesh) ! Replaced by Perl Script
        IF (.NOT.use_obs .EQ. 1) CALL UPDATE_COST_FUNCTION(dof, cost)
        sub_nt = sub_nt + 1
      END IF
    END DO
  END SUBROUTINE SUB_RUN_MODEL

END SUBROUTINE RUN_MODEL_DIFF

