!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 25 Jun 2025 16:38
!
!  Differentiation of set_bc in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: *(dof.h)
!   with respect to varying inputs: *(dof.h)
!   Plus diff mem management of: dof.h:in mesh.edge:in
SUBROUTINE SET_BC_DIFF(dof, dof_diff, mesh, mesh_diff)
  USE M_NUMERIC ! Replaced by Perl Script
  USE M_NUMERIC_DIFF
  USE M_MODEL ! Replaced by Perl Script
  USE M_MPI ! Replaced by Perl Script

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  TYPE(MSH), INTENT(IN) :: mesh
  TYPE(MSH), INTENT(IN) :: mesh_diff ! Replaced by Perl Script
  TYPE(UNK), INTENT(INOUT) :: dof
  TYPE(UNK), INTENT(INOUT) :: dof_diff
  REAL(rp) :: sum_pow_h, zin, qin, qout
  INTEGER(ip) :: num_bc, up_num_bc, down_num_bc, connected_num_bc
  INTRINSIC SIZE
  INTRINSIC MAX
  REAL(rp) :: y1
  REAL(rp) :: y2
  REAL(rp) :: max1
  bc%inflow = zero
  bc%outflow = zero
  DO num_bc=1,bc%nb
    IF (bc%typ(num_bc, 1) .EQ. 'discharg1') THEN
      IF (bc%typ(num_bc, 2) .EQ. 'file') THEN
        IF (SIZE(bc%hyd(bc%grpf(num_bc))%t) .GT. 1) THEN
          qin = LINEAR_INTERP(bc%hyd(bc%grpf(num_bc))%t, bc%hyd(bc%grpf(&
&           num_bc))%q, tc)
        ELSE
          qin = bc%hyd(bc%grpf(num_bc))%q(1)
        END IF
      END IF
!write(*,*) " bc%typ(num_bc,2) == 'file'  must be fill to define qin bc"
      sum_pow_h = zero
      DO ib=1,mesh%neb
        IF (mesh%edgeb(ib)%typlim .EQ. 'discharg1' .AND. mesh%edgeb(ib)%&
&           group .EQ. num_bc) THEN
          ie = mesh%edgeb(ib)%ind
          i = mesh%edge(ie)%cell(1)
!To review before merge
          IF (dof%h(i) .LE. heps) THEN
            dof_diff%h(i) = 0.0_8
            dof%h(i) = 0.0001
          END IF
          IF (dof%h(i) .GT. heps) sum_pow_h = sum_pow_h + dof%h(i)**d5p3&
&             *mesh%edge(ie)%length
        END IF
      END DO
      CALL MPI_SUM_R(sum_pow_h)
      DO ib=1,mesh%neb
        IF (mesh%edgeb(ib)%typlim .EQ. 'discharg1' .AND. mesh%edgeb(ib)%&
&           group .EQ. num_bc) THEN
          ie = mesh%edgeb(ib)%ind
          i = mesh%edge(ie)%cell(1)
          IF (dof%h(i) .GT. heps) THEN
            bc%inflow(ib) = -(qin*dof%h(i)**d2p3/sum_pow_h)
            bc%inflow(mesh%neb+ib) = dof%h(i)*bc%inflow(ib)
          END IF
        END IF
      END DO
    END IF
    IF (bc%typ(num_bc, 1) .EQ. 'discharg2') THEN
      IF (bc%typ(num_bc, 2) .EQ. 'file') qin = LINEAR_INTERP(bc%hyd(bc%&
&         grpf(num_bc))%t, bc%hyd(bc%grpf(num_bc))%q, tc)
!write(*,*) " bc%typ(num_bc,2) == 'file'  must be fill to define qin bc"
      CALL NEWTON_QIN(qin, dof, mesh, zin) ! Replaced by Perl Script
      DO ib=1,mesh%neb
        IF (mesh%edgeb(ib)%typlim .EQ. 'discharg2' .AND. mesh%edgeb(ib)%&
&           group .EQ. num_bc) THEN
          ie = mesh%edgeb(ib)%ind
          i = mesh%edge(ie)%cell(1)
          j = mesh%edge(ie)%cell(2)
          IF (dof%h(i) .GT. heps) THEN
            IF (0._rp .LT. zin - bathy_cell(j)) THEN
              bc%inflow(ib) = zin - bathy_cell(j)
            ELSE
              bc%inflow(ib) = 0._rp
            END IF
          END IF
        END IF
      END DO
    END IF
    IF (bc%typ(num_bc, 1) .EQ. 'ratcurve') THEN
      IF (nt .EQ. 0) THEN
        qout = zero
        DO ib=1,mesh%neb
          IF (mesh%edgeb(ib)%typlim .EQ. 'ratcurve' .AND. mesh%edgeb(ib)&
&             %group .EQ. num_bc) THEN
            ie = mesh%edgeb(ib)%ind
            i = mesh%edge(ie)%cell(1)
            qout = qout + dof%h(i)*(dof%u(i)*mesh%edge(ie)%normal%x+dof%&
&             v(i)*mesh%edge(ie)%normal%y)*mesh%edge(ie)%length
          END IF
        END DO
        CALL MPI_SUM_R(qout)
        y1 = LINEAR_INTERP(bc%rat(bc%grpf(num_bc))%q, bc%rat(bc%grpf(&
&         num_bc))%h, qout)
        IF (0._rp .LT. y1) THEN
          bc%rat(bc%grpf(num_bc))%zout = y1
        ELSE
          bc%rat(bc%grpf(num_bc))%zout = 0._rp
        END IF
      ELSE
        y2 = LINEAR_INTERP(bc%rat(bc%grpf(num_bc))%q, bc%rat(bc%grpf(&
&         num_bc))%h, bc%sum_mass_flux(num_bc))
        IF (0._rp .LT. y2) THEN
          max1 = y2
        ELSE
          max1 = 0._rp
        END IF
        bc%rat(bc%grpf(num_bc))%zout = 0.95_rp*bc%rat(bc%grpf(num_bc))%&
&         zout + 0.05_rp*max1
      END IF
      sum_pow_h = zero
      DO ib=1,mesh%neb
        IF (mesh%edgeb(ib)%typlim .EQ. 'ratcurve' .AND. mesh%edgeb(ib)%&
&           group .EQ. num_bc) THEN
          ie = mesh%edgeb(ib)%ind
          i = mesh%edge(ie)%cell(1)
          j = mesh%edge(ie)%cell(2)
          IF (0._rp .LT. bc%rat(bc%grpf(num_bc))%zout - bathy_cell(j) + &
&             bc%rat(bc%grpf(num_bc))%z_rat_ref) THEN
            bc%outflow(ib) = bc%rat(bc%grpf(num_bc))%zout - bathy_cell(j&
&             ) + bc%rat(bc%grpf(num_bc))%z_rat_ref
          ELSE
            bc%outflow(ib) = 0._rp
          END IF
          sum_pow_h = sum_pow_h + bc%outflow(ib)**d5p3*mesh%edge(ie)%&
&           length
        END IF
      END DO
      CALL MPI_SUM_R(sum_pow_h)
      IF (sum_pow_h .GT. zerom) THEN
        DO ib=1,mesh%neb
          IF (mesh%edgeb(ib)%typlim .EQ. 'ratcurve' .AND. mesh%edgeb(ib)&
&             %group .EQ. num_bc) THEN
            ie = mesh%edgeb(ib)%ind
            i = mesh%edge(ie)%cell(1)
            j = mesh%edge(ie)%cell(2)
            qout = LINEAR_INTERP(bc%rat(bc%grpf(num_bc))%h(:), bc%rat(bc&
&             %grpf(num_bc))%q(:), bc%rat(bc%grpf(num_bc))%zout)
            bc%outflow(mesh%neb+ib) = bc%outflow(ib)**d2p3*qout/&
&             sum_pow_h
          END IF
        END DO
      END IF
    END IF
  END DO
  IF (bc_rain .EQ. 1) THEN
    DO i=1,bc%nb_rn
      bc%rain(i)%qin = LINEAR_INTERP(bc%rain(i)%t, bc%rain(i)%q, tc)
    END DO
  END IF
END SUBROUTINE SET_BC_DIFF

