!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!  Differentiation of sw_hllc in forward (tangent) mode (with options fixinterface noISIZE):
!   variations   of useful results: flux
!   with respect to varying inputs: flux hl ul hr ur vl vr
SUBROUTINE SW_HLLC_DIFF(hl, hl_diff, ul, ul_diff, vl, vl_diff, hr, &
& hr_diff, ur, ur_diff, vr, vr_diff, flux, flux_diff)
  USE M_COMMON ! Replaced by Perl Script
  USE M_MODEL ! Replaced by Perl Script

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  REAL(rp), INTENT(IN) :: hl, ul, vl
  REAL(rp), INTENT(IN) :: hl_diff, ul_diff, vl_diff
  REAL(rp), INTENT(IN) :: hr, ur, vr
  REAL(rp), INTENT(IN) :: hr_diff, ur_diff, vr_diff
  REAL(rp), DIMENSION(3), INTENT(OUT) :: flux
  REAL(rp), DIMENSION(3), INTENT(OUT) :: flux_diff
  REAL(rp) :: sl, sr, sm, cl, cr
  REAL(rp) :: sl_diff, sr_diff, cl_diff, cr_diff
  REAL(rp), DIMENSION(3) :: fl, fr
  REAL(rp), DIMENSION(3) :: fl_diff, fr_diff
  INTRINSIC SQRT
  INTRINSIC MIN
  INTRINSIC MAX
  REAL(rp) :: temp
  temp = SQRT(g*hl)
  IF (g*hl .EQ. 0.0) THEN
    cl_diff = 0.0_8
  ELSE
    cl_diff = g*hl_diff/(2.0*temp)
  END IF
  cl = temp
  temp = SQRT(g*hr)
  IF (g*hr .EQ. 0.0) THEN
    cr_diff = 0.0_8
  ELSE
    cr_diff = g*hr_diff/(2.0*temp)
  END IF
  cr = temp
  IF (0._rp .GT. ul - cl) THEN
    IF (ul - cl .GT. ur - 2._rp*cr + cl) THEN
      sl_diff = ur_diff - 2._rp*cr_diff + cl_diff
      sl = ur - 2._rp*cr + cl
    ELSE
      sl_diff = ul_diff - cl_diff
      sl = ul - cl
    END IF
  ELSE IF (0._rp .GT. ur - 2._rp*cr + cl) THEN
    sl_diff = ur_diff - 2._rp*cr_diff + cl_diff
    sl = ur - 2._rp*cr + cl
  ELSE
    sl = 0._rp
    sl_diff = 0.0_8
  END IF
  IF (0._rp .LT. ur + cr) THEN
    IF (ur + cr .LT. ul + 2._rp*cl - cr) THEN
      sr_diff = ul_diff + 2._rp*cl_diff - cr_diff
      sr = ul + 2._rp*cl - cr
    ELSE
      sr_diff = ur_diff + cr_diff
      sr = ur + cr
    END IF
  ELSE IF (0._rp .LT. ul + 2._rp*cl - cr) THEN
    sr_diff = ul_diff + 2._rp*cl_diff - cr_diff
    sr = ul + 2._rp*cl - cr
  ELSE
    sr = 0._rp
    sr_diff = 0.0_8
  END IF
  IF ((sl .GT. -zerom .AND. sr .LT. zerom) .OR. (hl .LT. zerom .AND. hr &
&     .LT. zerom)) THEN
    flux(1:3) = 0._rp
    flux_diff = 0.0_8
    RETURN
  ELSE
    fl_diff = 0.0_8
    fl_diff(1) = ul*hl_diff + hl*ul_diff
    fl(1) = hl*ul
    fl_diff(2) = (ul**2+g*0.5_rp*2*hl)*hl_diff + hl*2*ul*ul_diff
    fl(2) = hl*ul*ul + 0.5_rp*g*hl*hl
    fr_diff = 0.0_8
    fr_diff(1) = ur*hr_diff + hr*ur_diff
    fr(1) = hr*ur
    fr_diff(2) = (ur**2+g*0.5_rp*2*hr)*hr_diff + hr*2*ur*ur_diff
    fr(2) = hr*ur*ur + 0.5_rp*g*hr*hr
    flux_diff(1) = fl(1)*sr_diff + sr*fl_diff(1) - fr(1)*sl_diff - sl*&
&     fr_diff(1) + (hr-hl)*(sr*sl_diff+sl*sr_diff) + sl*sr*(hr_diff-&
&     hl_diff)
    flux(1) = sr*fl(1) - sl*fr(1) + sl*sr*(hr-hl)
    flux_diff(2) = fl(2)*sr_diff + sr*fl_diff(2) - fr(2)*sl_diff - sl*&
&     fr_diff(2) + (fr(1)-fl(1))*(sr*sl_diff+sl*sr_diff) + sl*sr*(&
&     fr_diff(1)-fl_diff(1))
    flux(2) = sr*fl(2) - sl*fr(2) + sl*sr*(fr(1)-fl(1))
    flux_diff(1:2) = (flux_diff(1:2)-flux(1:2)*(sr_diff-sl_diff)/(sr-sl)&
&     )/(sr-sl)
    flux(1:2) = flux(1:2)/(sr-sl)
    sm = (sl*hr*ur-sr*hl*ul-sl*sr*(hr-hl))/(hr*(ur-sr)-hl*(ul-sl))
    IF (sm .LT. 0._rp) THEN
      flux_diff(3) = vr*flux_diff(1) + flux(1)*vr_diff
      flux(3) = flux(1)*vr
    ELSE IF (sm .GT. 0._rp) THEN
      flux_diff(3) = vl*flux_diff(1) + flux(1)*vl_diff
      flux(3) = flux(1)*vl
    ELSE
      flux_diff(3) = demi*((vl+vr)*flux_diff(1)+flux(1)*(vl_diff+vr_diff&
&       ))
      flux(3) = flux(1)*demi*(vl+vr)
    END IF
  END IF
END SUBROUTINE SW_HLLC_DIFF

