!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Apr 2025 13:39
!
!  Differentiation of sw_hllc_impervious_sp in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: hl ul hr ur s2l s2r
!   with respect to varying inputs: phir hl ul hr ur phil
SUBROUTINE SW_HLLC_IMPERVIOUS_SP_BACK(hl, hl_back, ul, ul_back, vl, zl, &
& phil, phil_back, s2l, s2l_back, hr, hr_back, ur, ur_back, vr, zr, phir&
& , phir_back, s2r, s2r_back, flux)
  USE M_COMMON ! Replaced by Perl Script
  USE M_MODEL ! Replaced by Perl Script

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  REAL(rp), INTENT(IN) :: hl, ul, vl, zl, phil
  REAL(rp) :: hl_back, ul_back, phil_back
  REAL(rp), INTENT(IN) :: hr, ur, vr, zr, phir
  REAL(rp) :: hr_back, ur_back, phir_back
  REAL(rp), DIMENSION(3) :: flux
  REAL(rp) :: s2l, s2r
  REAL(rp) :: s2l_back, s2r_back
  REAL(rp) :: sl, sr, cl, cr
  REAL(rp) :: sl_back, sr_back, cl_back, cr_back
  REAL(rp), DIMENSION(3) :: fl, fr
  REAL(rp), DIMENSION(3) :: fl_back, fr_back
  INTRINSIC SQRT
  INTRINSIC MIN
  INTRINSIC MAX
  REAL(rp) :: temp_back
  INTEGER*4 :: branch
  cl = SQRT(g*hl)
  cr = SQRT(g*hr)
  IF (0._rp .GT. ul - cl) THEN
    IF (ul - cl .GT. ur - 2._rp*cr + cl) THEN
      sl = ur - 2._rp*cr + cl
      CALL PUSHCONTROL2B(0)
    ELSE
      sl = ul - cl
      CALL PUSHCONTROL2B(1)
    END IF
  ELSE IF (0._rp .GT. ur - 2._rp*cr + cl) THEN
    sl = ur - 2._rp*cr + cl
    CALL PUSHCONTROL2B(2)
  ELSE
    CALL PUSHCONTROL2B(3)
    sl = 0._rp
  END IF
  IF (0._rp .LT. ur + cr) THEN
    IF (ur + cr .LT. ul + 2._rp*cl - cr) THEN
      sr = ul + 2._rp*cl - cr
      CALL PUSHCONTROL2B(0)
    ELSE
      sr = ur + cr
      CALL PUSHCONTROL2B(1)
    END IF
  ELSE IF (0._rp .LT. ul + 2._rp*cl - cr) THEN
    sr = ul + 2._rp*cl - cr
    CALL PUSHCONTROL2B(2)
  ELSE
    sr = 0._rp
    CALL PUSHCONTROL2B(3)
  END IF
  fl(1) = hl*ul
  fl(2) = hl*ul*ul + 0.5_rp*g*hl*hl
  fr(1) = hr*ur
  fr(2) = hr*ur*ur + 0.5_rp*g*hr*hr
  fr_back = 0.0_8
  phir_back = ((ur-sr)*fr(1)+demi*g*hr**2)*s2r_back
  temp_back = phir*s2r_back
  sr_back = -(fr(1)*temp_back)
  fr_back(1) = fr_back(1) + (ur-sr)*temp_back
  ur_back = ur_back + fr(1)*temp_back + 2*ur*hr*fr_back(2) + hr*fr_back(&
&   1)
  hr_back = hr_back + 2*hr*demi*g*temp_back + (ur**2+2*hr*g*0.5_rp)*&
&   fr_back(2) + ur*fr_back(1)
  fl_back = 0.0_8
  phil_back = ((sl-ul)*fl(1)-demi*g*hl**2)*s2l_back
  temp_back = phil*s2l_back
  sl_back = fl(1)*temp_back
  fl_back(1) = fl_back(1) + (sl-ul)*temp_back
  ul_back = ul_back + 2*ul*hl*fl_back(2) - fl(1)*temp_back + hl*fl_back(&
&   1)
  hl_back = hl_back + (ul**2+2*hl*g*0.5_rp)*fl_back(2) - 2*hl*demi*g*&
&   temp_back + ul*fl_back(1)
  fr_back(2) = 0.0_8
  fl_back(2) = 0.0_8
  CALL POPCONTROL2B(branch)
  IF (branch .LT. 2) THEN
    IF (branch .EQ. 0) THEN
      ul_back = ul_back + sr_back
      cl_back = 2._rp*sr_back
      cr_back = -sr_back
    ELSE
      ur_back = ur_back + sr_back
      cr_back = sr_back
      cl_back = 0.0_8
    END IF
  ELSE IF (branch .EQ. 2) THEN
    ul_back = ul_back + sr_back
    cl_back = 2._rp*sr_back
    cr_back = -sr_back
  ELSE
    cl_back = 0.0_8
    cr_back = 0.0_8
  END IF
  CALL POPCONTROL2B(branch)
  IF (branch .LT. 2) THEN
    IF (branch .EQ. 0) THEN
      ur_back = ur_back + sl_back
      cr_back = cr_back - 2._rp*sl_back
      cl_back = cl_back + sl_back
    ELSE
      ul_back = ul_back + sl_back
      cl_back = cl_back - sl_back
    END IF
  ELSE IF (branch .EQ. 2) THEN
    ur_back = ur_back + sl_back
    cr_back = cr_back - 2._rp*sl_back
    cl_back = cl_back + sl_back
  END IF
  IF (.NOT.g*hr .EQ. 0.0) hr_back = hr_back + g*cr_back/(2.0*SQRT(g*hr))
  IF (.NOT.g*hl .EQ. 0.0) hl_back = hl_back + g*cl_back/(2.0*SQRT(g*hl))
END SUBROUTINE SW_HLLC_IMPERVIOUS_SP_BACK

