!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 26 Mar 2024 17:10
!
!  Differentiation of sw_hllc_impervious_sp in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: s2l s2r
!   with respect to varying inputs: phir hl ul hr ur phil
SUBROUTINE SW_HLLC_IMPERVIOUS_SP_DIFF(hl, hl_diff, ul, ul_diff, vl, zl, &
& phil, phil_diff, s2l, s2l_diff, hr, hr_diff, ur, ur_diff, vr, zr, phir&
& , phir_diff, s2r, s2r_diff, flux)
  USE M_COMMON ! Replaced by Perl Script
  USE M_MODEL ! Replaced by Perl Script

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  REAL(rp), INTENT(IN) :: hl, ul, vl, zl, phil
  REAL(rp), INTENT(IN) :: hl_diff, ul_diff, phil_diff
  REAL(rp), INTENT(IN) :: hr, ur, vr, zr, phir
  REAL(rp), INTENT(IN) :: hr_diff, ur_diff, phir_diff
  REAL(rp), DIMENSION(3), INTENT(OUT) :: flux
  REAL(rp), INTENT(OUT) :: s2l, s2r
  REAL(rp), INTENT(OUT) :: s2l_diff, s2r_diff
  REAL(rp) :: sl, sr, cl, cr
  REAL(rp) :: sl_diff, sr_diff, cl_diff, cr_diff
  REAL(rp), DIMENSION(3) :: fl, fr
  REAL(rp), DIMENSION(3) :: fl_diff, fr_diff
  INTRINSIC SQRT
  INTRINSIC MIN
  INTRINSIC MAX
  REAL(rp) :: temp
  temp = SQRT(g*hl)
  IF (g*hl .EQ. 0.0) THEN
    cl_diff = 0.0_8
  ELSE
    cl_diff = g*hl_diff/(2.0*temp)
  END IF
  cl = temp
  temp = SQRT(g*hr)
  IF (g*hr .EQ. 0.0) THEN
    cr_diff = 0.0_8
  ELSE
    cr_diff = g*hr_diff/(2.0*temp)
  END IF
  cr = temp
  IF (0._rp .GT. ul - cl) THEN
    IF (ul - cl .GT. ur - 2._rp*cr + cl) THEN
      sl_diff = ur_diff - 2._rp*cr_diff + cl_diff
      sl = ur - 2._rp*cr + cl
    ELSE
      sl_diff = ul_diff - cl_diff
      sl = ul - cl
    END IF
  ELSE IF (0._rp .GT. ur - 2._rp*cr + cl) THEN
    sl_diff = ur_diff - 2._rp*cr_diff + cl_diff
    sl = ur - 2._rp*cr + cl
  ELSE
    sl = 0._rp
    sl_diff = 0.0_8
  END IF
  IF (0._rp .LT. ur + cr) THEN
    IF (ur + cr .LT. ul + 2._rp*cl - cr) THEN
      sr_diff = ul_diff + 2._rp*cl_diff - cr_diff
      sr = ul + 2._rp*cl - cr
    ELSE
      sr_diff = ur_diff + cr_diff
      sr = ur + cr
    END IF
  ELSE IF (0._rp .LT. ul + 2._rp*cl - cr) THEN
    sr_diff = ul_diff + 2._rp*cl_diff - cr_diff
    sr = ul + 2._rp*cl - cr
  ELSE
    sr = 0._rp
    sr_diff = 0.0_8
  END IF
  fl_diff = 0.0_8
  fl_diff(1) = ul*hl_diff + hl*ul_diff
  fl(1) = hl*ul
  fl_diff(2) = (ul**2+g*0.5_rp*2*hl)*hl_diff + hl*2*ul*ul_diff
  fl(2) = hl*ul*ul + 0.5_rp*g*hl*hl
  fr_diff = 0.0_8
  fr_diff(1) = ur*hr_diff + hr*ur_diff
  fr(1) = hr*ur
  fr_diff(2) = (ur**2+g*0.5_rp*2*hr)*hr_diff + hr*2*ur*ur_diff
  fr(2) = hr*ur*ur + 0.5_rp*g*hr*hr
  flux(:) = 0.
  temp = (sl-ul)*fl(1) - demi*g*(hl*hl)
  s2l_diff = temp*phil_diff + phil*(fl(1)*(sl_diff-ul_diff)+(sl-ul)*&
&   fl_diff(1)-demi*g*2*hl*hl_diff)
  s2l = phil*temp
  temp = (ur-sr)*fr(1) + demi*g*(hr*hr)
  s2r_diff = temp*phir_diff + phir*(fr(1)*(ur_diff-sr_diff)+(ur-sr)*&
&   fr_diff(1)+demi*g*2*hr*hr_diff)
  s2r = phir*temp
END SUBROUTINE SW_HLLC_IMPERVIOUS_SP_DIFF

