!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Apr 2025 13:39
!
!  Differentiation of sw_hllc_sp in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: flux s2l s2r
!   with respect to varying inputs: phir flux hl ul hr ur vl vr
!                s2l s2r zl zr phil
SUBROUTINE SW_HLLC_SP_DIFF(hl, hl_diff, ul, ul_diff, vl, vl_diff, zl, &
& zl_diff, phil, phil_diff, s2l, s2l_diff, hr, hr_diff, ur, ur_diff, vr&
& , vr_diff, zr, zr_diff, phir, phir_diff, s2r, s2r_diff, flux, &
& flux_diff)
  USE M_COMMON ! Replaced by Perl Script
  USE M_MODEL ! Replaced by Perl Script

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  REAL(rp), INTENT(IN) :: hl, ul, vl, zl, phil
  REAL(rp), INTENT(IN) :: hl_diff, ul_diff, vl_diff, zl_diff, phil_diff
  REAL(rp), INTENT(IN) :: hr, ur, vr, zr, phir
  REAL(rp), INTENT(IN) :: hr_diff, ur_diff, vr_diff, zr_diff, phir_diff
  REAL(rp), DIMENSION(3), INTENT(OUT) :: flux
  REAL(rp), DIMENSION(3), INTENT(OUT) :: flux_diff
  REAL(rp), INTENT(OUT) :: s2l, s2r
  REAL(rp), INTENT(OUT) :: s2l_diff, s2r_diff
  REAL(rp) :: sl, sr, s2, cl, cr
  REAL(rp) :: sl_diff, sr_diff, s2_diff, cl_diff, cr_diff
  REAL(rp), DIMENSION(3) :: fl, fr
  REAL(rp), DIMENSION(3) :: fl_diff, fr_diff
  REAL(rp) :: philr, fact
  REAL(rp) :: philr_diff, fact_diff
  INTRINSIC SQRT
  INTRINSIC MIN
  INTRINSIC MAX
  REAL(rp) :: max1
  REAL(rp) :: max1_diff
  REAL(rp) :: max2
  REAL(rp) :: max2_diff
  REAL(rp) :: temp
  REAL(rp) :: temp0
  REAL(rp) :: temp1
  temp = SQRT(g*hl)
  IF (g*hl .EQ. 0.0) THEN
    cl_diff = 0.0_8
  ELSE
    cl_diff = g*hl_diff/(2.0*temp)
  END IF
  cl = temp
  temp = SQRT(g*hr)
  IF (g*hr .EQ. 0.0) THEN
    cr_diff = 0.0_8
  ELSE
    cr_diff = g*hr_diff/(2.0*temp)
  END IF
  cr = temp
  IF (0._rp .GT. ul - cl) THEN
    IF (ul - cl .GT. ur - cr) THEN
      sl_diff = ur_diff - cr_diff
      sl = ur - cr
    ELSE
      sl_diff = ul_diff - cl_diff
      sl = ul - cl
    END IF
  ELSE IF (0._rp .GT. ur - cr) THEN
    sl_diff = ur_diff - cr_diff
    sl = ur - cr
  ELSE
    sl = 0._rp
    sl_diff = 0.0_8
  END IF
  IF (0._rp .LT. ur + cr) THEN
    IF (ur + cr .LT. ul + cl) THEN
      sr_diff = ul_diff + cl_diff
      sr = ul + cl
    ELSE
      sr_diff = ur_diff + cr_diff
      sr = ur + cr
    END IF
  ELSE IF (0._rp .LT. ul + cl) THEN
    sr_diff = ul_diff + cl_diff
    sr = ul + cl
  ELSE
    sr = 0._rp
    sr_diff = 0.0_8
  END IF
  IF ((sl .GT. -zerom .AND. sr .LT. zerom) .OR. (hl .LT. zerom .AND. hr &
&     .LT. zerom)) THEN
    flux(1:3) = 0._rp
    flux_diff = 0.0_8
    RETURN
  ELSE
    IF (phil .GT. phir) THEN
      philr_diff = phir_diff
      philr = phir
    ELSE
      philr_diff = phil_diff
      philr = phil
    END IF
    fact_diff = demi*((hl+hr)*philr_diff+philr*(hl_diff+hr_diff))
    fact = demi*philr*(hl+hr)
    fl_diff = 0.0_8
    fl_diff(1) = ul*hl_diff + hl*ul_diff
    fl(1) = hl*ul
    fl_diff(2) = (ul**2+g*0.5_rp*2*hl)*hl_diff + hl*2*ul*ul_diff
    fl(2) = hl*ul*ul + 0.5_rp*g*hl*hl
    fr_diff = 0.0_8
    fr_diff(1) = ur*hr_diff + hr*ur_diff
    fr(1) = hr*ur
    fr_diff(2) = (ur**2+g*0.5_rp*2*hr)*hr_diff + hr*2*ur*ur_diff
    fr(2) = hr*ur*ur + 0.5_rp*g*hr*hr
    temp = sr*fl(1) - sl*fr(1) + sl*sr*(hr+zr-hl-zl)
    flux_diff(1) = temp*philr_diff + philr*(fl(1)*sr_diff+sr*fl_diff(1)-&
&     fr(1)*sl_diff-sl*fr_diff(1)+(hr+zr-hl-zl)*(sr*sl_diff+sl*sr_diff)+&
&     sl*sr*(hr_diff+zr_diff-hl_diff-zl_diff))
    flux(1) = philr*temp
    IF (zerom .LT. sr - sl) THEN
      max1_diff = sr_diff - sl_diff
      max1 = sr - sl
    ELSE
      max1 = zerom
      max1_diff = 0.0_8
    END IF
    temp = (demi*(phir*(hr*hr)-phil*(hl*hl))-fact*(hr+zr-hl-zl))/max1
    s2_diff = g*(demi*(hr**2*phir_diff+phir*2*hr*hr_diff-hl**2*phil_diff&
&     -phil*2*hl*hl_diff)-(hr+zr-hl-zl)*fact_diff-fact*(hr_diff+zr_diff-&
&     hl_diff-zl_diff)-temp*max1_diff)/max1
    s2 = g*temp
    s2l_diff = -(s2*sl_diff+sl*s2_diff)
    s2l = -(sl*s2)
    s2r_diff = s2*sr_diff + sr*s2_diff
    s2r = sr*s2
    temp = phil*fl(2) + s2l
    temp0 = phir*fr(2) - s2r
    temp1 = phir*fr(1) - phil*fl(1)
    flux_diff(2) = temp*sr_diff + sr*(fl(2)*phil_diff+phil*fl_diff(2)+&
&     s2l_diff) - temp0*sl_diff - sl*(fr(2)*phir_diff+phir*fr_diff(2)-&
&     s2r_diff) + temp1*(sr*sl_diff+sl*sr_diff) + sl*sr*(fr(1)*phir_diff&
&     +phir*fr_diff(1)-fl(1)*phil_diff-phil*fl_diff(1))
    flux(2) = sr*temp - sl*temp0 + sl*sr*temp1
    IF (zerom .LT. sr - sl) THEN
      max2_diff = sr_diff - sl_diff
      max2 = sr - sl
    ELSE
      max2 = zerom
      max2_diff = 0.0_8
    END IF
    flux_diff(1:2) = (flux_diff(1:2)-flux(1:2)*max2_diff/max2)/max2
    flux(1:2) = flux(1:2)/max2
    IF (flux(1) .GE. 0) THEN
      flux_diff(3) = vl*flux_diff(1) + flux(1)*vl_diff
      flux(3) = flux(1)*vl
    ELSE
      flux_diff(3) = vr*flux_diff(1) + flux(1)*vr_diff
      flux(3) = flux(1)*vr
    END IF
    IF (hl .LE. heps .AND. zr + hr .LE. zl + heps) THEN
      flux(:) = 0.
      s2l = 0.
      s2r_diff = demi*g*(hr**2*phir_diff+phir*2*hr*hr_diff)
      s2r = phir*demi*g*hr*hr
      flux_diff = 0.0_8
      s2l_diff = 0.0_8
    ELSE IF (hr .LE. heps .AND. zl + hl .LE. zr + heps) THEN
      flux(:) = 0.
      s2l_diff = -(demi*g*(hl**2*phil_diff+phil*2*hl*hl_diff))
      s2l = -(phil*demi*g*hl*hl)
      s2r = 0.
      flux_diff = 0.0_8
      s2r_diff = 0.0_8
    END IF
  END IF
END SUBROUTINE SW_HLLC_SP_DIFF

