!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
!  Differentiation of sw_post_treatment in forward (tangent) mode (with options fixinterface noISIZE):
!   variations   of useful results: *(bc.sum_mass_flux)
!   with respect to varying inputs: *(bc.sum_mass_flux)
!   Plus diff mem management of: bc.sum_mass_flux:in
SUBROUTINE SW_POST_TREATMENT_DIFF(dof, mesh)
  USE M_COMMON ! Replaced by Perl Script
  USE M_MESH ! Replaced by Perl Script
  USE M_MODEL ! Replaced by Perl Script

  USE M_TAP_VARS ! Added by Perl Script -> Need to be filled !!!

  IMPLICIT NONE
  TYPE(UNK), INTENT(IN) :: dof
  TYPE(MSH), INTENT(IN) :: mesh
  INTEGER(ip) :: num_bc
  DO num_bc=1,bc%nb
    IF (temp_scheme(1:2) .EQ. 'rk' .OR. temp_scheme(1:4) .EQ. 'imex') &
&   THEN
      bc_diff%sum_mass_flux(num_bc) = 0.5_rp*bc_diff%sum_mass_flux(&
&       num_bc)
      bc%sum_mass_flux(num_bc) = 0.5_rp*bc%sum_mass_flux(num_bc)
    END IF
  END DO
END SUBROUTINE SW_POST_TREATMENT_DIFF

