MODULE ADMPI
USE MPI

PUBLIC

       EXTERNAL ADMPI_TURN
       EXTERNAL ADMPI_INIT
       EXTERNAL ADMPI_FINALIZE
       EXTERNAL MPI_SEND_D, MPI_SEND_FWD, MPI_SEND_BWD
       EXTERNAL MPI_RECV_D, MPI_RECV_FWD, MPI_RECV_BWD
       EXTERNAL ADMPI_ISEND, ADMPI_ISEND_D, ADMPI_ISEND_FWD
       EXTERNAL ADMPI_ISEND_BWD
       EXTERNAL ADMPI_IRECV, ADMPI_IRECV_D, ADMPI_IRECV_FWD
       EXTERNAL ADMPI_IRECV_BWD
       EXTERNAL ADMPI_WAIT, ADMPI_WAIT_D, ADMPI_WAIT_FWD, ADMPI_WAIT_BWD
       EXTERNAL ADMPI_WAITALL
       EXTERNAL MPI_BARRIER_D, MPI_BARRIER_FWD, MPI_BARRIER_BWD
       EXTERNAL MPI_GATHER_D, MPI_GATHER_FWD, MPI_GATHER_BWD
       EXTERNAL MPI_GATHERV_D, MPI_GATHERV_FWD, MPI_GATHERV_BWD
       EXTERNAL MPI_ALLGATHER_D, MPI_ALLGATHER_FWD, MPI_ALLGATHER_BWD
       EXTERNAL MPI_ALLGATHERV_D, MPI_ALLGATHERV_FWD, MPI_ALLGATHERV_BWD
       EXTERNAL MPI_SCATTER_D, MPI_SCATTER_FWD, MPI_SCATTER_BWD
       EXTERNAL MPI_SCATTERV_D, MPI_SCATTERV_FWD, MPI_SCATTERV_BWD
       EXTERNAL MPI_BCAST_D, MPI_BCAST_FWD, MPI_BCAST_BWD
       EXTERNAL MPI_REDUCE_D, MPI_REDUCE_FWD, MPI_REDUCE_BWD
       EXTERNAL MPI_ALLREDUCE_D, MPI_ALLREDUCE_FWD, MPI_ALLREDUCE_BWD
       EXTERNAL MPI_COMM_DUP_D
       EXTERNAL MPI_COMM_SPLIT_D
       EXTERNAL MPI_COMM_CREATE_D
       EXTERNAL MPI_COMM_FREE_D
       EXTERNAL ADMPI_TYPE_CONTIGUOUS
       EXTERNAL ADMPI_TYPE_CREATE_STRUCT
       EXTERNAL ADMPI_TYPE_CREATE_RESIZED
       EXTERNAL ADMPI_TYPE_COMMIT
       EXTERNAL ADMPI_TYPE_FREE
       EXTERNAL ADMPI_OP_CREATE
       EXTERNAL ADMPI_OP_FREE

END MODULE ADMPI

subroutine ADMPI_FORTRANSETUPBINDINGS()
  USE MPI
  call ADMPI_SENDFORTRANBINDINGS(MPI_BOTTOM, MPI_IN_PLACE, &
     &     MPI_STATUS_IGNORE, MPI_STATUSES_IGNORE, &
     &     MPI_ERRCODES_IGNORE, MPI_ARGV_NULL, MPI_ARGVS_NULL) ;
end subroutine ADMPI_FORTRANSETUPBINDINGS
